# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "3c77b5f5-75f4-467e-955c-b28bf605b25f"
plan_id: "AFT-1.2"
description: "AFTs slow collector"
testbed: TESTBED_DUT_ATE_2LINKS
