# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "a01b6e65-3b45-4e0c-a71d-f451c07fec6b"
plan_id: "Health-1.1"
description: "Generic Health Check"
testbed: TESTBED_DUT
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    consistent_component_names_unsupported: true
    controller_card_cpu_utilization_unsupported: true
    fabric_drop_counter_unsupported: true
    qos_voq_drop_counter_unsupported: true
    qos_inqueue_drop_counter_unsupported: true
    interface_counters_in_unknown_protos_unsupported: true
  }
}
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    cpu_utilization_query_against_base_controller_card_component: true
    cpu_utilization_query_against_base_linecard_component: true
    no_queue_drop_unsupported: true
    interface_ethernet_inblock_errors_unsupported: true
    fabric_drop_counter_unsupported: true
  }
}
tags: TAGS_AGGREGATION
