# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid:  "4fdd3abd-24b6-482c-9b32-da96910ef080"
plan_id:  "System-1.2"
description:  "System g protocol test"
testbed:  TESTBED_DUT
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    p4rt_capabilities_unsupported: true
    gnmi_get_on_root_unsupported: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    gnmi_get_on_root_unsupported: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    gnmi_get_on_root_unsupported: true
    non_standard_grpc_port: true
  }
}
