steps:
- name: gcr.io/$PROJECT_ID/remote-builder
  waitFor: ["-"]
  env:
    - USERNAME=user
    - SSH_ARGS=--internal-ip --ssh-key-expire-after=1d
    - INSTANCE_NAME=fp-build-arista-$BUILD_ID
    - INSTANCE_ARGS=--network cloudbuild-workers --image-project ubuntu-os-cloud --image-family ubuntu-minimal-2004-lts --machine-type e2-standard-4 --boot-disk-size 100GB --preemptible
    - ZONE=us-west1-a
    - REMOTE_WORKSPACE=/tmp/workspace
    - COMMAND=source /tmp/workspace/cloudbuild/setup.sh && source /tmp/workspace/cloudbuild/arista.sh
options:
  pool:
    name: 'projects/disco-idea-817/locations/us-west1/workerPools/featureprofiles-workerpool'
timeout: 1800s
