steps:
  - id: arista_ceos
    name: gcr.io/$PROJECT_ID/remote-builder
    waitFor: ["-"]
    allowFailure: true
    env:
      - USERNAME=user
      - SSH_ARGS=--internal-ip --ssh-key-expire-after=1d
      - INSTANCE_NAME=fp-presubmit-arista-$BUILD_ID
      - INSTANCE_ARGS=--network cloudbuild-workers --image-project gep-kne --image-family kne --machine-type e2-standard-4 --boot-disk-size 100GB --preemptible
      - ZONE=us-west1-a
      - REMOTE_WORKSPACE=/tmp/workspace
      - COMMAND=sudo -iu user /tmp/workspace/cloudbuild/test.sh arista_ceos
  - id: juniper_cptx
    name: gcr.io/$PROJECT_ID/remote-builder
    waitFor: ["-"]
    allowFailure: true
    env:
      - USERNAME=user
      - SSH_ARGS=--internal-ip --ssh-key-expire-after=1d
      - INSTANCE_NAME=fp-presubmit-juniper-$BUILD_ID
      - INSTANCE_ARGS=--network cloudbuild-workers --image-project gep-kne --image-family kne --machine-type n2-standard-16 --boot-disk-size 100GB --enable-nested-virtualization --preemptible
      - ZONE=us-west1-a
      - REMOTE_WORKSPACE=/tmp/workspace
      - COMMAND=sudo -iu user /tmp/workspace/cloudbuild/test.sh juniper_cptx
  - id: cisco_8000e
    name: gcr.io/$PROJECT_ID/remote-builder
    waitFor: ["-"]
    allowFailure: true
    env:
      - USERNAME=user
      - SSH_ARGS=--internal-ip --ssh-key-expire-after=1d
      - INSTANCE_NAME=fp-presubmit-cisco-$BUILD_ID
      - INSTANCE_ARGS=--network cloudbuild-workers --image-project gep-kne --image-family kne --machine-type n2-standard-8 --boot-disk-size 100GB --enable-nested-virtualization --preemptible
      - ZONE=us-west1-a
      - REMOTE_WORKSPACE=/tmp/workspace
      - COMMAND=sudo -iu user /tmp/workspace/cloudbuild/test.sh cisco_8000e
  - id: nokia_srlinux
    name: gcr.io/$PROJECT_ID/remote-builder
    waitFor: ["-"]
    allowFailure: true
    env:
      - USERNAME=user
      - SSH_ARGS=--internal-ip --ssh-key-expire-after=1d
      - INSTANCE_NAME=fp-presubmit-nokia-$BUILD_ID
      - INSTANCE_ARGS=--network cloudbuild-workers --image-project gep-kne --image-family kne --machine-type e2-standard-4 --boot-disk-size 100GB --preemptible
      - ZONE=us-west1-a
      - REMOTE_WORKSPACE=/tmp/workspace
      - COMMAND=sudo -iu user /tmp/workspace/cloudbuild/test.sh nokia_srlinux

timeout: 2700s

options:
  pool:
    name: "projects/disco-idea-817/locations/us-west1/workerPools/featureprofiles-workerpool"
