# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "9e5ec4a5-0adb-48aa-b6c2-c0d604d15934"
plan_id: "OC-26.1"
description: "Network Time Protocol (NTP)"
testbed: TESTBED_DUT
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    ntp_non_default_vrf_unsupported: true
  }
}
