// Code generated by go run tools/addrundata; DO NOT EDIT.
package base_adjacencies_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "RT-2.1"
	rundata.TestDescription = "Base IS-IS Process and Adjacencies"
	rundata.TestUUID = "a5b892e1-192d-45ff-89b5-a84a2865fdb2"
}
