# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "9ff3be0d-84aa-4513-8a6c-bfe497a8ae9e"
plan_id: "gNMI-1.21"
description: "Integrated Circuit Hardware Resource Utilization Test"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    interface_enabled: true
    default_network_instance: "default"
    mismatched_hardware_resource_name_in_component: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_interface_in_default_vrf: true
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ciscoxr8000_integrated_circuit_resource_ft: "ciscoxr-8000-integrated-circuit-resource-ft"
  }
}
tags: TAGS_TRANSIT
