// Code generated by go run tools/addrundata; DO NOT EDIT.
package get_rpc_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "TE-5.1"
	rundata.TestDescription = "gRIBI Get RPC"
	rundata.TestUUID = "86aabaa0-1c61-4604-898b-eb4d5809b650"
}
