# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "500a9a2e-8a3e-4993-ae1c-ac5bb194048e"
plan_id: "RT-3.1"
description: "Policy based VRF selection"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
    interface_ref_interface_id_format: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    static_protocol_name: "static"
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    static_protocol_name: "STATIC"
    interface_config_vrf_before_address: true
    interface_enabled: true
    default_network_instance: "default"
  }
}
