# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "d54b1029-6f8e-4dc7-a50d-99d6e4f59474"
plan_id: "RT-3.2"
description: "Multiple <Protocol, DSCP> Rules for VRF Selection"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
    interface_ref_interface_id_format: true

  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    no_mix_of_tagged_and_untagged_subinterfaces: true
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    no_mix_of_tagged_and_untagged_subinterfaces: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    interface_enabled: true
    default_network_instance: "default"
  }
}
