# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "44fb709e-fc15-4285-94cf-cb6b9dc19d1a"
plan_id: "P4RT-6.1"
description: "Required Packet I/O rate: Performance"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    gribi_mac_override_static_arp_static_route: true
    interface_enabled: true
  }
}
