# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "fbe36d03-20af-43a4-921a-9642e66f051c"
plan_id: "PF-1.9"
description: "Egress handling of TTL"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    interface_enabled: true
    default_network_instance: "default"
    static_mpls_lsp_oc_unsupported: true
    gre_decapsulation_oc_unsupported: true
    decapsulate_gue_oc_unsupported: true
  }
}