# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "3265de19-8fb8-4b0c-8a71-a75df008aa61"
plan_id: "gNOI-3.5"
description: "Copying Debug Files"
testbed: TESTBED_DUT_ATE_2LINKS
