// Code generated by go run tools/addrundata; DO NOT EDIT.
package copying_debug_files_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "gNOI-3.5"
	rundata.TestDescription = "Copying Debug Files"
	rundata.TestUUID = "3265de19-8fb8-4b0c-8a71-a75df008aa61"
}
