// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/cntrsrv/proto/cntr/cntr.proto

package cntr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Service enumerates the services that the dialler can connect to
// in an RPC-content-aware manner.
type Service int32

const (
	Service_ST_UNSPECIFIED Service = 0
	// gNMI indicates that a gNMI check should be initiated, particularly the
	// Capabilities RPC should be sent to the target.
	Service_ST_GNMI Service = 1
	// gRIBI indictes that gRIBI check should be initiated, particularly the
	// Get RPC should be sent to the target.
	Service_ST_GRIBI Service = 2
)

// Enum value maps for Service.
var (
	Service_name = map[int32]string{
		0: "ST_UNSPECIFIED",
		1: "ST_GNMI",
		2: "ST_GRIBI",
	}
	Service_value = map[string]int32{
		"ST_UNSPECIFIED": 0,
		"ST_GNMI":        1,
		"ST_GRIBI":       2,
	}
)

func (x Service) Enum() *Service {
	p := new(Service)
	*p = x
	return p
}

func (x Service) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Service) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_cntrsrv_proto_cntr_cntr_proto_enumTypes[0].Descriptor()
}

func (Service) Type() protoreflect.EnumType {
	return &file_internal_cntrsrv_proto_cntr_cntr_proto_enumTypes[0]
}

func (x Service) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Service.Descriptor instead.
func (Service) EnumDescriptor() ([]byte, []int) {
	return file_internal_cntrsrv_proto_cntr_cntr_proto_rawDescGZIP(), []int{0}
}

type DialRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Address for the container to dial.
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*DialRequest_Ping
	//	*DialRequest_Srv
	Request        isDialRequest_Request `protobuf_oneof:"request"`
	Username       string                `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password       string                `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	TlsCredentials *TLSCredentials       `protobuf:"bytes,6,opt,name=tls_credentials,json=tlsCredentials,proto3" json:"tls_credentials,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DialRequest) Reset() {
	*x = DialRequest{}
	mi := &file_internal_cntrsrv_proto_cntr_cntr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialRequest) ProtoMessage() {}

func (x *DialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cntrsrv_proto_cntr_cntr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialRequest.ProtoReflect.Descriptor instead.
func (*DialRequest) Descriptor() ([]byte, []int) {
	return file_internal_cntrsrv_proto_cntr_cntr_proto_rawDescGZIP(), []int{0}
}

func (x *DialRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *DialRequest) GetRequest() isDialRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *DialRequest) GetPing() *PingRequest {
	if x != nil {
		if x, ok := x.Request.(*DialRequest_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *DialRequest) GetSrv() Service {
	if x != nil {
		if x, ok := x.Request.(*DialRequest_Srv); ok {
			return x.Srv
		}
	}
	return Service_ST_UNSPECIFIED
}

func (x *DialRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DialRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DialRequest) GetTlsCredentials() *TLSCredentials {
	if x != nil {
		return x.TlsCredentials
	}
	return nil
}

type isDialRequest_Request interface {
	isDialRequest_Request()
}

type DialRequest_Ping struct {
	// The payload of a PingRequest, if specified, the container dials and then
	// uses the Ping RPC to send a request.
	Ping *PingRequest `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type DialRequest_Srv struct {
	// Service to be initiated towards the target.
	Srv Service `protobuf:"varint,3,opt,name=srv,proto3,enum=openconfig.featureprofiles.cntr.Service,oneof"`
}

func (*DialRequest_Ping) isDialRequest_Request() {}

func (*DialRequest_Srv) isDialRequest_Request() {}

type TLSCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrustBundle   []byte                 `protobuf:"bytes,1,opt,name=trust_bundle,json=trustBundle,proto3" json:"trust_bundle,omitempty"`
	Certificate   []byte                 `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	PrivateKey    []byte                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	ServerName    string                 `protobuf:"bytes,4,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	SkipVerify    bool                   `protobuf:"varint,5,opt,name=skip_verify,json=skipVerify,proto3" json:"skip_verify,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSCredentials) Reset() {
	*x = TLSCredentials{}
	mi := &file_internal_cntrsrv_proto_cntr_cntr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSCredentials) ProtoMessage() {}

func (x *TLSCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cntrsrv_proto_cntr_cntr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSCredentials.ProtoReflect.Descriptor instead.
func (*TLSCredentials) Descriptor() ([]byte, []int) {
	return file_internal_cntrsrv_proto_cntr_cntr_proto_rawDescGZIP(), []int{1}
}

func (x *TLSCredentials) GetTrustBundle() []byte {
	if x != nil {
		return x.TrustBundle
	}
	return nil
}

func (x *TLSCredentials) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *TLSCredentials) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *TLSCredentials) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *TLSCredentials) GetSkipVerify() bool {
	if x != nil {
		return x.SkipVerify
	}
	return false
}

type DialResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*DialResponse_Pong
	//	*DialResponse_GribiResponse
	//	*DialResponse_GnmiResponse
	Response      isDialResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialResponse) Reset() {
	*x = DialResponse{}
	mi := &file_internal_cntrsrv_proto_cntr_cntr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialResponse) ProtoMessage() {}

func (x *DialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cntrsrv_proto_cntr_cntr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialResponse.ProtoReflect.Descriptor instead.
func (*DialResponse) Descriptor() ([]byte, []int) {
	return file_internal_cntrsrv_proto_cntr_cntr_proto_rawDescGZIP(), []int{2}
}

func (x *DialResponse) GetResponse() isDialResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *DialResponse) GetPong() *PingResponse {
	if x != nil {
		if x, ok := x.Response.(*DialResponse_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *DialResponse) GetGribiResponse() *anypb.Any {
	if x != nil {
		if x, ok := x.Response.(*DialResponse_GribiResponse); ok {
			return x.GribiResponse
		}
	}
	return nil
}

func (x *DialResponse) GetGnmiResponse() *anypb.Any {
	if x != nil {
		if x, ok := x.Response.(*DialResponse_GnmiResponse); ok {
			return x.GnmiResponse
		}
	}
	return nil
}

type isDialResponse_Response interface {
	isDialResponse_Response()
}

type DialResponse_Pong struct {
	// The ping response returned from the remote system, populated when the
	// request specifies a PingRequest.
	Pong *PingResponse `protobuf:"bytes,2,opt,name=pong,proto3,oneof"`
}

type DialResponse_GribiResponse struct {
	// The gRIBI message sent in response to the gRIBI Get RPC. Contains only
	// the first message, and is populated only when the Service in the request
	// is set to GRIBI.
	GribiResponse *anypb.Any `protobuf:"bytes,3,opt,name=gribi_response,json=gribiResponse,proto3,oneof"`
}

type DialResponse_GnmiResponse struct {
	// The gNMI message sent in response to the gNMI Capabilities RPC. Populated
	// only when the Service in the request is set to GNMI.
	GnmiResponse *anypb.Any `protobuf:"bytes,4,opt,name=gnmi_response,json=gnmiResponse,proto3,oneof"`
}

func (*DialResponse_Pong) isDialResponse_Response() {}

func (*DialResponse_GribiResponse) isDialResponse_Response() {}

func (*DialResponse_GnmiResponse) isDialResponse_Response() {}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_cntrsrv_proto_cntr_cntr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cntrsrv_proto_cntr_cntr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_cntrsrv_proto_cntr_cntr_proto_rawDescGZIP(), []int{3}
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp at which the ping response was sent.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_cntrsrv_proto_cntr_cntr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cntrsrv_proto_cntr_cntr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_cntrsrv_proto_cntr_cntr_proto_rawDescGZIP(), []int{4}
}

func (x *PingResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_internal_cntrsrv_proto_cntr_cntr_proto protoreflect.FileDescriptor

const file_internal_cntrsrv_proto_cntr_cntr_proto_rawDesc = "" +
	"\n" +
	"&internal/cntrsrv/proto/cntr/cntr.proto\x12\x1fopenconfig.featureprofiles.cntr\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x02\n" +
	"\vDialRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12B\n" +
	"\x04ping\x18\x02 \x01(\v2,.openconfig.featureprofiles.cntr.PingRequestH\x00R\x04ping\x12<\n" +
	"\x03srv\x18\x03 \x01(\x0e2(.openconfig.featureprofiles.cntr.ServiceH\x00R\x03srv\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12X\n" +
	"\x0ftls_credentials\x18\x06 \x01(\v2/.openconfig.featureprofiles.cntr.TLSCredentialsR\x0etlsCredentialsB\t\n" +
	"\arequest\"\xb8\x01\n" +
	"\x0eTLSCredentials\x12!\n" +
	"\ftrust_bundle\x18\x01 \x01(\fR\vtrustBundle\x12 \n" +
	"\vcertificate\x18\x02 \x01(\fR\vcertificate\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\fR\n" +
	"privateKey\x12\x1f\n" +
	"\vserver_name\x18\x04 \x01(\tR\n" +
	"serverName\x12\x1f\n" +
	"\vskip_verify\x18\x05 \x01(\bR\n" +
	"skipVerify\"\xdb\x01\n" +
	"\fDialResponse\x12C\n" +
	"\x04pong\x18\x02 \x01(\v2-.openconfig.featureprofiles.cntr.PingResponseH\x00R\x04pong\x12=\n" +
	"\x0egribi_response\x18\x03 \x01(\v2\x14.google.protobuf.AnyH\x00R\rgribiResponse\x12;\n" +
	"\rgnmi_response\x18\x04 \x01(\v2\x14.google.protobuf.AnyH\x00R\fgnmiResponseB\n" +
	"\n" +
	"\bresponse\"\r\n" +
	"\vPingRequest\"H\n" +
	"\fPingResponse\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*8\n" +
	"\aService\x12\x12\n" +
	"\x0eST_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aST_GNMI\x10\x01\x12\f\n" +
	"\bST_GRIBI\x10\x022\xd0\x01\n" +
	"\x04Cntr\x12c\n" +
	"\x04Dial\x12,.openconfig.featureprofiles.cntr.DialRequest\x1a-.openconfig.featureprofiles.cntr.DialResponse\x12c\n" +
	"\x04Ping\x12,.openconfig.featureprofiles.cntr.PingRequest\x1a-.openconfig.featureprofiles.cntr.PingResponseBJP\x01ZFgithub.com/openconfig/featureprofiles/internal/cntrsrv/proto/cntr;cntrb\x06proto3"

var (
	file_internal_cntrsrv_proto_cntr_cntr_proto_rawDescOnce sync.Once
	file_internal_cntrsrv_proto_cntr_cntr_proto_rawDescData []byte
)

func file_internal_cntrsrv_proto_cntr_cntr_proto_rawDescGZIP() []byte {
	file_internal_cntrsrv_proto_cntr_cntr_proto_rawDescOnce.Do(func() {
		file_internal_cntrsrv_proto_cntr_cntr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_cntrsrv_proto_cntr_cntr_proto_rawDesc), len(file_internal_cntrsrv_proto_cntr_cntr_proto_rawDesc)))
	})
	return file_internal_cntrsrv_proto_cntr_cntr_proto_rawDescData
}

var file_internal_cntrsrv_proto_cntr_cntr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_cntrsrv_proto_cntr_cntr_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_cntrsrv_proto_cntr_cntr_proto_goTypes = []any{
	(Service)(0),                  // 0: openconfig.featureprofiles.cntr.Service
	(*DialRequest)(nil),           // 1: openconfig.featureprofiles.cntr.DialRequest
	(*TLSCredentials)(nil),        // 2: openconfig.featureprofiles.cntr.TLSCredentials
	(*DialResponse)(nil),          // 3: openconfig.featureprofiles.cntr.DialResponse
	(*PingRequest)(nil),           // 4: openconfig.featureprofiles.cntr.PingRequest
	(*PingResponse)(nil),          // 5: openconfig.featureprofiles.cntr.PingResponse
	(*anypb.Any)(nil),             // 6: google.protobuf.Any
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_internal_cntrsrv_proto_cntr_cntr_proto_depIdxs = []int32{
	4, // 0: openconfig.featureprofiles.cntr.DialRequest.ping:type_name -> openconfig.featureprofiles.cntr.PingRequest
	0, // 1: openconfig.featureprofiles.cntr.DialRequest.srv:type_name -> openconfig.featureprofiles.cntr.Service
	2, // 2: openconfig.featureprofiles.cntr.DialRequest.tls_credentials:type_name -> openconfig.featureprofiles.cntr.TLSCredentials
	5, // 3: openconfig.featureprofiles.cntr.DialResponse.pong:type_name -> openconfig.featureprofiles.cntr.PingResponse
	6, // 4: openconfig.featureprofiles.cntr.DialResponse.gribi_response:type_name -> google.protobuf.Any
	6, // 5: openconfig.featureprofiles.cntr.DialResponse.gnmi_response:type_name -> google.protobuf.Any
	7, // 6: openconfig.featureprofiles.cntr.PingResponse.timestamp:type_name -> google.protobuf.Timestamp
	1, // 7: openconfig.featureprofiles.cntr.Cntr.Dial:input_type -> openconfig.featureprofiles.cntr.DialRequest
	4, // 8: openconfig.featureprofiles.cntr.Cntr.Ping:input_type -> openconfig.featureprofiles.cntr.PingRequest
	3, // 9: openconfig.featureprofiles.cntr.Cntr.Dial:output_type -> openconfig.featureprofiles.cntr.DialResponse
	5, // 10: openconfig.featureprofiles.cntr.Cntr.Ping:output_type -> openconfig.featureprofiles.cntr.PingResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_internal_cntrsrv_proto_cntr_cntr_proto_init() }
func file_internal_cntrsrv_proto_cntr_cntr_proto_init() {
	if File_internal_cntrsrv_proto_cntr_cntr_proto != nil {
		return
	}
	file_internal_cntrsrv_proto_cntr_cntr_proto_msgTypes[0].OneofWrappers = []any{
		(*DialRequest_Ping)(nil),
		(*DialRequest_Srv)(nil),
	}
	file_internal_cntrsrv_proto_cntr_cntr_proto_msgTypes[2].OneofWrappers = []any{
		(*DialResponse_Pong)(nil),
		(*DialResponse_GribiResponse)(nil),
		(*DialResponse_GnmiResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_cntrsrv_proto_cntr_cntr_proto_rawDesc), len(file_internal_cntrsrv_proto_cntr_cntr_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_cntrsrv_proto_cntr_cntr_proto_goTypes,
		DependencyIndexes: file_internal_cntrsrv_proto_cntr_cntr_proto_depIdxs,
		EnumInfos:         file_internal_cntrsrv_proto_cntr_cntr_proto_enumTypes,
		MessageInfos:      file_internal_cntrsrv_proto_cntr_cntr_proto_msgTypes,
	}.Build()
	File_internal_cntrsrv_proto_cntr_cntr_proto = out.File
	file_internal_cntrsrv_proto_cntr_cntr_proto_goTypes = nil
	file_internal_cntrsrv_proto_cntr_cntr_proto_depIdxs = nil
}
