// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.9
// source: cntr.proto

package cntr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Service enumerates the services that the dialler can connect to
// in an RPC-content-aware manner.
type Service int32

const (
	Service_ST_UNSPECIFIED Service = 0
	// gNMI indicates that a gNMI check should be initiated, particularly the
	// Capabilities RPC should be sent to the target.
	Service_ST_GNMI Service = 1
	// gRIBI indictes that gRIBI check should be initiated, particularly the
	// Get RPC should be sent to the target.
	Service_ST_GRIBI Service = 2
)

// Enum value maps for Service.
var (
	Service_name = map[int32]string{
		0: "ST_UNSPECIFIED",
		1: "ST_GNMI",
		2: "ST_GRIBI",
	}
	Service_value = map[string]int32{
		"ST_UNSPECIFIED": 0,
		"ST_GNMI":        1,
		"ST_GRIBI":       2,
	}
)

func (x Service) Enum() *Service {
	p := new(Service)
	*p = x
	return p
}

func (x Service) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Service) Descriptor() protoreflect.EnumDescriptor {
	return file_cntr_proto_enumTypes[0].Descriptor()
}

func (Service) Type() protoreflect.EnumType {
	return &file_cntr_proto_enumTypes[0]
}

func (x Service) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Service.Descriptor instead.
func (Service) EnumDescriptor() ([]byte, []int) {
	return file_cntr_proto_rawDescGZIP(), []int{0}
}

type DialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Address for the container to dial.
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// Types that are assignable to Request:
	//	*DialRequest_Ping
	//	*DialRequest_Srv
	Request isDialRequest_Request `protobuf_oneof:"request"`
}

func (x *DialRequest) Reset() {
	*x = DialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cntr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialRequest) ProtoMessage() {}

func (x *DialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cntr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialRequest.ProtoReflect.Descriptor instead.
func (*DialRequest) Descriptor() ([]byte, []int) {
	return file_cntr_proto_rawDescGZIP(), []int{0}
}

func (x *DialRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (m *DialRequest) GetRequest() isDialRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *DialRequest) GetPing() *PingRequest {
	if x, ok := x.GetRequest().(*DialRequest_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *DialRequest) GetSrv() Service {
	if x, ok := x.GetRequest().(*DialRequest_Srv); ok {
		return x.Srv
	}
	return Service_ST_UNSPECIFIED
}

type isDialRequest_Request interface {
	isDialRequest_Request()
}

type DialRequest_Ping struct {
	// The payload of a PingRequest, if specified, the container dials and then
	// uses the Ping RPC to send a request.
	Ping *PingRequest `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type DialRequest_Srv struct {
	// Service to be initiated towards the target.
	Srv Service `protobuf:"varint,3,opt,name=srv,proto3,enum=openconfig.featureprofiles.cntr.Service,oneof"`
}

func (*DialRequest_Ping) isDialRequest_Request() {}

func (*DialRequest_Srv) isDialRequest_Request() {}

type DialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*DialResponse_Pong
	//	*DialResponse_GribiResponse
	//	*DialResponse_GnmiResponse
	Response isDialResponse_Response `protobuf_oneof:"response"`
}

func (x *DialResponse) Reset() {
	*x = DialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cntr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialResponse) ProtoMessage() {}

func (x *DialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cntr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialResponse.ProtoReflect.Descriptor instead.
func (*DialResponse) Descriptor() ([]byte, []int) {
	return file_cntr_proto_rawDescGZIP(), []int{1}
}

func (m *DialResponse) GetResponse() isDialResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *DialResponse) GetPong() *PingResponse {
	if x, ok := x.GetResponse().(*DialResponse_Pong); ok {
		return x.Pong
	}
	return nil
}

func (x *DialResponse) GetGribiResponse() *anypb.Any {
	if x, ok := x.GetResponse().(*DialResponse_GribiResponse); ok {
		return x.GribiResponse
	}
	return nil
}

func (x *DialResponse) GetGnmiResponse() *anypb.Any {
	if x, ok := x.GetResponse().(*DialResponse_GnmiResponse); ok {
		return x.GnmiResponse
	}
	return nil
}

type isDialResponse_Response interface {
	isDialResponse_Response()
}

type DialResponse_Pong struct {
	// The ping response returned from the remote system, populated when the
	// request specifies a PingRequest.
	Pong *PingResponse `protobuf:"bytes,2,opt,name=pong,proto3,oneof"`
}

type DialResponse_GribiResponse struct {
	// The gRIBI message sent in response to the gRIBI Get RPC. Contains only
	// the first message, and is populated only when the Service in the request
	// is set to GRIBI.
	GribiResponse *anypb.Any `protobuf:"bytes,3,opt,name=gribi_response,json=gribiResponse,proto3,oneof"`
}

type DialResponse_GnmiResponse struct {
	// The gNMI message sent in response to the gNMI Capabilities RPC. Populated
	// only when the Service in the request is set to GNMI.
	GnmiResponse *anypb.Any `protobuf:"bytes,4,opt,name=gnmi_response,json=gnmiResponse,proto3,oneof"`
}

func (*DialResponse_Pong) isDialResponse_Response() {}

func (*DialResponse_GribiResponse) isDialResponse_Response() {}

func (*DialResponse_GnmiResponse) isDialResponse_Response() {}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cntr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cntr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_cntr_proto_rawDescGZIP(), []int{2}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Timestamp at which the ping response was sent.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cntr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cntr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_cntr_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_cntr_proto protoreflect.FileDescriptor

var file_cntr_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x6e, 0x74, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x6f, 0x70,
	0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x63, 0x6e, 0x74, 0x72, 0x1a, 0x19, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61,
	0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xae, 0x01, 0x0a, 0x0b, 0x44, 0x69,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x42, 0x0a,
	0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6f, 0x70,
	0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x63, 0x6e, 0x74, 0x72, 0x2e, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e,
	0x67, 0x12, 0x3c, 0x0a, 0x03, 0x73, 0x72, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28,
	0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x66, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x63, 0x6e, 0x74, 0x72,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x48, 0x00, 0x52, 0x03, 0x73, 0x72, 0x76, 0x42,
	0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xdb, 0x01, 0x0a, 0x0c, 0x44,
	0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x04, 0x70,
	0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6f, 0x70, 0x65, 0x6e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x63, 0x6e, 0x74, 0x72, 0x2e, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67,
	0x12, 0x3d, 0x0a, 0x0e, 0x67, 0x72, 0x69, 0x62, 0x69, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x48, 0x00,
	0x52, 0x0d, 0x67, 0x72, 0x69, 0x62, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3b, 0x0a, 0x0d, 0x67, 0x6e, 0x6d, 0x69, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x48, 0x00, 0x52, 0x0c,
	0x67, 0x6e, 0x6d, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2a, 0x38, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x0e,
	0x53, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x5f, 0x47, 0x4e, 0x4d, 0x49, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x53, 0x54, 0x5f, 0x47, 0x52, 0x49, 0x42, 0x49, 0x10, 0x02, 0x32, 0xd0, 0x01, 0x0a, 0x04,
	0x43, 0x6e, 0x74, 0x72, 0x12, 0x63, 0x0a, 0x04, 0x44, 0x69, 0x61, 0x6c, 0x12, 0x2c, 0x2e, 0x6f,
	0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x63, 0x6e, 0x74, 0x72, 0x2e, 0x44,
	0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x63, 0x6e, 0x74, 0x72, 0x2e, 0x44, 0x69, 0x61,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x04, 0x50, 0x69, 0x6e,
	0x67, 0x12, 0x2c, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x63,
	0x6e, 0x74, 0x72, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2d, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x66, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x63, 0x6e, 0x74,
	0x72, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x49,
	0x50, 0x01, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x2f, 0x6f, 0x70,
	0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x63, 0x6e, 0x74, 0x72, 0x73, 0x72, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x63, 0x6e, 0x74, 0x72, 0x3b, 0x63, 0x6e, 0x74, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_cntr_proto_rawDescOnce sync.Once
	file_cntr_proto_rawDescData = file_cntr_proto_rawDesc
)

func file_cntr_proto_rawDescGZIP() []byte {
	file_cntr_proto_rawDescOnce.Do(func() {
		file_cntr_proto_rawDescData = protoimpl.X.CompressGZIP(file_cntr_proto_rawDescData)
	})
	return file_cntr_proto_rawDescData
}

var file_cntr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cntr_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cntr_proto_goTypes = []interface{}{
	(Service)(0),                  // 0: openconfig.featureprofiles.cntr.Service
	(*DialRequest)(nil),           // 1: openconfig.featureprofiles.cntr.DialRequest
	(*DialResponse)(nil),          // 2: openconfig.featureprofiles.cntr.DialResponse
	(*PingRequest)(nil),           // 3: openconfig.featureprofiles.cntr.PingRequest
	(*PingResponse)(nil),          // 4: openconfig.featureprofiles.cntr.PingResponse
	(*anypb.Any)(nil),             // 5: google.protobuf.Any
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_cntr_proto_depIdxs = []int32{
	3, // 0: openconfig.featureprofiles.cntr.DialRequest.ping:type_name -> openconfig.featureprofiles.cntr.PingRequest
	0, // 1: openconfig.featureprofiles.cntr.DialRequest.srv:type_name -> openconfig.featureprofiles.cntr.Service
	4, // 2: openconfig.featureprofiles.cntr.DialResponse.pong:type_name -> openconfig.featureprofiles.cntr.PingResponse
	5, // 3: openconfig.featureprofiles.cntr.DialResponse.gribi_response:type_name -> google.protobuf.Any
	5, // 4: openconfig.featureprofiles.cntr.DialResponse.gnmi_response:type_name -> google.protobuf.Any
	6, // 5: openconfig.featureprofiles.cntr.PingResponse.timestamp:type_name -> google.protobuf.Timestamp
	1, // 6: openconfig.featureprofiles.cntr.Cntr.Dial:input_type -> openconfig.featureprofiles.cntr.DialRequest
	3, // 7: openconfig.featureprofiles.cntr.Cntr.Ping:input_type -> openconfig.featureprofiles.cntr.PingRequest
	2, // 8: openconfig.featureprofiles.cntr.Cntr.Dial:output_type -> openconfig.featureprofiles.cntr.DialResponse
	4, // 9: openconfig.featureprofiles.cntr.Cntr.Ping:output_type -> openconfig.featureprofiles.cntr.PingResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_cntr_proto_init() }
func file_cntr_proto_init() {
	if File_cntr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cntr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cntr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cntr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cntr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cntr_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*DialRequest_Ping)(nil),
		(*DialRequest_Srv)(nil),
	}
	file_cntr_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*DialResponse_Pong)(nil),
		(*DialResponse_GribiResponse)(nil),
		(*DialResponse_GnmiResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cntr_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cntr_proto_goTypes,
		DependencyIndexes: file_cntr_proto_depIdxs,
		EnumInfos:         file_cntr_proto_enumTypes,
		MessageInfos:      file_cntr_proto_msgTypes,
	}.Build()
	File_cntr_proto = out.File
	file_cntr_proto_rawDesc = nil
	file_cntr_proto_goTypes = nil
	file_cntr_proto_depIdxs = nil
}
