
id {
  name: "isis_auth"
  version: 1
}

# Global

# Global Authentication
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/global/config/authentication-check"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/global/state/authentication-check"
}

# Levels

# Level authentication enable
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/config/enabled"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/state/enabled"
}

# Level csnp authentication
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/config/disable-csnp"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/state/disable-csnp"
}

# Level psnp authentication
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/config/disable-psnp"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/state/disable-psnp"
}

# Level lsp authentication
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/config/disable-lsp"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/state/disable-lsp"
}

# Level authentication keychain
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/config/keychain"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/state/keychain"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/config/auth-mode"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/state/auth-mode"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/config/auth-password"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/state/auth-password"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/config/auth-type"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/state/auth-type"
}

# Interfaces authentication hello authentication
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/authentication/config/enabled"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/authentication/state/enabled"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/hello-authentication/config/auth-mode"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/hello-authentication/state/auth-mode"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/hello-authentication/config/auth-password"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/hello-authentication/state/auth-password"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/hello-authentication/config/enabled"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/hello-authentication/state/enabled"
}

# Interfaces authentication key authentication password
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/authentication/config/keychain"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/authentication/state/keychain"
}
