// Code generated by go run tools/addrundata; DO NOT EDIT.
package localbgp_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "RT-1.7"
	rundata.TestDescription = "Local BGP Test"
	rundata.TestUUID = "78ceceb4-cd33-4d4c-b5aa-b7844d4dd4f1"
}
