// Code generated by go run tools/addrundata; DO NOT EDIT.
package google_discovery_protocol_packetin_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "P4RT-3.1"
	rundata.TestDescription = "Google Discovery Protocol: PacketIn"
	rundata.TestUUID = "d944e6e8-268c-4e37-87a2-df779d19dbde"
}
