# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata
uuid: "376d3561-4271-4efc-be63-3eec7b56b86d"
plan_id: "TRANSCEIVER-7"
description: "Telemetry: 400ZR Optics inventory info streaming"
testbed: TESTBED_DUT_400ZR
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    default_network_instance: "default"
    missing_port_to_optical_channel_component_mapping: true
  }
}
