# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata
uuid: "c09345b2-bddf-4e5c-b4c4-22424e8cb602"
plan_id: "TE-6.3"
description: "Route Leakage between Non Default VRF"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    interface_enabled: true
    default_network_instance: "default"
    network_instance_import_export_policy_oc_unsupported: true
  }
}
tags: TAGS_AGGREGATION
