# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "be382dda-88e8-427c-be95-cb39f3253e18"
plan_id: "TE-4.2"
description: "Persistence Mode"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    interface_enabled: true

  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    interface_enabled: true
  }
}
