// Code generated by go run tools/addrundata; DO NOT EDIT.
package persistence_mode_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "TE-4.2"
	rundata.TestDescription = "Persistence Mode"
	rundata.TestUUID = "be382dda-88e8-427c-be95-cb39f3253e18"
}
