// Code generated by go run tools/addrundata; DO NOT EDIT.
package p4rt_election_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "P4RT-2.1"
	rundata.TestDescription = "P4RT Election"
	rundata.TestUUID = "73bf3d88-e5c1-4d30-9fae-f40b8363044f"
}
