# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "ed6b4f14-d5bb-4ee1-bff8-cc9f84aeb955"
plan_id: "TRANSCEIVER-102"
description: "Telemetry: ZR terminal-device OC paths streaming."
testbed: TESTBED_DUT_400ZR
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    default_network_instance: "default"
    channel_assignment_rate_class_parameters_unsupported: true
    missing_port_to_optical_channel_component_mapping: true
    otn_channel_trib_unsupported: true
    otn_to_eth_assignment: true
  }
}