// Code generated by go run tools/addrundata; DO NOT EDIT.
package ping_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "gNOI-5.1"
	rundata.TestDescription = "Ping Test"
	rundata.TestUUID = "24dc9bcf-f76c-4ac4-a268-35d417d01a3d"
}
