// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: release_intent.proto

package release_intent_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PlatformType defines the target execution environment for qualification.
type PlatformType int32

const (
	PlatformType_PLATFORM_TYPE_UNSPECIFIED PlatformType = 0
	// Execution on physical hardware testbeds.
	PlatformType_PLATFORM_TYPE_HARDWARE PlatformType = 1
	// Execution in Kubernetes Network Emulation (KNE) virtual environment.
	PlatformType_PLATFORM_TYPE_KNE PlatformType = 2
)

// Enum value maps for PlatformType.
var (
	PlatformType_name = map[int32]string{
		0: "PLATFORM_TYPE_UNSPECIFIED",
		1: "PLATFORM_TYPE_HARDWARE",
		2: "PLATFORM_TYPE_KNE",
	}
	PlatformType_value = map[string]int32{
		"PLATFORM_TYPE_UNSPECIFIED": 0,
		"PLATFORM_TYPE_HARDWARE":    1,
		"PLATFORM_TYPE_KNE":         2,
	}
)

func (x PlatformType) Enum() *PlatformType {
	p := new(PlatformType)
	*p = x
	return p
}

func (x PlatformType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlatformType) Descriptor() protoreflect.EnumDescriptor {
	return file_release_intent_proto_enumTypes[0].Descriptor()
}

func (PlatformType) Type() protoreflect.EnumType {
	return &file_release_intent_proto_enumTypes[0]
}

func (x PlatformType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlatformType.Descriptor instead.
func (PlatformType) EnumDescriptor() ([]byte, []int) {
	return file_release_intent_proto_rawDescGZIP(), []int{0}
}

// ReleaseIntent defines the set of feature profile tests required for
// qualifying a target release.
type ReleaseIntent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Canonical identifier for the release (e.g., "August_2026_GA").
	ReleaseId string `protobuf:"bytes,1,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	// List of intended feature profile test IDs required to pass qualification
	// (e.g., "ACL-1.2", "gNOI-4.1").
	IntendedTestIds []string `protobuf:"bytes,2,rep,name=intended_test_ids,json=intendedTestIds,proto3" json:"intended_test_ids,omitempty"`
	// Target chassis Model Part Numbers (e.g., "DCS-7280CR3K-32D4",
	// "3HE14838AA"). Multiple MPNs may be specified for abstract SKUs with
	// multiple hardware variants.
	ChassisMpns []string `protobuf:"bytes,3,rep,name=chassis_mpns,json=chassisMpns,proto3" json:"chassis_mpns,omitempty"`
	// Target execution platform (e.g., HARDWARE or KNE virtual environment).
	TargetPlatform PlatformType `protobuf:"varint,4,opt,name=target_platform,json=targetPlatform,proto3,enum=openconfig.qualificationreporter.PlatformType" json:"target_platform,omitempty"`
}

func (x *ReleaseIntent) Reset() {
	*x = ReleaseIntent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_release_intent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseIntent) ProtoMessage() {}

func (x *ReleaseIntent) ProtoReflect() protoreflect.Message {
	mi := &file_release_intent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseIntent.ProtoReflect.Descriptor instead.
func (*ReleaseIntent) Descriptor() ([]byte, []int) {
	return file_release_intent_proto_rawDescGZIP(), []int{0}
}

func (x *ReleaseIntent) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *ReleaseIntent) GetIntendedTestIds() []string {
	if x != nil {
		return x.IntendedTestIds
	}
	return nil
}

func (x *ReleaseIntent) GetChassisMpns() []string {
	if x != nil {
		return x.ChassisMpns
	}
	return nil
}

func (x *ReleaseIntent) GetTargetPlatform() PlatformType {
	if x != nil {
		return x.TargetPlatform
	}
	return PlatformType_PLATFORM_TYPE_UNSPECIFIED
}

var File_release_intent_proto protoreflect.FileDescriptor

var file_release_intent_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x22, 0xd6, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x69, 0x6e, 0x74,
	0x65, 0x6e, 0x64, 0x65, 0x64, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x54, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x73, 0x73, 0x69, 0x73,
	0x5f, 0x6d, 0x70, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61,
	0x73, 0x73, 0x69, 0x73, 0x4d, 0x70, 0x6e, 0x73, 0x12, 0x57, 0x0a, 0x0f, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x2e, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x71,
	0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x2a, 0x60, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1d, 0x0a, 0x19, 0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x1a, 0x0a, 0x16, 0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x48, 0x41, 0x52, 0x44, 0x57, 0x41, 0x52, 0x45, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11,
	0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4b, 0x4e,
	0x45, 0x10, 0x02, 0x42, 0x5d, 0x5a, 0x5b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x66, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x5f, 0x67, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x72, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x67, 0x6f, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_release_intent_proto_rawDescOnce sync.Once
	file_release_intent_proto_rawDescData = file_release_intent_proto_rawDesc
)

func file_release_intent_proto_rawDescGZIP() []byte {
	file_release_intent_proto_rawDescOnce.Do(func() {
		file_release_intent_proto_rawDescData = protoimpl.X.CompressGZIP(file_release_intent_proto_rawDescData)
	})
	return file_release_intent_proto_rawDescData
}

var file_release_intent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_release_intent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_release_intent_proto_goTypes = []any{
	(PlatformType)(0),     // 0: openconfig.qualificationreporter.PlatformType
	(*ReleaseIntent)(nil), // 1: openconfig.qualificationreporter.ReleaseIntent
}
var file_release_intent_proto_depIdxs = []int32{
	0, // 0: openconfig.qualificationreporter.ReleaseIntent.target_platform:type_name -> openconfig.qualificationreporter.PlatformType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_release_intent_proto_init() }
func file_release_intent_proto_init() {
	if File_release_intent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_release_intent_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ReleaseIntent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_release_intent_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_release_intent_proto_goTypes,
		DependencyIndexes: file_release_intent_proto_depIdxs,
		EnumInfos:         file_release_intent_proto_enumTypes,
		MessageInfos:      file_release_intent_proto_msgTypes,
	}.Build()
	File_release_intent_proto = out.File
	file_release_intent_proto_rawDesc = nil
	file_release_intent_proto_goTypes = nil
	file_release_intent_proto_depIdxs = nil
}
