# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata
uuid: "2ab734c3-2d1a-48b2-9243-ad00a0d3738e"
plan_id: "gNOI-2.2"
description: "Single-Chassis Dual-Mode Link Qualification"
testbed: TESTBED_DUT_400ZR_100G_4LINKS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    default_network_instance: "default"
  }
}

