# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "4632f134-71e6-46a2-ac2a-b1ff6a3444e6"
plan_id: "Credentialz-2"
description: "SSH Password Login Disallowed"
testbed: TESTBED_DUT

platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    ssh_server_counters_unsupported: true
  }
}