# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "3cf4e073-148a-4b92-b12c-1bfb4d5dce61"
plan_id: "AFT-6.1"
description: "AFT Prefix Filtering"
testbed: TESTBED_DUT_ATE_2LINKS
