# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "58c13a5a-d3b3-4a2c-98a7-0404596ee8ea"
plan_id: "gNMI-1.10"
description: "Telemetry: Basic Check"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
    hardware_model_regex: ".*820.*|xrd"
  }
  deviations: {
    ipv4_missing_enabled: true
    interface_counters_from_container: true
  }
}
platform_exceptions: {
  platform: {
    vendor: CISCO
    hardware_model_regex: "CISCO-8808"
  }
  deviations: {
    ipv4_missing_enabled: true
    interface_counters_from_container: true
    os_component_parent_is_supervisor_or_linecard: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    qos_dropped_octets: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
    hardware_model_regex: "DCS-78.*|ceos"
  }
  deviations: {
    interface_enabled: true
    default_network_instance: "default"
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
    hardware_model_regex: "DCS-7280CR3K-32D4"
  }
  deviations: {
    interface_enabled: true
    default_network_instance: "default"
    os_component_parent_is_chassis: true
  }
}
path_presence_test: true
