# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "a7283b91-2e40-40eb-8988-f87443e4585d"
plan_id: "DP-1.12"
description: "ECN enabled traffic test"
testbed: TESTBED_DUT_ATE_4LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    interface_enabled: true
    explicit_interface_in_default_vrf: true
    qos_queue_requires_id: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    interface_enabled: true
    default_network_instance: "default"
    omit_l2_mtu: true
  }
}
