// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: internal/fperrors/error_category.proto

package fperrors_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCategory categorizes the failures in featureprofiles tests.
type ErrorCategory int32

const (
	ErrorCategory_ERROR_CATEGORY_UNSPECIFIED ErrorCategory = 0
	// Indicates that OTG or DUT traffic generation completely failed (e.g., 0 tx packets).
	ErrorCategory_ERROR_CATEGORY_TRAFFIC_GENERATION_FAILED ErrorCategory = 1
	// Indicates an anomaly in traffic validation, such as Rx > Tx packets.
	ErrorCategory_ERROR_CATEGORY_TRAFFIC_VALIDATION_ANOMALY ErrorCategory = 2
	// Indicates a generic test assertion failure, such as loss percentage out of bounds.
	ErrorCategory_ERROR_CATEGORY_TEST_ASSERTION_FAILURE ErrorCategory = 3
)

// Enum value maps for ErrorCategory.
var (
	ErrorCategory_name = map[int32]string{
		0: "ERROR_CATEGORY_UNSPECIFIED",
		1: "ERROR_CATEGORY_TRAFFIC_GENERATION_FAILED",
		2: "ERROR_CATEGORY_TRAFFIC_VALIDATION_ANOMALY",
		3: "ERROR_CATEGORY_TEST_ASSERTION_FAILURE",
	}
	ErrorCategory_value = map[string]int32{
		"ERROR_CATEGORY_UNSPECIFIED":                0,
		"ERROR_CATEGORY_TRAFFIC_GENERATION_FAILED":  1,
		"ERROR_CATEGORY_TRAFFIC_VALIDATION_ANOMALY": 2,
		"ERROR_CATEGORY_TEST_ASSERTION_FAILURE":     3,
	}
)

func (x ErrorCategory) Enum() *ErrorCategory {
	p := new(ErrorCategory)
	*p = x
	return p
}

func (x ErrorCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_fperrors_error_category_proto_enumTypes[0].Descriptor()
}

func (ErrorCategory) Type() protoreflect.EnumType {
	return &file_internal_fperrors_error_category_proto_enumTypes[0]
}

func (x ErrorCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCategory.Descriptor instead.
func (ErrorCategory) EnumDescriptor() ([]byte, []int) {
	return file_internal_fperrors_error_category_proto_rawDescGZIP(), []int{0}
}

var File_internal_fperrors_error_category_proto protoreflect.FileDescriptor

const file_internal_fperrors_error_category_proto_rawDesc = "" +
	"\n" +
	"&internal/fperrors/error_category.proto\x12#openconfig.featureprofiles.fperrors*\xb7\x01\n" +
	"\rErrorCategory\x12\x1e\n" +
	"\x1aERROR_CATEGORY_UNSPECIFIED\x10\x00\x12,\n" +
	"(ERROR_CATEGORY_TRAFFIC_GENERATION_FAILED\x10\x01\x12-\n" +
	")ERROR_CATEGORY_TRAFFIC_VALIDATION_ANOMALY\x10\x02\x12)\n" +
	"%ERROR_CATEGORY_TEST_ASSERTION_FAILURE\x10\x03BKZIgithub.com/openconfig/featureprofiles/internal/fperrors/fperrors_go_protob\x06proto3"

var (
	file_internal_fperrors_error_category_proto_rawDescOnce sync.Once
	file_internal_fperrors_error_category_proto_rawDescData []byte
)

func file_internal_fperrors_error_category_proto_rawDescGZIP() []byte {
	file_internal_fperrors_error_category_proto_rawDescOnce.Do(func() {
		file_internal_fperrors_error_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_fperrors_error_category_proto_rawDesc), len(file_internal_fperrors_error_category_proto_rawDesc)))
	})
	return file_internal_fperrors_error_category_proto_rawDescData
}

var file_internal_fperrors_error_category_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_fperrors_error_category_proto_goTypes = []any{
	(ErrorCategory)(0), // 0: openconfig.featureprofiles.fperrors.ErrorCategory
}
var file_internal_fperrors_error_category_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_fperrors_error_category_proto_init() }
func file_internal_fperrors_error_category_proto_init() {
	if File_internal_fperrors_error_category_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_fperrors_error_category_proto_rawDesc), len(file_internal_fperrors_error_category_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_fperrors_error_category_proto_goTypes,
		DependencyIndexes: file_internal_fperrors_error_category_proto_depIdxs,
		EnumInfos:         file_internal_fperrors_error_category_proto_enumTypes,
	}.Build()
	File_internal_fperrors_error_category_proto = out.File
	file_internal_fperrors_error_category_proto_goTypes = nil
	file_internal_fperrors_error_category_proto_depIdxs = nil
}
