# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "43776caf-2340-4f35-ab30-8c763feaadae"
plan_id: "RT-5.9"
description: "Disable IPv6 ND Router Arvetisment"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    ipv6_router_advertisement_config_unsupported: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    interface_enabled: true
    ipv6_router_advertisement_interval_unsupported: true
  }
}
