name: "arista-ceos-dut"
nodes: {
    name: "dut"
    vendor: ARISTA
    model: "ceos"
    os: "eos"
    config: {
        image: "ceos:latest"
        file: "config.cfg"
        config_path: "/mnt/flash"
        config_file: "startup-config"
        cert: {
            self_signed: {
                cert_name: "gnmiCert.pem"
                key_name: "gnmiCertKey.pem"
                key_size: 4096
            }
        }
    }
}
