name: "arista-ceos-dut"
nodes: {
    name: "dut"
    vendor: ARISTA
    model: "ceos"
    os: "eos"
    config: {
        image: "ceos:latest"
        file: "config.cfg"
        config_path: "/mnt/flash"
        config_file: "startup-config"
        cert: {
            self_signed: {
                cert_name: "gnmiCert.pem"
                key_name: "gnmiCertKey.pem"
                key_size: 4096
            }
        }
    }
    services: {
        key: 22
        value: {
            name: "ssh"
            inside: 22
        }
    }
    services: {
        key: 443
        value: {
            name: "ssl"
            inside: 443
        }
    }
    services: {
        key: 9339
        value: {
            name: "gnmi"
            inside: 9339
        }
    }
    services: {
        key: 9340
        value: {
            name: "gribi"
            inside: 9340
        }
    }
    services: {
        key: 9559
        value: {
            name: "p4rt"
            inside: 9559
        }
    }
}
