name: "arista-ceos-dutate"
nodes: {
    name: "dut"
    vendor: ARISTA
    model: "ceos"
    os: "eos"
    services: {
        key: 22
        value: {
            name: "ssh"
            inside: 22
        }
    }
    services: {
        key: 443
        value: {
            name: "ssl"
            inside: 443
        }
    }
    services: {
        key: 9339
        value: {
            name: "gnmi"
            inside: 9339
        }
    }
    services: {
        key: 9340
        value: {
            name: "gribi"
            inside: 9340
        }
    }
    services: {
        key: 9559
        value: {
            name: "p4rt"
            inside: 9559
        }
    }
    config: {
        image: "ceos:latest"
        file: "config.cfg"
        config_path: "/mnt/flash"
        config_file: "startup-config"
        cert: {
            self_signed: {
                cert_name: "gnmiCert.pem"
                key_name: "gnmiCertKey.pem"
                key_size: 4096
            }
        }
    }
}
nodes: {
    name: "otg"
    vendor: KEYSIGHT
    version: "0.0.1-9999" # Please update this with the local version from ixiatg-configmap.yaml
}
links: {
    a_node: "otg"
    a_int: "eth1"
    z_node: "dut"
    z_int: "eth1"
}
links: {
    a_node: "dut"
    a_int: "eth2"
    z_node: "otg"
    z_int: "eth2"
}
links: {
    a_node: "dut"
    a_int: "eth3"
    z_node: "otg"
    z_int: "eth3"
}
links: {
    a_node: "dut"
    a_int: "eth4"
    z_node: "otg"
    z_int: "eth4"
}
links: {
    a_node: "dut"
    a_int: "eth5"
    z_node: "otg"
    z_int: "eth5"
}
links: {
    a_node: "dut"
    a_int: "eth6"
    z_node: "otg"
    z_int: "eth6"
}
links: {
    a_node: "dut"
    a_int: "eth7"
    z_node: "otg"
    z_int: "eth7"
}
links: {
    a_node: "dut"
    a_int: "eth8"
    z_node: "otg"
    z_int: "eth8"
}
links: {
    a_node: "dut"
    a_int: "eth9"
    z_node: "otg"
    z_int: "eth9"
}
