# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "6163fd8a-2b42-4e3d-ad98-3c940aa70a4c"
plan_id: "SEC-3.1"
description: "Authentication"
testbed: TESTBED_DUT
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    banner_delimiter: "c"
  }
}
