# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "44fed7d9-4c79-4952-8b83-fbd5f7138ae9"
plan_id: "gNMI-1.4"
description: "Telemetry: Inventory"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    install_position_and_install_component_unsupported: true
    model_name_unsupported: true
  }
}
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    install_position_and_install_component_unsupported: true
    model_name_unsupported: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    backplane_facing_capacity_unsupported: true
    install_position_and_install_component_unsupported: true
    model_name_unsupported: true
    storage_component_unsupported: true
    switch_chip_id_unsupported: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    backplane_facing_capacity_unsupported: true
    install_position_and_install_component_unsupported: true
    model_name_unsupported: true
    skip_controller_card_power_admin: true
  }
}
