# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid:  "89a10b5b-76e7-4ccc-a37f-c59b9a2ca884"
plan_id:  "DP-2.2"
description:  "QoS scheduler with 1 rate 2 color policer, classifying on next-hop group"
testbed:  TESTBED_DUT_ATE_2LINKS

platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    static_protocol_name:  "STATIC"
    gribi_mac_override_static_arp_static_route:  true
    interface_enabled:  true
    default_network_instance:  "default"
    gribi_encap_header_unsupported:  true
    qos_two_rate_three_color_policer_oc_unsupported: true
    qos_scheduler_ingress_policer_unsupported: true
  }
}
