# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata


uuid:  "ffd2b1d2-382f-46e2-81ee-d68466439804"
plan_id:  "PF-1.24"
description:  "Add and remove interface bound to PBF"
testbed:  TESTBED_DUT_ATE_4LINKS
platform_exceptions:  {
  platform:  {
    vendor:  NOKIA
  }
  deviations:  {
    static_protocol_name:  "static"
    interface_enabled:  true
    explicit_interface_in_default_vrf: true
    require_routed_subinterface_0: true
  }
}
platform_exceptions:  {
  platform:  {
    vendor:  ARISTA
  }
  deviations:  {
    static_protocol_name:  "STATIC"
    interface_enabled:  true
    default_network_instance:  "default"
    interface_config_vrf_before_address: true
  }
}
platform_exceptions:  {
  platform:  {
    vendor:  CISCO
  }
  deviations:  {
    ipv4_missing_enabled: true
    interface_ref_interface_id_format: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    interface_enabled: true
    explicit_interface_in_default_vrf: true
    interface_ref_interface_id_format: true
  }
}
