// Code generated by go run tools/addrundata; DO NOT EDIT.
package complete_chassis_reboot_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "gNOI-3.1"
	rundata.TestDescription = "Complete Chassis Reboot"
	rundata.TestUUID = "5f0c7b5c-5c52-4a4d-af59-fba9edb04b6d"
}
