// Code generated by go run tools/addrundata; DO NOT EDIT.
package traceroute_packetout_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "P4RT-5.2"
	rundata.TestDescription = "Traceroute Packetout"
	rundata.TestUUID = "6c2613a5-7579-4d2b-940b-d93a128d4fd5"
}
