# proto-file: third_party/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "2beaac46-9b7b-49c4-9bde-62ad530aa5c5"
plan_id:  "PF-1.12"
description:  "MPLSoGRE IPV4 decapsulation of IPV4/IPV6 payload"
testbed: TESTBED_DUT_ATE_4LINKS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
 deviations: {
  local_proxy_unsupported: true
  qos_classification_unsupported: true
  policy_forwarding_unsupported: true
  mpls_unsupported: true
  mpls_label_classification_unsupported: true
  aggregate_atomic_update: true
  interface_enabled: true
  gue_gre_decap_unsupported: true
  static_mpls_unsupported: true
  default_network_instance: "default"
  }
}
