# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "8e46e4ea-e114-40e7-9b96-2b7e8337a709"
plan_id: "AFT-3.1"
description: "AFTs Atomic Flag Check"
testbed: TESTBED_DUT_ATE_2LINKS

platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    isis_single_topology_required: true
    link_local_instead_of_nh: true
    missing_isis_interface_afi_safi_enable: true
    skip_interface_name_check: true
    skip_setting_allow_multiple_as: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    default_network_instance: "default"
    isis_instance_enabled_required: true
    isis_mpls_unsupported: true
    skip_setting_allow_multiple_as: true
  }
}
