# proto-file: third_party/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "f43d95b6-438c-4128-801e-043e426b55cd"
plan_id: "FNT-Carrier-Transitions"
description: "Validates that the carrier-transitions counter increments correctly when the interface link state changes."
testbed: DUT_ATE_2LINKS
