# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "c1cb3545-2704-4f1a-80d3-150840df5f4a"
plan_id: "gNMI-1.14"
description: "Telemetry: Optics Thresholds"
testbed: TESTBED_DUT_ATE_2LINKS
