# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid:  "32ac61df-e182-4e2e-ab68-b517453dabbf"
plan_id:  "MPLS-1.2"
description:  "MPLS Traffic Class Marking"
testbed:  TESTBED_DUT_DUT_4LINKS

platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    interface_enabled: true
    default_network_instance: "default"
    isis_counter_manual_address_drop_from_areas_unsupported: true
    isis_counter_part_changes_unsupported: true
    isis_instance_enabled_required: true
    isis_interface_afi_unsupported: true
    isis_metric_style_telemetry_unsupported: true
    isis_timers_csnp_interval_unsupported: true
    missing_isis_interface_afi_safi_enable: true
    static_mpls_unsupported: true
    static_mpls_lsp_oc_unsupported: true
  }
}
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    sr_igp_config_unsupported: true
  }
}