# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "50213f26-ddde-441f-936a-b92414cc9dd3"
plan_id: "QoS-1.1"
description: "Ingress traffic classification Test"
testbed: TESTBED_DUT_ATE_2LINKS