# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid:  "c1352e24-e45c-4f6d-9b16-d28cc1a5093a"
plan_id:  "ACCTZ-1.1"
description:  "Record Subscribe Full"
testbed:  TESTBED_DUT