// Code generated by go run tools/addrundata; DO NOT EDIT.
package base_hierarchical_route_installation_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "TE-3.1"
	rundata.TestDescription = "Base Hierarchical Route Installation"
	rundata.TestUUID = "3d0dba19-fdf7-4911-8150-ac968b09a1ba"
}
