# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# proto-file: github.com/openconfig/featureprofiles/proto/feature.proto
# proto-message: FeatureProfile

id {
  name: "bgp_gracefulrestart"
  version: 1
}

# Peer Group graceful restart leafs.
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/graceful-restart/config/enabled"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/graceful-restart/config/restart-time"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/graceful-restart/config/stale-routes-time"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/graceful-restart/config/helper-only"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/graceful-restart/state/enabled"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/graceful-restart/state/restart-time"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/graceful-restart/state/stale-routes-time"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/graceful-restart/state/helper-only"
}

# Per neighbor graceful restart leafs.
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/graceful-restart/config/enabled"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/graceful-restart/config/restart-time"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/graceful-restart/config/stale-routes-time"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/graceful-restart/config/helper-only"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/graceful-restart/state/enabled"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/graceful-restart/state/restart-time"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/graceful-restart/state/stale-routes-time"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/graceful-restart/state/helper-only"
}

# Per neighbor telemetry paths
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/graceful-restart/state/advertised"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/graceful-restart/state/peer-restart-time"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/graceful-restart/state/received"
}

# Global telemetry paths
config_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/global/graceful-restart/config/restart-time"
}
config_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/global/graceful-restart/config/stale-routes-time"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/global/graceful-restart/state/restart-time"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/global/graceful-restart/state/stale-routes-time"
}

feature_profile_dependency {
  name: "bgp"
  version: 1
}
