# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "bc288f94-cb04-4bb0-b1d7-621cfaa7e9f4"
plan_id: "gnmi-1-6-ni-test"
description: "FNT gNMI Get/Set/Subscribe for multiple Network Instance"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    interface_enabled: true
    default_network_instance: "default"
  }
}

platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    interface_enabled: true
    explicit_interface_in_default_vrf: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    interface_enabled: true
  }
}