# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "912d6fc8-5245-419a-9ae9-7da432a46cdf"
plan_id: "gNMI-3"
description: "union_replace"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
    num_physical_channels_unsupported: true
    port_speed_unsupported: true
    union_replace_oc_and_cli_required: true
    invalid_interface_number_allowed: true
    eth_channel_ingress_parameters_unsupported: true
    missing_port_to_optical_channel_component_mapping: true
    eth_channel_assignment_cisco_numbering: true
    otn_channel_assignment_cisco_numbering: true
    otn_to_eth_assignment: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_interface_in_default_vrf: true
    aggregate_atomic_update: true
    interface_enabled: true
  }
}

platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    aggregate_atomic_update: true
    interface_enabled: true
    explicit_port_speed: true
    default_network_instance: "default"
    missing_port_to_optical_channel_component_mapping: true
    otn_to_eth_assignment: true
    terminal_device_channel_admin_state_unsupported: true
    channel_assignment_rate_class_parameters_unsupported: true
  }
}
