# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

plan_id: "RT-2.2"
description: "BGP as-path and community-set policy"
testbed: TESTBED_DUT_ATE_2LINKS
