# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "abcc6890-c3e1-4b0e-984e-749c85b54e5a"
plan_id: "gNMI-1.27"
description: "gNMI Sample Mode Test"
testbed: TESTBED_DUT
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    omit_l2_mtu: true
    missing_value_for_defaults: true
    interface_enabled: true
	default_network_instance: "default"
    isis_instance_enabled_required: true
    isis_interface_afi_unsupported: true
  }
}
