# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid:  "944d8eb1-a5dd-46ea-b398-cadd9574d695"
plan_id:  "TE-17.1"
description:  "VRF selection policy driven TE"
testbed:  TESTBED_DUT_ATE_8LINKS
platform_exceptions:  {
  platform:  {
    vendor:  CISCO
  }
  deviations:  {
    gribi_mac_override_with_static_arp: true
    interface_ref_interface_id_format: true
    pf_require_match_default_rule: true
    pf_require_sequential_order_pbr_rules: true   
    ttl_copy_unsupported:  true
    isis_single_topology_required: true
  }
}
platform_exceptions:  {
  platform:  {
    vendor:  JUNIPER
  }
  deviations:  {
    isis_level_enabled:  true
    ttl_copy_unsupported:  true
    gribi_decap_mixed_plen_unsupported: true
  }
}
platform_exceptions:  {
  platform:  {
    vendor:  NOKIA
  }
  deviations:  {
    explicit_port_speed:  true
    explicit_interface_in_default_vrf:  true
    interface_enabled:  true
  }
}
platform_exceptions:  {
  platform:  {
    vendor:  ARISTA
  }
  deviations:  {
    gnoi_subcomponent_path:  true
    interface_enabled:  true
    static_protocol_name: "STATIC"
    default_network_instance:  "default"
    gribi_mac_override_static_arp_static_route: true
    missing_isis_interface_afi_safi_enable: true
    isis_interface_afi_unsupported: true
    isis_instance_enabled_required: true
  }
}
