id {
  name: "lldp"
  version: 1
}

config_path {
  path: "/lldp/config/enabled"
}
telemetry_path {
  path: "/lldp/state/enabled"
}
config_path {
  path: "/lldp/interfaces/interface/config/enabled"
}
telemetry_path {
  path: "/lldp/interfaces/interface/state/enabled"
}
telemetry_path {
  path: "/lldp/interfaces/interface/neighbors/neighbor/state/chassis-id"
}
telemetry_path {
  path: "/lldp/interfaces/interface/neighbors/neighbor/state/chassis-id-type"
}
telemetry_path {
  path: "/lldp/interfaces/interface/neighbors/neighbor/state/port-id"
}
telemetry_path {
  path: "/lldp/interfaces/interface/neighbors/neighbor/state/port-id-type"
}
telemetry_path {
  path: "/lldp/interfaces/interface/neighbors/neighbor/state/system-name"
}
config_path {
  path: "/lldp/interfaces/interface/name"
}
telemetry_path {
  path: "/lldp/interfaces/interface/state/name"
}
telemetry_path {
  path: "/lldp/state/chassis-id"
}
telemetry_path {
  path: "/lldp/state/chassis-id-type"
}
config_path {
  path: "/lldp/config/system-name"
}
telemetry_path {
  path: "/lldp/state/system-name"
}
config_path {
    path: "/lldp/config/system-description"
}
telemetry_path {
    path: "/lldp/state/system-description"
}
config_path {
    path: "/lldp/interfaces/interface/config/name"
}
