// Code generated by go run tools/addrundata; DO NOT EDIT.
package bgp_graceful_restart_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "RT-1.4"
	rundata.TestDescription = "BGP Graceful Restart"
	rundata.TestUUID = "d2e0ad15-fd22-408b-961c-ec016de29925"
}
