// Code generated by go run tools/addrundata; DO NOT EDIT.
package route_removal_non_default_vrf_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "TE-6.2"
	rundata.TestDescription = "Route Removal In Non Default VRF"
	rundata.TestUUID = "2b09c623-da44-4511-8d7a-bec872fdc20b"
}
