package subscriptions

import (
	gpb "github.com/openconfig/gnmi/proto/gnmi"
)

// gpb.SubscriptionList_ONCE has type gpb.SubscriptionList_Mode.
type Subscription struct {
	Path           string
	StreamMode     gpb.SubscriptionMode
	SampleInterval string
}

// Alias for the subscription list mode enum (STREAM, ONCE, POLL).
// type SubscriptionListMode = gpb.SubscriptionList_Mode

func GetOrionSubscriptions() []Subscription {
	return []Subscription{
		// SAMPLE group
		{"openconfig:components/component[name=*]/integrated-circuit/backplane-facing-capacity/state/available-pct", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:components/component[name=*]/integrated-circuit/backplane-facing-capacity/state/consumed-capacity", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:components/component[name=*]/integrated-circuit/backplane-facing-capacity/state/total", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:components/component[name=*]/integrated-circuit/backplane-facing-capacity/state/total-operational-capacity", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:interfaces/interface[name=*]/state/counters/in-broadcast-pkts", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:interfaces/interface[name=*]/state/counters/in-discards", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:interfaces/interface[name=*]/state/counters/in-errors", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:interfaces/interface[name=*]/state/counters/in-fcs-errors", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:interfaces/interface[name=*]/state/counters/in-multicast-pkts", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:interfaces/interface[name=*]/state/counters/in-octets", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:interfaces/interface[name=*]/state/counters/in-unicast-pkts", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:interfaces/interface[name=*]/state/counters/out-broadcast-pkts", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:interfaces/interface[name=*]/state/counters/out-discards", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:interfaces/interface[name=*]/state/counters/out-errors", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:interfaces/interface[name=*]/state/counters/out-multicast-pkts", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:interfaces/interface[name=*]/state/counters/out-octets", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:interfaces/interface[name=*]/state/counters/out-unicast-pkts", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:qos/interfaces/interface[interface-id=*]/output/queues/queue[name=*]/state/dropped-pkts", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:qos/interfaces/interface[interface-id=*]/output/queues/queue[name=*]/state/transmit-octets", gpb.SubscriptionMode_SAMPLE, "10s"},
		{"openconfig:qos/interfaces/interface[interface-id=*]/output/queues/queue[name=*]/state/transmit-pkts", gpb.SubscriptionMode_SAMPLE, "10s"},

		// ON_CHANGE group
		{"openconfig:components/component[name=*]/integrated-circuit/state/node-id", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:components/component[name=*]/state/oper-status", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:components/component[name=*]/state/parent", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:components/component[name=*]/state/redundant-role", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:components/component[name=*]/state/switchover-ready", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:interfaces/interface[name=*]/ethernet/state/mac-address", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:interfaces/interface[name=*]/ethernet/state/port-speed", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:interfaces/interface[name=*]/state/admin-status", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:interfaces/interface[name=*]/state/forwarding-viable", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:interfaces/interface[name=*]/state/hardware-port", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:interfaces/interface[name=*]/state/id", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:interfaces/interface[name=*]/state/oper-status", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:lacp/interfaces/interface[name=*]/members/member[interface=*]/state/interface", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:network-instances/network-instance/afts", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface[interface-id=*]/levels/level/afi-safi/af/state/metric", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:system/state/software-version", gpb.SubscriptionMode_ON_CHANGE, ""},
	}
}

func GetPictorSubscriptions() []Subscription {
	return []Subscription{
		// ON_CHANGE group from pictor_subs.yaml
		{"openconfig:components/component/controller-card/state/power-admin-state", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:components/component/fabric/state/power-admin-state", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:components/component/linecard/state/power-admin-state", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:components/component/state/last-reboot-reason", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:components/component/state/last-reboot-time", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:components/component/state/last-switchover-reason/details", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:components/component/state/last-switchover-reason/trigger", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:components/component/state/oper-status", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:components/component/state/software-version", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:components/component/state/switchover-ready", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:interfaces/interface/state/type", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:interfaces/interface/state/name", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:interfaces/interface/state/admin-status", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:interfaces/interface/state/cpu", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:interfaces/interface/state/description", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:interfaces/interface/state/ifindex", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:interfaces/interface/state/last-change", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:interfaces/interface/state/management", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:interfaces/interface/state/mtu", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:interfaces/interface/state/oper-status", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/adjacencies/adjacency/state/adjacency-state", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/adjacencies/adjacency/state/area-address", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/afi-safi/af/state/metric", gpb.SubscriptionMode_ON_CHANGE, ""},
		{"openconfig:system/state/software-version", gpb.SubscriptionMode_ON_CHANGE, ""},

		// SAMPLE group from pictor_subs.yaml (30s interval)
		{"openconfig:components/component/cpu/utilization/state/avg", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/cpu/utilization/state/instant", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/fan/state/speed", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/linecard/state/slot-id", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/optical-channel/state/carrier-frequency-offset", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/optical-channel/state/chromatic-dispersion", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/optical-channel/state/frequency", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/optical-channel/state/input-power", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/optical-channel/state/laser-bias-current", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/optical-channel/state/operational-mode", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/optical-channel/state/osnr", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/optical-channel/state/output-power", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/optical-channel/state/target-output-power", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/name", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/power-supply/state/capacity", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/power-supply/state/input-current", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/power-supply/state/input-voltage", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/power-supply/state/output-current", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/power-supply/state/output-power", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/power-supply/state/output-voltage", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/description", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/empty", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/firmware-version", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/location", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/memory/available", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/memory/utilized", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/mfg-name", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/name", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/parent", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/part-no", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/redundant-role", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/removable", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/serial-no", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/software-version", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/temperature/alarm-severity", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/temperature/alarm-status", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/temperature/alarm-threshold", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/temperature/instant", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/state/type", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/transceiver/physical-channels/channel/state/input-power/instant", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/transceiver/physical-channels/channel/state/laser-bias-current/instant", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/transceiver/physical-channels/channel/state/output-power/instant", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/transceiver/physical-channels/channel/state/associated-optical-channel", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/transceiver/physical-channels/channel/state/tx-laser", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:components/component/transceiver/state/form-factor", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:interfaces/interface/aggregation/state/lag-speed", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:interfaces/interface/ethernet/state/auto-negotiate", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:interfaces/interface/ethernet/state/mac-address", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:interfaces/interface/ethernet/state/port-speed", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:interfaces/interface/state/forwarding-viable", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:interfaces/interface/state/hardware-port", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:interfaces/interface/state/physical-channel", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:interfaces/interface/state/transceiver", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:interfaces/interface/subinterfaces/subinterface/ipv4/addresses/address/state/ip", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:interfaces/interface/subinterfaces/subinterface/ipv4/addresses/address/state/prefix-length", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:interfaces/interface/subinterfaces/subinterface/ipv4/state/counters/in-pkts", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:interfaces/interface/subinterfaces/subinterface/ipv4/state/counters/out-pkts", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:interfaces/interface/subinterfaces/subinterface/ipv6/addresses/address/state/ip", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:interfaces/interface/subinterfaces/subinterface/ipv6/addresses/address/state/prefix-length", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:interfaces/interface/subinterfaces/subinterface/ipv6/state/counters/in-pkts", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:interfaces/interface/subinterfaces/subinterface/ipv6/state/counters/out-pkts", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:lacp/interfaces/interface/members/member/state/activity", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:lacp/interfaces/interface/members/member/state/aggregatable", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:lacp/interfaces/interface/members/member/state/collecting", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:lacp/interfaces/interface/members/member/state/counters/lacp-errors", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:lacp/interfaces/interface/members/member/state/counters/lacp-in-pkts", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:lacp/interfaces/interface/members/member/state/counters/lacp-out-pkts", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:lacp/interfaces/interface/members/member/state/counters/lacp-rx-errors", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:lacp/interfaces/interface/members/member/state/counters/lacp-unknown-errors", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:lacp/interfaces/interface/members/member/state/distributing", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:lacp/interfaces/interface/members/member/state/oper-key", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:lacp/interfaces/interface/members/member/state/partner-id", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:lacp/interfaces/interface/members/member/state/partner-key", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:lacp/interfaces/interface/members/member/state/port-num", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:lacp/interfaces/interface/members/member/state/synchronization", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:lacp/interfaces/interface/members/member/state/system-id", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:lacp/interfaces/interface/members/member/state/timeout", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:lldp/interfaces/interface/neighbors/neighbor/state", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/global/state/as", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/global/state/total-prefixes", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/active", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/installed", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/received", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/received-pre-policy", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/sent", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/description", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/established-transitions", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/received/NOTIFICATION", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/received/UPDATE", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/received/last-notification-error-code", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/received/last-notification-error-subcode", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/received/last-notification-time", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/sent/NOTIFICATION", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/sent/UPDATE", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/sent/last-notification-error-code", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/sent/last-notification-error-subcode", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/sent/last-notification-time", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/peer-as", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/peer-group", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/queues/input", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/queues/output", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/session-state", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/transport/state/local-address", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/global/lsp-bit/overload-bit/state/set-bit", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/global/state/net", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/global/timers/spf/state/spf-first-interval", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/circuit-counters/state/adj-number", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/csnp/state/dropped", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/csnp/state/processed", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/csnp/state/received", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/csnp/state/sent", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/iih/state/dropped", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/iih/state/processed", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/iih/state/received", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/iih/state/sent", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/lsp/state/dropped", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/lsp/state/processed", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/lsp/state/received", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/lsp/state/retransmit", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/lsp/state/sent", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/psnp/state/dropped", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/psnp/state/processed", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/psnp/state/received", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/psnp/state/sent", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/state/enabled", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/interfaces/interface/state/interface-id", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/levels/level/system-level-counters/state/spf-runs", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/isis/levels/level/system-level-counters/state/total-lsps", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:network-instances/network-instance/protocols/protocol/state/enabled", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:qos/interfaces/interface/output/queues/queue/state/dropped-pkts", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:qos/interfaces/interface/output/queues/queue/state/transmit-octets", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:qos/interfaces/interface/output/queues/queue/state/transmit-pkts", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:system/cpus/cpu/state/total/avg", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:system/logging/remote-servers/remote-server/state/host", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:system/processes/process/state/cpu-utilization", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:system/processes/process/state/name", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:system/processes/process/state/start-time", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:system/state/boot-time", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:system/state/current-datetime", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:system/state/hostname", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:terminal-device/logical-channels/channel/state", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:terminal-device/logical-channels/channel/otn/state/esnr", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:terminal-device/logical-channels/channel/otn/state/fec-uncorrectable-blocks", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:terminal-device/logical-channels/channel/otn/state/pre-fec-ber", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:terminal-device/logical-channels/channel/otn/state/q-value", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:terminal-device/logical-channels/channel/ethernet/state", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:terminal-device/logical-channels/channel/logical-channel-assignments/assignment/state", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"openconfig:terminal-device/logical-channels/channel/ingress", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"Cisco-IOS-XR-ipv6-ma-oper:ipv6-network/nodes/node/interface-data/vrfs/vrf/briefs/brief/link-local-address/address", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"Cisco-IOS-XR-platforms-ofa-oper:ofa/stats/nodes/node/Cisco-IOS-XR-ofa-npu-stats-oper:npu-numbers/npu-number/display/trap-ids/trap-id", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"Cisco-IOS-XR-platforms-ofa-oper:ofa/stats/nodes/node/Cisco-IOS-XR-ofa-npu-stats-oper:asic-statistics/asic-statistics-drop-for-npu-ids/asic-statistics-drop-for-npu-id", gpb.SubscriptionMode_SAMPLE, "30s"},
		{"Cisco-IOS-XR-platforms-ofa-oper:ofa/stats/nodes/node/Cisco-IOS-XR-8000-platforms-npu-resources-oper:hw-resources-datas/hw-resources-data/npu-hwr", gpb.SubscriptionMode_SAMPLE, "30s"},
	}
}
