// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// deviations.proto defines the protocol buffer messages required to manage the
// lifecycle of deviations used in featureprofiles.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: deviations.proto

package deviations

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	metadata_go_proto "github.com/openconfig/featureprofiles/proto/metadata_go_proto"
	ocpaths_go_proto "github.com/openconfig/featureprofiles/proto/ocpaths_go_proto"
	gnmi "github.com/openconfig/gnmi/proto/gnmi"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeviationType specifies the type of the deviation.
type DeviationType int32

const (
	// DEVIATION_TYPE_UNSPECIFIED indicates that the deviation type is not
	// specified.
	DeviationType_DEVIATION_TYPE_UNSPECIFIED DeviationType = 0
	// DEVIATION_TYPE_PATH indicates that the deviation impacts a particular path,
	// which is then omitted and replaced with the contents of the deviation.
	DeviationType_DEVIATION_TYPE_PATH DeviationType = 1
	// DEVIATION_TYPE_VALUE indicates that the deviation impacts a particular
	// path, which continues to be used but its value is changed.
	DeviationType_DEVIATION_TYPE_VALUE DeviationType = 2
	// DEVIATION_TYPE_CLI indicates that the deviation impacts a particular path
	// which is then omitted and replaced with the contents of the deviation.
	DeviationType_DEVIATION_TYPE_CLI DeviationType = 3
)

// Enum value maps for DeviationType.
var (
	DeviationType_name = map[int32]string{
		0: "DEVIATION_TYPE_UNSPECIFIED",
		1: "DEVIATION_TYPE_PATH",
		2: "DEVIATION_TYPE_VALUE",
		3: "DEVIATION_TYPE_CLI",
	}
	DeviationType_value = map[string]int32{
		"DEVIATION_TYPE_UNSPECIFIED": 0,
		"DEVIATION_TYPE_PATH":        1,
		"DEVIATION_TYPE_VALUE":       2,
		"DEVIATION_TYPE_CLI":         3,
	}
)

func (x DeviationType) Enum() *DeviationType {
	p := new(DeviationType)
	*p = x
	return p
}

func (x DeviationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviationType) Descriptor() protoreflect.EnumDescriptor {
	return file_deviations_proto_enumTypes[0].Descriptor()
}

func (DeviationType) Type() protoreflect.EnumType {
	return &file_deviations_proto_enumTypes[0]
}

func (x DeviationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviationType.Descriptor instead.
func (DeviationType) EnumDescriptor() ([]byte, []int) {
	return file_deviations_proto_rawDescGZIP(), []int{0}
}

// DeviationRegistry contains a list of deviations.
type DeviationRegistry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deviations    []*Deviation           `protobuf:"bytes,1,rep,name=deviations,proto3" json:"deviations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviationRegistry) Reset() {
	*x = DeviationRegistry{}
	mi := &file_deviations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviationRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviationRegistry) ProtoMessage() {}

func (x *DeviationRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_deviations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviationRegistry.ProtoReflect.Descriptor instead.
func (*DeviationRegistry) Descriptor() ([]byte, []int) {
	return file_deviations_proto_rawDescGZIP(), []int{0}
}

func (x *DeviationRegistry) GetDeviations() []*Deviation {
	if x != nil {
		return x.Deviations
	}
	return nil
}

// Deviation specifies a single deviation.
type Deviation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the deviation.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Type of the deviation.
	Type DeviationType `protobuf:"varint,2,opt,name=type,proto3,enum=openconfig.deviations.DeviationType" json:"type,omitempty"`
	// List of paths that are impacted by the deviation.
	ImpactedPaths *ocpaths_go_proto.OCPaths `protobuf:"bytes,3,opt,name=impacted_paths,json=impactedPaths,proto3" json:"impacted_paths,omitempty"`
	// List of platforms for which the deviation is applicable.
	Platforms     []*PlatformData `protobuf:"bytes,4,rep,name=platforms,proto3" json:"platforms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deviation) Reset() {
	*x = Deviation{}
	mi := &file_deviations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deviation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deviation) ProtoMessage() {}

func (x *Deviation) ProtoReflect() protoreflect.Message {
	mi := &file_deviations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deviation.ProtoReflect.Descriptor instead.
func (*Deviation) Descriptor() ([]byte, []int) {
	return file_deviations_proto_rawDescGZIP(), []int{1}
}

func (x *Deviation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Deviation) GetType() DeviationType {
	if x != nil {
		return x.Type
	}
	return DeviationType_DEVIATION_TYPE_UNSPECIFIED
}

func (x *Deviation) GetImpactedPaths() *ocpaths_go_proto.OCPaths {
	if x != nil {
		return x.ImpactedPaths
	}
	return nil
}

func (x *Deviation) GetPlatforms() []*PlatformData {
	if x != nil {
		return x.Platforms
	}
	return nil
}

// PlatformData comprises of the platform for which the deviation is applicable
// along with the issue_url tracking the deviation.
type PlatformData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// issue_url is the URL for the issue tracking the deviation.
	IssueUrl string `protobuf:"bytes,1,opt,name=issue_url,json=issueUrl,proto3" json:"issue_url,omitempty"`
	// platform is the platform for which the deviation is applicable.
	// Missing value of hardware_model_regex implies that the deviation is
	// hardware agnostic.
	Platform *metadata_go_proto.Metadata_Platform `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	// deviation_field specifies the additional paths, CLI commands or deviation
	// values.
	//
	// Types that are valid to be assigned to DeviationField:
	//
	//	*PlatformData_AdditionalPaths
	//	*PlatformData_Clis
	//	*PlatformData_DeviationValues_
	DeviationField isPlatformData_DeviationField `protobuf_oneof:"deviation_field"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlatformData) Reset() {
	*x = PlatformData{}
	mi := &file_deviations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformData) ProtoMessage() {}

func (x *PlatformData) ProtoReflect() protoreflect.Message {
	mi := &file_deviations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformData.ProtoReflect.Descriptor instead.
func (*PlatformData) Descriptor() ([]byte, []int) {
	return file_deviations_proto_rawDescGZIP(), []int{2}
}

func (x *PlatformData) GetIssueUrl() string {
	if x != nil {
		return x.IssueUrl
	}
	return ""
}

func (x *PlatformData) GetPlatform() *metadata_go_proto.Metadata_Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *PlatformData) GetDeviationField() isPlatformData_DeviationField {
	if x != nil {
		return x.DeviationField
	}
	return nil
}

func (x *PlatformData) GetAdditionalPaths() *ocpaths_go_proto.OCPaths {
	if x != nil {
		if x, ok := x.DeviationField.(*PlatformData_AdditionalPaths); ok {
			return x.AdditionalPaths
		}
	}
	return nil
}

func (x *PlatformData) GetClis() *PlatformData_CliCommands {
	if x != nil {
		if x, ok := x.DeviationField.(*PlatformData_Clis); ok {
			return x.Clis
		}
	}
	return nil
}

func (x *PlatformData) GetDeviationValues() *PlatformData_DeviationValues {
	if x != nil {
		if x, ok := x.DeviationField.(*PlatformData_DeviationValues_); ok {
			return x.DeviationValues
		}
	}
	return nil
}

type isPlatformData_DeviationField interface {
	isPlatformData_DeviationField()
}

type PlatformData_AdditionalPaths struct {
	// List of additional paths for the deviation.
	AdditionalPaths *ocpaths_go_proto.OCPaths `protobuf:"bytes,3,opt,name=additional_paths,json=additionalPaths,proto3,oneof"`
}

type PlatformData_Clis struct {
	// List of CLI commands for the deviation.
	Clis *PlatformData_CliCommands `protobuf:"bytes,4,opt,name=clis,proto3,oneof"`
}

type PlatformData_DeviationValues_ struct {
	// Canonical and vendor specific values for the deviation.
	DeviationValues *PlatformData_DeviationValues `protobuf:"bytes,5,opt,name=deviation_values,json=deviationValues,proto3,oneof"`
}

func (*PlatformData_AdditionalPaths) isPlatformData_DeviationField() {}

func (*PlatformData_Clis) isPlatformData_DeviationField() {}

func (*PlatformData_DeviationValues_) isPlatformData_DeviationField() {}

// DeviationValues specifies the canonical and vendor specific values for a
// deviation.
type PlatformData_DeviationValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OC standard value for the deviation.
	OcStandardValue *gnmi.TypedValue `protobuf:"bytes,1,opt,name=oc_standard_value,json=ocStandardValue,proto3" json:"oc_standard_value,omitempty"`
	// Vendor specific value for the deviation.
	VendorSpecificValue *gnmi.TypedValue `protobuf:"bytes,2,opt,name=vendor_specific_value,json=vendorSpecificValue,proto3" json:"vendor_specific_value,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlatformData_DeviationValues) Reset() {
	*x = PlatformData_DeviationValues{}
	mi := &file_deviations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformData_DeviationValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformData_DeviationValues) ProtoMessage() {}

func (x *PlatformData_DeviationValues) ProtoReflect() protoreflect.Message {
	mi := &file_deviations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformData_DeviationValues.ProtoReflect.Descriptor instead.
func (*PlatformData_DeviationValues) Descriptor() ([]byte, []int) {
	return file_deviations_proto_rawDescGZIP(), []int{2, 0}
}

func (x *PlatformData_DeviationValues) GetOcStandardValue() *gnmi.TypedValue {
	if x != nil {
		return x.OcStandardValue
	}
	return nil
}

func (x *PlatformData_DeviationValues) GetVendorSpecificValue() *gnmi.TypedValue {
	if x != nil {
		return x.VendorSpecificValue
	}
	return nil
}

// CliCommands specifies the CLI commands for a deviation.
type PlatformData_CliCommands struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of CLI commands. Each command is a regex to match cli command
	// format.
	Commands      []string `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformData_CliCommands) Reset() {
	*x = PlatformData_CliCommands{}
	mi := &file_deviations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformData_CliCommands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformData_CliCommands) ProtoMessage() {}

func (x *PlatformData_CliCommands) ProtoReflect() protoreflect.Message {
	mi := &file_deviations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformData_CliCommands.ProtoReflect.Descriptor instead.
func (*PlatformData_CliCommands) Descriptor() ([]byte, []int) {
	return file_deviations_proto_rawDescGZIP(), []int{2, 1}
}

func (x *PlatformData_CliCommands) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

var File_deviations_proto protoreflect.FileDescriptor

const file_deviations_proto_rawDesc = "" +
	"\n" +
	"\x10deviations.proto\x12\x15openconfig.deviations\x1a:github.com/openconfig/featureprofiles/proto/metadata.proto\x1a9github.com/openconfig/featureprofiles/proto/ocpaths.proto\x1a0github.com/openconfig/gnmi/proto/gnmi/gnmi.proto\"U\n" +
	"\x11DeviationRegistry\x12@\n" +
	"\n" +
	"deviations\x18\x01 \x03(\v2 .openconfig.deviations.DeviationR\n" +
	"deviations\"\xe0\x01\n" +
	"\tDeviation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\x04type\x18\x02 \x01(\x0e2$.openconfig.deviations.DeviationTypeR\x04type\x12B\n" +
	"\x0eimpacted_paths\x18\x03 \x01(\v2\x1b.openconfig.ocpaths.OCPathsR\rimpactedPaths\x12A\n" +
	"\tplatforms\x18\x04 \x03(\v2#.openconfig.deviations.PlatformDataR\tplatforms\"\xb7\x04\n" +
	"\fPlatformData\x12\x1b\n" +
	"\tissue_url\x18\x01 \x01(\tR\bissueUrl\x12A\n" +
	"\bplatform\x18\x02 \x01(\v2%.openconfig.testing.Metadata.PlatformR\bplatform\x12H\n" +
	"\x10additional_paths\x18\x03 \x01(\v2\x1b.openconfig.ocpaths.OCPathsH\x00R\x0fadditionalPaths\x12E\n" +
	"\x04clis\x18\x04 \x01(\v2/.openconfig.deviations.PlatformData.CliCommandsH\x00R\x04clis\x12`\n" +
	"\x10deviation_values\x18\x05 \x01(\v23.openconfig.deviations.PlatformData.DeviationValuesH\x00R\x0fdeviationValues\x1a\x95\x01\n" +
	"\x0fDeviationValues\x12<\n" +
	"\x11oc_standard_value\x18\x01 \x01(\v2\x10.gnmi.TypedValueR\x0focStandardValue\x12D\n" +
	"\x15vendor_specific_value\x18\x02 \x01(\v2\x10.gnmi.TypedValueR\x13vendorSpecificValue\x1a)\n" +
	"\vCliCommands\x12\x1a\n" +
	"\bcommands\x18\x01 \x03(\tR\bcommandsB\x11\n" +
	"\x0fdeviation_field*z\n" +
	"\rDeviationType\x12\x1e\n" +
	"\x1aDEVIATION_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DEVIATION_TYPE_PATH\x10\x01\x12\x18\n" +
	"\x14DEVIATION_TYPE_VALUE\x10\x02\x12\x16\n" +
	"\x12DEVIATION_TYPE_CLI\x10\x03BLZJgithub.com/openconfig/featureprofiles/proto/deviations_go_proto;deviationsb\x06proto3"

var (
	file_deviations_proto_rawDescOnce sync.Once
	file_deviations_proto_rawDescData []byte
)

func file_deviations_proto_rawDescGZIP() []byte {
	file_deviations_proto_rawDescOnce.Do(func() {
		file_deviations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deviations_proto_rawDesc), len(file_deviations_proto_rawDesc)))
	})
	return file_deviations_proto_rawDescData
}

var file_deviations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_deviations_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_deviations_proto_goTypes = []any{
	(DeviationType)(0),                          // 0: openconfig.deviations.DeviationType
	(*DeviationRegistry)(nil),                   // 1: openconfig.deviations.DeviationRegistry
	(*Deviation)(nil),                           // 2: openconfig.deviations.Deviation
	(*PlatformData)(nil),                        // 3: openconfig.deviations.PlatformData
	(*PlatformData_DeviationValues)(nil),        // 4: openconfig.deviations.PlatformData.DeviationValues
	(*PlatformData_CliCommands)(nil),            // 5: openconfig.deviations.PlatformData.CliCommands
	(*ocpaths_go_proto.OCPaths)(nil),            // 6: openconfig.ocpaths.OCPaths
	(*metadata_go_proto.Metadata_Platform)(nil), // 7: openconfig.testing.Metadata.Platform
	(*gnmi.TypedValue)(nil),                     // 8: gnmi.TypedValue
}
var file_deviations_proto_depIdxs = []int32{
	2,  // 0: openconfig.deviations.DeviationRegistry.deviations:type_name -> openconfig.deviations.Deviation
	0,  // 1: openconfig.deviations.Deviation.type:type_name -> openconfig.deviations.DeviationType
	6,  // 2: openconfig.deviations.Deviation.impacted_paths:type_name -> openconfig.ocpaths.OCPaths
	3,  // 3: openconfig.deviations.Deviation.platforms:type_name -> openconfig.deviations.PlatformData
	7,  // 4: openconfig.deviations.PlatformData.platform:type_name -> openconfig.testing.Metadata.Platform
	6,  // 5: openconfig.deviations.PlatformData.additional_paths:type_name -> openconfig.ocpaths.OCPaths
	5,  // 6: openconfig.deviations.PlatformData.clis:type_name -> openconfig.deviations.PlatformData.CliCommands
	4,  // 7: openconfig.deviations.PlatformData.deviation_values:type_name -> openconfig.deviations.PlatformData.DeviationValues
	8,  // 8: openconfig.deviations.PlatformData.DeviationValues.oc_standard_value:type_name -> gnmi.TypedValue
	8,  // 9: openconfig.deviations.PlatformData.DeviationValues.vendor_specific_value:type_name -> gnmi.TypedValue
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_deviations_proto_init() }
func file_deviations_proto_init() {
	if File_deviations_proto != nil {
		return
	}
	file_deviations_proto_msgTypes[2].OneofWrappers = []any{
		(*PlatformData_AdditionalPaths)(nil),
		(*PlatformData_Clis)(nil),
		(*PlatformData_DeviationValues_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deviations_proto_rawDesc), len(file_deviations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_deviations_proto_goTypes,
		DependencyIndexes: file_deviations_proto_depIdxs,
		EnumInfos:         file_deviations_proto_enumTypes,
		MessageInfos:      file_deviations_proto_msgTypes,
	}.Build()
	File_deviations_proto = out.File
	file_deviations_proto_goTypes = nil
	file_deviations_proto_depIdxs = nil
}
