# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "1be40a09-1f0e-4891-aa7a-12ea8e8ee02f"
plan_id: "RT-6.1"
description: "Core LLDP TLV Population"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    lldp_interface_config_override_global: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    missing_value_for_defaults: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    missing_value_for_defaults: true
  }
}
