# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "f4387453-37e8-4c2b-99c3-24b13cc51fd1"
plan_id: "RT-7.3"
description: "BGP Policy AS Path Set"
testbed: TESTBED_DUT_ATE_2LINKS
tags: [TAGS_TRANSIT, TAGS_DATACENTER_EDGE]
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    route_policy_under_afi_unsupported: true
    omit_l2_mtu: true
    missing_value_for_defaults: true
    interface_enabled: true
    default_network_instance: "default"
    skip_set_rp_match_set_options: true
    skip_setting_disable_metric_propagation: true
    bgp_conditions_match_community_set_unsupported: true
  }
}
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    community_member_regex_unsupported: true
    default_route_policy_unsupported: true
  }
}
