// Code generated by go run tools/addrundata; DO NOT EDIT.
package cli_origin_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "gNMI-1.1"
	rundata.TestDescription = "cli Origin"
	rundata.TestUUID = "a958cce5-60e2-4562-9b37-e24e0c520f99"
}
