id {
  name: "isis"
  version: 3
}

# Global

# Global NET
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/global/config/net"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/global/state/net"
}

# Global Level Capability
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/global/config/level-capability"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/global/state/level-capability"
}

# AFI-SAFI
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/global/afi-safi/af/config/afi-name"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/global/afi-safi/af/state/afi-name"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/global/afi-safi/af/config/safi-name"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/global/afi-safi/af/state/safi-name"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/global/afi-safi/af/config/enabled"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/global/afi-safi/af/state/enabled"
}

# Transport
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/global/transport/config/lsp-mtu-size"
}

telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/global/transport/state/lsp-mtu-size"
}

# Levels

# Level number
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/config/level-number"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/state/level-number"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/config/enabled"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/state/enabled"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/link-state-database/lsp/tlvs/tlv/extended-ipv4-reachability/prefixes/prefix/state/metric"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/link-state-database/lsp/tlvs/tlv/extended-ipv4-reachability/prefixes/prefix/state/s-bit"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/link-state-database/lsp/tlvs/tlv/extended-ipv4-reachability/prefixes/prefix/state/up-down"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/link-state-database/lsp/tlvs/tlv/extended-ipv4-reachability/prefixes/prefix/subtlvs/subtlv/flags/state/flags"
}

# Interfaces interface-id
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/config/interface-id"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/state/interface-id"
}

# Interfaces enabled
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/config/enabled"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/state/enabled"
}

# Interfaces circuit-type
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/config/circuit-type"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/state/circuit-type"
}

# Interfaces csnp interval
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/timers/config/csnp-interval"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/timers/state/csnp-interval"
}

# Interfaces lsp pacing interval
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/timers/config/lsp-pacing-interval"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/timers/state/lsp-pacing-interval"
}

# Interfaces afi name
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/afi-safi/af/config/afi-name"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/afi-safi/af/state/afi-name"
}

# Interfaces safi name
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/afi-safi/af/config/safi-name"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/afi-safi/af/state/safi-name"
}

# Interfaces afi-safi enabled
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/afi-safi/af/config/enabled"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/afi-safi/af/state/enabled"
}

# Interfaces level number
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/config/level-number"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/state/level-number"
}

# Interfaces level enabled
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/config/enabled"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/state/enabled"
}

# Interfaces hello timers interval
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/timers/config/hello-interval"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/timers/state/hello-interval"
}

# Interfaces hello timers multiplier
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/timers/config/hello-multiplier"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/timers/state/hello-multiplier"
}

# Interfaces afi name
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/afi-safi/af/config/afi-name"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/afi-safi/af/state/afi-name"
}

# Interfaces safi name
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/afi-safi/af/config/safi-name"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/afi-safi/af/state/safi-name"
}

# Interfaces afi-safi enabled
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/afi-safi/af/config/enabled"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/afi-safi/af/state/enabled"
}

# Interfaces afi-safi metric
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/afi-safi/af/config/metric"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/afi-safi/af/state/metric"
}

# IPv6 Reachability
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/link-state-database/lsp/tlvs/tlv/ipv6-reachability/prefixes/prefix/state/metric"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/link-state-database/lsp/tlvs/tlv/ipv6-reachability/prefixes/prefix/state/s-bit"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/link-state-database/lsp/tlvs/tlv/ipv6-reachability/prefixes/prefix/state/up-down"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/link-state-database/lsp/tlvs/tlv/ipv6-reachability/prefixes/prefix/state/x-bit"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/link-state-database/lsp/tlvs/tlv/ipv6-reachability/prefixes/prefix/subtlvs/subtlv/flags/state/flags"
}

# Interface counters
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/iih/state/retransmit"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/psnp/state/retransmit"
}

# Network instance 
config_path {
    path: "/network-instances/network-instance/protocols/protocol/config/identifier"
}
config_path {
    path: "/network-instances/network-instance/protocols/protocol/config/name"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/state/identifier"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/state/name"
}

# Global counters
config_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/global/timers/config/lsp-lifetime-interval"
}
config_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/global/timers/config/lsp-refresh-interval"
}
config_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/global/timers/spf/config/spf-first-interval"
}
config_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/global/timers/spf/config/spf-hold-interval"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/global/timers/state/lsp-lifetime-interval"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/global/timers/state/lsp-refresh-interval"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/global/timers/spf/state/spf-first-interval"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/global/timers/spf/state/spf-hold-interval"
  }
# Adjacencies
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/adjacencies/adjacency/state/adjacency-state"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/adjacencies/adjacency/state/neighbor-ipv4-address"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/adjacencies/adjacency/state/neighbor-ipv6-address"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/adjacencies/adjacency/state/system-id"
}

# AFI-SAFI
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/afi-safi/af/state/afi-name"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/afi-safi/af/state/metric"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/afi-safi/af/state/safi-name"
}

# CSNP counters
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/csnp/state/dropped"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/csnp/state/processed"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/csnp/state/received"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/csnp/state/sent"
}

# IIH counters
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/iih/state/dropped"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/iih/state/received"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/iih/state/sent"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/iih/state/processed"
}

# LSP Counters
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/lsp/state/dropped"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/lsp/state/processed"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/lsp/state/received"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/lsp/state/retransmit"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/lsp/state/sent"
}

# PSNP Counters
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/psnp/state/dropped"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/psnp/state/processed"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/psnp/state/sent"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/packet-counters/psnp/state/received"
}

# System Level Counters
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/system-level-counters/state/auth-fails"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/system-level-counters/state/auth-type-fails"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/system-level-counters/state/corrupted-lsps"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/system-level-counters/state/database-overloads"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/system-level-counters/state/id-len-mismatch"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/system-level-counters/state/lsp-errors"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/system-level-counters/state/max-area-address-mismatches"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/system-level-counters/state/own-lsp-purges"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/system-level-counters/state/seq-num-skips"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/system-level-counters/state/spf-runs"
}

feature_profile_dependency {
  name: "networkinstance"
  version: 1
}

feature_profile_dependency {
  name: "interface_singleton"
  version: 1
}
