# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "f86969ba-5ae6-437d-aca9-1a15e5b080e5"
plan_id: "gNOI-3.4"
description: "Chassis Reboot Status and Reboot Cancellation"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    gnoi_status_empty_subcomponent: true
    gnoi_subcomponent_path: true
  }
}
