// Code generated by go run tools/addrundata; DO NOT EDIT.
package chassis_reboot_status_and_cancel_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "gNOI-3.4"
	rundata.TestDescription = "Chassis Reboot Status and Reboot Cancellation"
	rundata.TestUUID = "f86969ba-5ae6-437d-aca9-1a15e5b080e5"
}
