plan_id: "forwarding_unviable_test"
description: "forwarding_unviable_test"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    gribi_mac_override_with_static_arp: true
  }
}

