// Code generated by go run tools/addrundata; DO NOT EDIT.
package base_leader_election_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "TE-4.1"
	rundata.TestDescription = "Base Leader Election"
	rundata.TestUUID = "cacbb7a0-5e13-4665-9ec0-e529980e9335"
}
