# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "0a8a23e4-ea4e-45b6-ad09-fe763d1b8581"
plan_id: "DP-1.3"
description: "QoS ECN feature config"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    state_path_unsupported: true
    drop_weight_leaves_unsupported: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    qos_queue_requires_id: true
    qos_buffer_allocation_config_required: true
  }
}
