// Code generated by go run tools/addrundata; DO NOT EDIT.
package route_ack_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "TE-3.6"
	rundata.TestDescription = "ACK in the Presence of Other Routes"
	rundata.TestUUID = "5eda1e33-0978-4ee4-9c9a-41a1129f7ae0"
}
