# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid:  "5131d5f6-892a-4965-989f-c76d7311e13f"
plan_id:  "System-Mount-Points"
description:  "System mount points state test"
testbed:  TESTBED_DUT
