# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "5131d5f6-892a-4965-989f-c76d7311e13f"
plan_id: "SYS-4.1"
description: "System Mount Points State Verification"
testbed: TESTBED_DUT
