# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "8e6a4bdd-7e4e-4c2a-90d8-55f3543f9e18"
plan_id: "DP-1.14"
description: "QoS basic test"
testbed: TESTBED_DUT_ATE_4LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    ecn_profile_required_definition: true
    explicit_interface_ref_definition: true
    qos_dropped_octets: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    interface_enabled: true
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    qos_octets: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    interface_enabled: true
  }
}
