# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "df5626eb-4199-4c68-bb62-1735ba682fa2"
plan_id: "OC-1.2"
description: "Default Address Families"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
    hardware_model: "CISCO-8808"
    hardware_model: "CISCO-8202-32FH-M"
    hardware_model: "8201"
    hardware_model: "xrd"
  }
  deviations: {
    ipv4_missing_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
    hardware_model: "7250-ixr10e"
    hardware_model: "ixr10"
  }
  deviations: {
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
    hardware_model: "DCS-7280CR3K-32D4"
    hardware_model: "DCS-7808"
    hardware_model: "DCS-7804-CH"
    hardware_model: "ceos"
  }
  deviations: {
    omit_l2_mtu: true
  }
}
