// Code generated by go run tools/addrundata; DO NOT EDIT.
package ni_address_families_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "OC-1.2"
	rundata.TestDescription = "Default Address Families"
	rundata.TestUUID = "df5626eb-4199-4c68-bb62-1735ba682fa2"
}
