name: "juniper-ncptx-dutate"
nodes: {
    name: "dut"
    vendor: JUNIPER
    model: "ncptx"
    os: "evo"
    config: {
        image: "ncptx:latest"
        config_path: "/home/evo/configdisk"
        config_file: "juniper.conf"
        file: "config.cfg"
        cert: {
            self_signed: {
                cert_name: "grpc-server-cert"
                key_name: "N/A"
                key_size: 4096
            }
        }
    }
    interfaces: {
        key: "eth5"
        value: {
          name: "et-0/0/0:0"
        }
    }
    interfaces: {
        key: "eth13"
        value: {
          name: "et-0/0/1:0"
        }
    }
    interfaces: {
        key: "eth21"
        value: {
          name: "et-0/0/2:0"
        }
    }
    interfaces: {
        key: "eth29"
        value: {
          name: "et-0/0/3:0"
        }
    }
    interfaces: {
        key: "eth37"
        value: {
          name: "et-0/0/4:0"
        }
    }
    interfaces: {
        key: "eth41"
        value: {
          name: "et-0/0/6:0"
        }
    }
    interfaces: {
        key: "eth45"
        value: {
          name: "et-0/0/8:0"
        }
    }
    interfaces: {
        key: "eth53"
        value: {
          name: "et-0/0/9:0"
        }
    }
    interfaces: {
        key: "eth61"
        value: {
          name: "et-0/0/10:0"
        }
    }
}
nodes: {
    name: "otg"
    vendor: KEYSIGHT
    version: "0.0.1-9999" # Please update this with the local version from ixiatg-configmap.yaml
}
links: {
    a_node: "otg"
    a_int: "eth1"
    z_node: "dut"
    z_int: "eth5"
}
links: {
    a_node: "dut"
    a_int: "eth13"
    z_node: "otg"
    z_int: "eth2"
}
links: {
    a_node: "dut"
    a_int: "eth21"
    z_node: "otg"
    z_int: "eth3"
}
links: {
    a_node: "dut"
    a_int: "eth29"
    z_node: "otg"
    z_int: "eth4"
}
links: {
    a_node: "dut"
    a_int: "eth37"
    z_node: "otg"
    z_int: "eth5"
}
links: {
    a_node: "dut"
    a_int: "eth41"
    z_node: "otg"
    z_int: "eth6"
}
links: {
    a_node: "dut"
    a_int: "eth45"
    z_node: "otg"
    z_int: "eth7"
}
links: {
    a_node: "dut"
    a_int: "eth53"
    z_node: "otg"
    z_int: "eth8"
}
links: {
    a_node: "dut"
    a_int: "eth61"
    z_node: "otg"
    z_int: "eth9"
}
