# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "E2B5D167-5536-475B-BA26-8939A15FFB0E"
plan_id: "gNMI-1.19"
description: "ConfigPush and ConfigPull after Control Card switchover"
testbed: TESTBED_DUT
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    default_network_instance: "default"
    gnoi_subcomponent_path: true
  }
}
