# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

id {
    name: "system_ntp"
    version: 1
}

config_path {
    path: "/system/ntp/config/enabled"
}
telemetry_path {
    path: "/system/ntp/state/enabled"
}
config_path {
    path: "/system/ntp/servers/server/config/address"
}
telemetry_path {
    path: "/system/ntp/servers/server/state/address"
}
telemetry_path {
    path: "/system/ntp/servers/server/state/port"
}
config_path {
    path: "/system/ntp/servers/server/config/source-address"
}
telemetry_path {
    path: "/system/ntp/servers/server/state/source-address"
}


# Counters
telemetry_path {
    path: "/system/ntp/servers/server/state/offset"
}
telemetry_path {
    path: "/system/ntp/servers/server/state/poll-interval"
}
telemetry_path {
    path: "/system/ntp/servers/server/state/root-delay"
}
telemetry_path {
    path: "/system/ntp/servers/server/state/root-dispersion"
}
telemetry_path {
    path: "/system/ntp/servers/server/state/stratum"
}
