# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "c78087a2-2586-4052-89d0-df4c621086ad"
plan_id: "TRANSCEIVER-8"
description: "Telemetry: 400ZR Optics module temperature streaming."
testbed: TESTBED_DUT_DUT_4LINKS
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    transceiver_thresholds_unsupported: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    transceiver_thresholds_unsupported: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    transceiver_thresholds_unsupported: true
  }
}
