# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

plan_id: "RT-7.11"
description: "BGP Policy - Import/Export Policy Action Using Multiple Criteria"
uuid: "520f6013-0188-45a3-b5be-ce13c55ce7cd"

testbed: TESTBED_DUT_ATE_2LINKS
tags: [TAGS_DATACENTER_EDGE]
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    omit_l2_mtu: true
    interface_enabled: true
    default_network_instance: "default"
    missing_value_for_defaults: true
    skip_set_rp_match_set_options: true
    bgp_community_set_refs_unsupported: true
    bgp_conditions_match_community_set_unsupported: true
    skip_prefix_set_mode: true
    bgp_community_member_is_a_string: true
    skip_bgp_send_community_type: true
  }
}
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    bgp_conditions_match_community_set_unsupported: true
    bgp_community_set_refs_unsupported: true
    community_member_regex_unsupported: true
    skip_setting_statement_for_policy: true
    default_route_policy_unsupported: true
    skip_checking_attribute_index: true
    skip_bgp_send_community_type: true
  }
}
