# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "4dd0a06c-e160-4810-b00c-4711fd2d6117"
plan_id: "TE-1.3"
description: "P4RT ACL Interaction with gRIBI Forwarding"
testbed: TESTBED_DUT_ATE_2_LINKS
