# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: binding.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='binding.proto',
  package='openconfig.testing',
  syntax='proto3',
  serialized_pb=_b('\n\rbinding.proto\x12\x12openconfig.testing\"\x8b\x01\n\x07\x42inding\x12(\n\x04\x64uts\x18\x01 \x03(\x0b\x32\x1a.openconfig.testing.Device\x12(\n\x04\x61tes\x18\x02 \x03(\x0b\x32\x1a.openconfig.testing.Device\x12,\n\x07options\x18\x03 \x01(\x0b\x32\x1b.openconfig.testing.Options\"T\n\x07\x43onfigs\x12\x0b\n\x03\x63li\x18\x01 \x03(\x0c\x12\x10\n\x08\x63li_file\x18\x02 \x03(\t\x12\x15\n\rgnmi_set_file\x18\x03 \x03(\t\x12\x13\n\x0bgribi_flush\x18\x04 \x01(\x08\"\xd8\x03\n\x06\x44\x65vice\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12,\n\x07options\x18\x03 \x01(\x0b\x32\x1b.openconfig.testing.Options\x12\'\n\x05ports\x18\x04 \x03(\x0b\x32\x18.openconfig.testing.Port\x12+\n\x06\x63onfig\x18\x05 \x01(\x0b\x32\x1b.openconfig.testing.Configs\x12(\n\x03ssh\x18\x0b \x01(\x0b\x32\x1b.openconfig.testing.Options\x12)\n\x04gnmi\x18\x0c \x01(\x0b\x32\x1b.openconfig.testing.Options\x12)\n\x04gnoi\x18\r \x01(\x0b\x32\x1b.openconfig.testing.Options\x12)\n\x04gnsi\x18\x0e \x01(\x0b\x32\x1b.openconfig.testing.Options\x12*\n\x05gribi\x18\x0f \x01(\x0b\x32\x1b.openconfig.testing.Options\x12)\n\x04p4rt\x18\x10 \x01(\x0b\x32\x1b.openconfig.testing.Options\x12.\n\tixnetwork\x18\x11 \x01(\x0b\x32\x1b.openconfig.testing.Options\"x\n\x07Options\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x10\n\x08insecure\x18\x02 \x01(\x08\x12\x13\n\x0bskip_verify\x18\x03 \x01(\x08\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\x12\x12\n\nsession_id\x18\x06 \x01(\x05\" \n\x04Port\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\tB@Z>github.com/openconfig/featureprofiles/topologies/proto/bindingb\x06proto3')
)




_BINDING = _descriptor.Descriptor(
  name='Binding',
  full_name='openconfig.testing.Binding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='duts', full_name='openconfig.testing.Binding.duts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ates', full_name='openconfig.testing.Binding.ates', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='options', full_name='openconfig.testing.Binding.options', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=177,
)


_CONFIGS = _descriptor.Descriptor(
  name='Configs',
  full_name='openconfig.testing.Configs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cli', full_name='openconfig.testing.Configs.cli', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cli_file', full_name='openconfig.testing.Configs.cli_file', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gnmi_set_file', full_name='openconfig.testing.Configs.gnmi_set_file', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gribi_flush', full_name='openconfig.testing.Configs.gribi_flush', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=263,
)


_DEVICE = _descriptor.Descriptor(
  name='Device',
  full_name='openconfig.testing.Device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='openconfig.testing.Device.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='openconfig.testing.Device.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='options', full_name='openconfig.testing.Device.options', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ports', full_name='openconfig.testing.Device.ports', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='openconfig.testing.Device.config', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ssh', full_name='openconfig.testing.Device.ssh', index=5,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gnmi', full_name='openconfig.testing.Device.gnmi', index=6,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gnoi', full_name='openconfig.testing.Device.gnoi', index=7,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gnsi', full_name='openconfig.testing.Device.gnsi', index=8,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gribi', full_name='openconfig.testing.Device.gribi', index=9,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='p4rt', full_name='openconfig.testing.Device.p4rt', index=10,
      number=16, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ixnetwork', full_name='openconfig.testing.Device.ixnetwork', index=11,
      number=17, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=738,
)


_OPTIONS = _descriptor.Descriptor(
  name='Options',
  full_name='openconfig.testing.Options',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='openconfig.testing.Options.target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='insecure', full_name='openconfig.testing.Options.insecure', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skip_verify', full_name='openconfig.testing.Options.skip_verify', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='openconfig.testing.Options.username', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='openconfig.testing.Options.password', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='openconfig.testing.Options.session_id', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=740,
  serialized_end=860,
)


_PORT = _descriptor.Descriptor(
  name='Port',
  full_name='openconfig.testing.Port',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='openconfig.testing.Port.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='openconfig.testing.Port.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=862,
  serialized_end=894,
)

_BINDING.fields_by_name['duts'].message_type = _DEVICE
_BINDING.fields_by_name['ates'].message_type = _DEVICE
_BINDING.fields_by_name['options'].message_type = _OPTIONS
_DEVICE.fields_by_name['options'].message_type = _OPTIONS
_DEVICE.fields_by_name['ports'].message_type = _PORT
_DEVICE.fields_by_name['config'].message_type = _CONFIGS
_DEVICE.fields_by_name['ssh'].message_type = _OPTIONS
_DEVICE.fields_by_name['gnmi'].message_type = _OPTIONS
_DEVICE.fields_by_name['gnoi'].message_type = _OPTIONS
_DEVICE.fields_by_name['gnsi'].message_type = _OPTIONS
_DEVICE.fields_by_name['gribi'].message_type = _OPTIONS
_DEVICE.fields_by_name['p4rt'].message_type = _OPTIONS
_DEVICE.fields_by_name['ixnetwork'].message_type = _OPTIONS
DESCRIPTOR.message_types_by_name['Binding'] = _BINDING
DESCRIPTOR.message_types_by_name['Configs'] = _CONFIGS
DESCRIPTOR.message_types_by_name['Device'] = _DEVICE
DESCRIPTOR.message_types_by_name['Options'] = _OPTIONS
DESCRIPTOR.message_types_by_name['Port'] = _PORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Binding = _reflection.GeneratedProtocolMessageType('Binding', (_message.Message,), dict(
  DESCRIPTOR = _BINDING,
  __module__ = 'binding_pb2'
  # @@protoc_insertion_point(class_scope:openconfig.testing.Binding)
  ))
_sym_db.RegisterMessage(Binding)

Configs = _reflection.GeneratedProtocolMessageType('Configs', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGS,
  __module__ = 'binding_pb2'
  # @@protoc_insertion_point(class_scope:openconfig.testing.Configs)
  ))
_sym_db.RegisterMessage(Configs)

Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), dict(
  DESCRIPTOR = _DEVICE,
  __module__ = 'binding_pb2'
  # @@protoc_insertion_point(class_scope:openconfig.testing.Device)
  ))
_sym_db.RegisterMessage(Device)

Options = _reflection.GeneratedProtocolMessageType('Options', (_message.Message,), dict(
  DESCRIPTOR = _OPTIONS,
  __module__ = 'binding_pb2'
  # @@protoc_insertion_point(class_scope:openconfig.testing.Options)
  ))
_sym_db.RegisterMessage(Options)

Port = _reflection.GeneratedProtocolMessageType('Port', (_message.Message,), dict(
  DESCRIPTOR = _PORT,
  __module__ = 'binding_pb2'
  # @@protoc_insertion_point(class_scope:openconfig.testing.Port)
  ))
_sym_db.RegisterMessage(Port)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z>github.com/openconfig/featureprofiles/topologies/proto/binding'))
# @@protoc_insertion_point(module_scope)
