// Code generated by go run tools/addrundata; DO NOT EDIT.
package supervisor_switchover_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "gNOI-3.3"
	rundata.TestDescription = "Supervisor Switchover"
	rundata.TestUUID = "7b4c9615-3892-4298-be2f-82a79dcfce9b"
}
