# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "0c825514-daf0-4d46-a3d9-2b6e5bff5529"
plan_id: "gNMI-1.11"
description: "Telemetry: Interface Packet Counters"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
    interface_counters_from_container: true
    subinterface_packet_counters_missing: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    ipv6_discarded_pkts_unsupported: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    ipv6_discarded_pkts_unsupported: true
    default_network_instance: "default"
  }
}
