// Code generated by go run tools/addrundata; DO NOT EDIT.
package telemetry_interface_packet_counters_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "gNMI-1.11"
	rundata.TestDescription = "Telemetry: Interface Packet Counters"
	rundata.TestUUID = "0c825514-daf0-4d46-a3d9-2b6e5bff5529"
}
