# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "33b8f5ee-658a-46ed-9c60-75b3fdb74726"
plan_id: "TE-11.3"
description: "Backup NHG: Actions"
testbed: TESTBED_DUT_ATE_4LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    static_protocol_name: "static"
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    omit_l2_mtu: true
    static_protocol_name: "STATIC"
    interface_config_vrf_before_address: true
    interface_enabled: true
    default_network_instance: "default"
  }
}
