# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "f28e7a1a-7ce4-4ccc-810e-1d6cc4eac21e"
plan_id: "gNMI-1.2"
description: "Benchmarking: Full Configuration Replace"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    isis_global_authentication_not_required: true
    isis_explicit_level_authentication_config: true
    missing_isis_interface_afi_safi_enable: true
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    isis_level_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    route_policy_under_afi_unsupported: true
    interface_enabled: true
    missing_isis_interface_afi_safi_enable: true
    isis_interface_afi_unsupported: true
    default_network_instance: "default"
    isis_instance_enabled_required: true      
  }
}
