# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "43591332-f2c8-4ba6-8957-f010bc0f3cd1"
plan_id: "RT-5.2"
description: "Aggregate Interfaces"
testbed: TESTBED_DUT_ATE_9LINKS_LAG
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    aggregate_atomic_update: true
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    aggregate_atomic_update: true
    interface_enabled: true
  }
}
