// Code generated by go run tools/addrundata; DO NOT EDIT.
package backup_nhg_multiple_nh_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "TE-11.2"
	rundata.TestDescription = "Backup NHG: Multiple NH"
	rundata.TestUUID = "139f3ee1-d0d0-45cf-8c92-4957c868d30a"
}
