# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "3d0dba19-fdf7-4911-8150-ac968b09a1ba"
plan_id: "TE-3.1"
description: "Base Hierarchical Route Installation"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
    gribi_mac_override_with_static_arp: true
    interface_ref_interface_id_format: true
    pf_require_match_default_rule: true
    pf_require_sequential_order_pbr_rules: true    
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    static_protocol_name: "static"
    interface_enabled: true
    skip_pbf_with_decap_encap_vrf: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    ipv6_enable_for_gribi_nh_dmac: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    omit_l2_mtu: true
    static_protocol_name: "STATIC"
    gribi_mac_override_static_arp_static_route: true
    interface_enabled: true
    default_network_instance: "default"
  }
}
