# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "2beaac46-9b7b-49c4-9bde-62ad530aa5c4"
plan_id: "RT-2.13"
description: "Weighted-ECMP for IS-IS"
testbed: TESTBED_DUT_ATE_8LINKS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    interface_enabled: true
    default_network_instance: "default"
    omit_l2_mtu: true
    isis_instance_enabled_required: true
    isis_interface_afi_unsupported: true
    missing_isis_interface_afi_safi_enable: true
    isis_require_same_l1_metric_with_l2_metric: true
    route_policy_under_afi_unsupported: true
    static_protocol_name: "STATIC"
    rib_wecmp: true
    explicit_port_speed: true
  }
}
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    interface_ref_config_unsupported:true
    rib_wecmp: true
    wecmp_auto_unsupported: true
    isis_loopback_required: true
    weighted_ecmp_fixed_packet_verification: true
  }
}
