// Code generated by go run tools/addrundata; DO NOT EDIT.
package gribigo_compliance_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "TE-15.1"
	rundata.TestDescription = "gRIBI Compliance"
	rundata.TestUUID = "d90174d4-5764-4fdb-9610-031e7f8d2cfa"
}
