# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

id {
  name: "bgp_linkbandwidth"
  version: 1
}

# AFI/SAFI - IPv4 unicast, IPv6 unicast

#add bgp link bandwidth community sa a member in a community list 
config_path {
  path: "/routing-policy/defined-sets/bgp-defined-sets/community-sets/community-set/config/community-member"
}
telemetry_path {
  path: "/routing-policy/defined-sets/bgp-defined-sets/community-sets/community-set/state/community-member"
}
##community-set-name
config_path {
  path: "/routing-policy/defined-sets/bgp-defined-sets/community-sets/community-set/config/community-set-name"
}
telemetry_path {
  path: "/routing-policy/defined-sets/bgp-defined-sets/community-sets/community-set/state/community-set-name"
}
##options:all,any,invert. default=any
config_path {
  path: "/routing-policy/defined-sets/bgp-defined-sets/community-sets/community-set/config/match-set-options"
}
telemetry_path {
  path: "/routing-policy/defined-sets/bgp-defined-sets/community-sets/community-set/state/match-set-options"
}

#Apply list containing link bandwidth community to peer group or neighbor




feature_profile_dependency {
  name: "bgp_policybase"
  version: 1
}
