# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata
uuid: "6ee614f9-efa6-4d1c-bdea-b15332feedc7"
plan_id: "TRANSCEIVER-1 (400ZR_PLUS)"
description: "Telemetry: 400ZR_PLUS Chromatic Dispersion(CD) telemetry values streaming"
testbed: TESTBED_DUT_400ZR_PLUS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    default_network_instance: "default"
    missing_port_to_optical_channel_component_mapping: true
  }
}
