# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

id {
  name: "bgp"
  version: 1
}

# Network Instance config
config_path {
    path: "/network-instances/network-instance/config/enabled"
}
telemetry_path {
    path: "/network-instances/network-instance/state/enabled"
}
config_path {
    path: "/network-instances/network-instance/config/enabled-address-families"
}
telemetry_path {
    path: "/network-instances/network-instance/state/enabled-address-families"
}
config_path {
    path: "/network-instances/network-instance/config/name"
}
telemetry_path {
    path: "/network-instances/network-instance/state/name"
}
config_path {
    path: "/network-instances/network-instance/config/type"
}
telemetry_path {
    path: "/network-instances/network-instance/state/type"
}

# BGP Instance
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/global/config/as"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/global/state/as"
}

# Router ID
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/global/config/router-id"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/global/state/router-id"
}

# Neighbor Level

# Static Peer
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/config/enabled"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/config/neighbor-address"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/enabled"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/neighbor-address"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/established-transitions"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/session-state"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/active"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/queues/input"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/queues/output"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/supported-capabilities"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/timers/state/negotiated-hold-time"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/transport/state/local-port"
}


# messages

telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/sent/UPDATE"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/received/UPDATE"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/sent/NOTIFICATION"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/received/NOTIFICATION"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/received/last-notification-error-code"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/received/last-notification-error-subcode"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/received/last-notification-time"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/sent/last-notification-error-code"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/messages/sent/last-notification-error-subcode"
}

# AFI/SAFI - IPv4 unicast, IPv6 unicast

config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/config/afi-safi-name"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/config/enabled"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/afi-safi-name"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/enabled"
}

# Neighbor Peer Group
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/config/peer-group"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/peer-group"
}

# state log
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/logging-options/config/log-neighbor-state-changes"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/logging-options/state/log-neighbor-state-changes"
}

# Password Encryption: MD5
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/config/auth-password"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/auth-password"
}

# Description
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/config/description"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/description"
}

# Passive Peer
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/transport/config/passive-mode"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/transport/state/passive-mode"
}

# TCP MSS
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/transport/config/tcp-mss"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/transport/state/tcp-mss"
}

# PMTUD
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/transport/config/mtu-discovery"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/transport/state/mtu-discovery"
}

# local-address
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/transport/config/local-address"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/transport/state/local-address"
}

# local-as
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/config/local-as"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/local-as"
}

# peer-as
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/config/peer-as"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/peer-as"
}

# peer-type
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/config/peer-type"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/peer-type"
}

# remove-private-as
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/config/remove-private-as"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/remove-private-as"
}

# send-community
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/config/send-community"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/send-community"
}

# max-prefix: IPv4 unicast, IPv6 unicast
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/ipv4-unicast/prefix-limit/config/max-prefixes"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/ipv4-unicast/prefix-limit/config/prevent-teardown"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/ipv4-unicast/prefix-limit/config/warning-threshold-pct"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/ipv4-unicast/prefix-limit/state/max-prefixes"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/ipv4-unicast/prefix-limit/state/prevent-teardown"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/ipv4-unicast/prefix-limit/state/warning-threshold-pct"
}

#Basic BGP Timers
## MRAI
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/timers/config/minimum-advertisement-interval"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/timers/config/restart-time"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/timers/state/minimum-advertisement-interval"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/timers/state/restart-time"
}

##Hold Time
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/timers/config/hold-time"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/timers/state/hold-time"
}

##Keepalive
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/timers/config/keepalive-interval"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/timers/state/keepalive-interval"
}

##Connect Retry
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/timers/config/connect-retry"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/timers/state/connect-retry"
}


# Peer Groups
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/config/peer-group-name"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/state/peer-group-name"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/config/peer-as"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/state/peer-as"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/config/local-as"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/state/local-as"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/config/description"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/state/description"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/config/peer-type"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/state/peer-type"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/config/auth-password"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/state/auth-password"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/config/remove-private-as"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/state/remove-private-as"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/config/send-community"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/state/send-community"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/transport/config/passive-mode"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/transport/state/passive-mode"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/afi-safis/afi-safi/config/afi-safi-name"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/afi-safis/afi-safi/state/afi-safi-name"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/afi-safis/afi-safi/config/enabled"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/afi-safis/afi-safi/state/enabled"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/timers/config/minimum-advertisement-interval"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/timers/state/minimum-advertisement-interval"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/timers/config/hold-time"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/timers/state/hold-time"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/timers/config/keepalive-interval"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/timers/state/keepalive-interval"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/transport/config/mtu-discovery"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/transport/state/mtu-discovery"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/transport/config/local-address"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/transport/state/local-address"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/afi-safis/afi-safi/ipv4-unicast/prefix-limit/config/max-prefixes"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/afi-safis/afi-safi/ipv4-unicast/prefix-limit/config/prevent-teardown"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/afi-safis/afi-safi/ipv4-unicast/prefix-limit/config/warning-threshold-pct"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/afi-safis/afi-safi/ipv4-unicast/prefix-limit/state/max-prefixes"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/afi-safis/afi-safi/ipv4-unicast/prefix-limit/state/prevent-teardown"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/afi-safis/afi-safi/ipv4-unicast/prefix-limit/state/warning-threshold-pct"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/timers/config/minimum-advertisement-interval"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/timers/state/minimum-advertisement-interval"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/timers/config/hold-time"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/timers/state/hold-time"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/timers/config/keepalive-interval"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/timers/state/keepalive-interval"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/timers/config/connect-retry"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/timers/state/connect-retry"
}
config_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/global/afi-safis/afi-safi/config/afi-safi-name"
}
config_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/global/afi-safis/afi-safi/config/enabled"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/global/afi-safis/afi-safi/state/afi-safi-name"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/global/afi-safis/afi-safi/state/enabled"
}

# Neighbor state
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state/last-established"
}

# Transport
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/transport/state/remote-address"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/transport/state/remote-port"
}

feature_profile_dependency {
  name: "networkinstance"
  version: 1
}
