// Code generated by go run tools/addrundata; DO NOT EDIT.
package lsp_updates_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "RT-2.2"
	rundata.TestDescription = "IS-IS LSP Updates"
	rundata.TestUUID = "24249426-4ec4-417e-8885-f147d04eebf2"
}
