# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "a477c97d-c895-4af3-9c97-9327bf86d517"
plan_id: "CNTR-1"
description: "Basic container lifecycle via `gnoi.Containerz`."
testbed: TESTBED_DUT

platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    containerz_oc_unsupported: true
  }
}

platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    containerz_plugin_rpc_unsupported: true
  }
}
