# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "a993eb24-40f8-4b86-bc6b-02c19f6a0d53"
plan_id: "RT-1.24"
description: "BGP 2-Byte and 4-Byte ASN support with policy"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    route_policy_under_afi_unsupported: true
    omit_l2_mtu: true
    interface_enabled: true
    default_network_instance: "default"
  }
}
tags: TAGS_AGGREGATION
