# proto-file: third_party/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "a34e386d-92f4-42a6-9565-068047d7a635"
plan_id: "gNOI-5.4"
description: "Chassis Reboot with Config Push Test"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    gnoi_status_empty_subcomponent: true
    gnoi_subcomponent_path: true
  }
}

