# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "7c80f692-478c-44c8-ba6e-d4d46bfebce1"
plan_id: "RT-2.10"
description: "IS-IS change LSP lifetime"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    isis_interface_level1_disable_required: true
    missing_isis_interface_afi_safi_enable: true
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    missing_value_for_defaults: true
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
    isis_interface_level1_disable_required: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    omit_l2_mtu: true
    missing_value_for_defaults: true
    interface_enabled: true
    default_network_instance: "default"
    isis_instance_enabled_required: true
    isis_lsp_lifetime_interval_requires_lsp_refresh_interval: true
  }
}
tags: TAGS_AGGREGATION
