// Code generated by go run tools/addrundata; DO NOT EDIT.
package te_1_1_static_arp_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "TE-1.1"
	rundata.TestDescription = "Static ARP"
	rundata.TestUUID = "8b86a8fd-3d9d-47a4-b607-79a3acd496ee"
}
