# proto-file: google3/third_party/openconfig/ondatra/proto/testbed.proto
# proto-message: ondatra.Testbed
duts {
  id: "dut"
  ports {
    id: "port1"
  }
  ports {
    id: "port2"
  }
  ports {
    id: "port3"
  }
  ports {
    id: "port4"
  }
}
ates {
  id: "otg"
  ports {
    id: "port1"
  }
  ports {
    id: "port2"
  }
  ports {
    id: "port3"
  }
  ports {
    id: "port4"
  }
}
