# proto-file: google3/third_party/openconfig/kne/proto/topo.proto
# proto-message: Topology

name: "2node-ceos"
nodes: {
  name: "r1"
  type: ARISTA_CEOS
  config: {
    image: "us-west1-docker.pkg.dev/gep-kne/arista/ceos:ga"
    init_image: "us-west1-docker.pkg.dev/gep-kne/kne/networkop/init-wait:ga"
    config_path: "/mnt/flash"
    config_file: "startup-config"
    file: "ops/netops/lab/ondatra/knegcebind/tests/r1-config"
    cert: {
      self_signed: {
        cert_name: "gnmiCert.pem"
        key_name: "gnmiCertKey.pem"
        key_size: 4096
      }
    }
  }
}
nodes: {
  name: "r2"
  type: ARISTA_CEOS
  config: {
    image: "us-west1-docker.pkg.dev/gep-kne/arista/ceos:ga"
    init_image: "us-west1-docker.pkg.dev/gep-kne/kne/networkop/init-wait:ga"
    config_path: "/mnt/flash"
    config_file: "startup-config"
    file: "ops/netops/lab/ondatra/knegcebind/tests/r2-config"
    cert: {
      self_signed: {
        cert_name: "gnmiCert.pem"
        key_name: "gnmiCertKey.pem"
        key_size: 4096
      }
    }
  }
}
links: {
  a_node: "r1"
  a_int: "eth1"
  z_node: "r2"
  z_int: "eth1"
}
links: {
  a_node: "r1"
  a_int: "eth2"
  z_node: "r2"
  z_int: "eth2"
}
links: {
  a_node: "r1"
  a_int: "eth3"
  z_node: "r2"
  z_int: "eth3"
}
