# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "74fd348e-8242-406b-96d5-c31667df7ac1"
plan_id: "MTU-1.3"
description: "Large IP Packet Transmission"
testbed: TESTBED_DUT_ATE_4LINKS
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    aggregate_atomic_update: true
    interface_enabled: true
    omit_l2_mtu: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    omit_l2_mtu: true
    aggregate_atomic_update: true
    interface_enabled: true
    default_network_instance: "default"
  }
}