# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "38497de1-f488-46f1-b972-15e51c3ca531"
plan_id: "TE-14.1"
description: "gRIBI Scaling"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: NOKIA
    hardware_model: "7250-ixr10e"
    hardware_model: "ixr10"
  }
  deviations: {
    no_mix_of_tagged_and_untagged_subinterfaces: true
    explicit_interface_ref_definition: true
    explicit_gribi_under_network_instance: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
    hardware_model: "PTX10008"
    hardware_model: "PTX10001-36MR"
    hardware_model: "cptx"
  }
  deviations: {
    no_mix_of_tagged_and_untagged_subinterfaces: true
    explicit_interface_ref_definition: true
  }
}
