# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "38497de1-f488-46f1-b972-15e51c3ca531"
plan_id: "TE-14.1"
description: "gRIBI Scaling"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
    interface_ref_interface_id_format: true
    override_default_nh_scale: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    no_mix_of_tagged_and_untagged_subinterfaces: true
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    no_mix_of_tagged_and_untagged_subinterfaces: true
    explicit_interface_ref_definition: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    interface_enabled: true
    default_network_instance: "default"
    omit_l2_mtu: true
  }
}
