// Code generated by go run tools/addrundata; DO NOT EDIT.
package te_14_1_gribi_scaling_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "TE-14.1"
	rundata.TestDescription = "gRIBI Scaling"
	rundata.TestUUID = "38497de1-f488-46f1-b972-15e51c3ca531"
}
