# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "cbab73d1-9cc3-4ab4-9386-132dbb68d2f6"
plan_id: "PF-1.22"
description: "GUEv1 Decapsulation and ECMP test for IPv4 and IPv6 payload"
testbed: TESTBED_DUT_ATE_8LINKS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    interface_enabled: true
    default_network_instance: "default"
    isis_instance_enabled_required: true
    multipath_unsupported_neighbor_or_afisafi: true
    static_mpls_lsp_oc_unsupported: true
    decapsulate_gue_oc_unsupported: true
    load_interval_not_supported: true
  }
}