//
// ----------------------------------------------------------------
//  Copyright (c) 2023 by cisco Systems, Inc.
//  All rights reserved.
// -----------------------------------------------------------------
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.1
// source: metadata.proto

package ycov

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Supported test phases for YANG coverage logging
type TestPhase int32

const (
	TestPhase_UT         TestPhase = 0
	TestPhase_IT         TestPhase = 1
	TestPhase_DT         TestPhase = 2
	TestPhase_CVT        TestPhase = 3
	TestPhase_BIT        TestPhase = 4
	TestPhase_MTB        TestPhase = 5
	TestPhase_SIT        TestPhase = 6
	TestPhase_ACCEPTANCE TestPhase = 7
)

// Enum value maps for TestPhase.
var (
	TestPhase_name = map[int32]string{
		0: "UT",
		1: "IT",
		2: "DT",
		3: "CVT",
		4: "BIT",
		5: "MTB",
		6: "SIT",
		7: "ACCEPTANCE",
	}
	TestPhase_value = map[string]int32{
		"UT":         0,
		"IT":         1,
		"DT":         2,
		"CVT":        3,
		"BIT":        4,
		"MTB":        5,
		"SIT":        6,
		"ACCEPTANCE": 7,
	}
)

func (x TestPhase) Enum() *TestPhase {
	p := new(TestPhase)
	*p = x
	return p
}

func (x TestPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_metadata_proto_enumTypes[0].Descriptor()
}

func (TestPhase) Type() protoreflect.EnumType {
	return &file_metadata_proto_enumTypes[0]
}

func (x TestPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestPhase.Descriptor instead.
func (TestPhase) EnumDescriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{0}
}

// Supported types of testing for Yang coverage logging
type TestType int32

const (
	TestType_MANUAL     TestType = 0
	TestType_PRECOMMIT  TestType = 1
	TestType_NIGHTLY    TestType = 2
	TestType_OCCASIONAL TestType = 3
)

// Enum value maps for TestType.
var (
	TestType_name = map[int32]string{
		0: "MANUAL",
		1: "PRECOMMIT",
		2: "NIGHTLY",
		3: "OCCASIONAL",
	}
	TestType_value = map[string]int32{
		"MANUAL":     0,
		"PRECOMMIT":  1,
		"NIGHTLY":    2,
		"OCCASIONAL": 3,
	}
)

func (x TestType) Enum() *TestType {
	p := new(TestType)
	*p = x
	return p
}

func (x TestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestType) Descriptor() protoreflect.EnumDescriptor {
	return file_metadata_proto_enumTypes[1].Descriptor()
}

func (TestType) Type() protoreflect.EnumType {
	return &file_metadata_proto_enumTypes[1]
}

func (x TestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestType.Descriptor instead.
func (TestType) EnumDescriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{1}
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Interested device id
	DutId string `protobuf:"bytes,1,opt,name=dut_id,json=dutId,proto3" json:"dut_id,omitempty"`
	// Name for the current testing being performed.
	SanityName string `protobuf:"bytes,2,opt,name=sanity_name,json=sanityName,proto3" json:"sanity_name,omitempty"`
	// Test phase the current logs on box were collected in.
	TestPhase TestPhase `protobuf:"varint,3,opt,name=test_phase,json=testPhase,proto3,enum=ycov.TestPhase" json:"test_phase,omitempty"`
	// Type of testing the current logs on box were collected in.
	TestType TestType `protobuf:"varint,4,opt,name=test_type,json=testType,proto3,enum=ycov.TestType" json:"test_type,omitempty"`
	// Flag indicating processing of log and generating report.
	Options *ProcessLogOptions `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetDutId() string {
	if x != nil {
		return x.DutId
	}
	return ""
}

func (x *Metadata) GetSanityName() string {
	if x != nil {
		return x.SanityName
	}
	return ""
}

func (x *Metadata) GetTestPhase() TestPhase {
	if x != nil {
		return x.TestPhase
	}
	return TestPhase_UT
}

func (x *Metadata) GetTestType() TestType {
	if x != nil {
		return x.TestType
	}
	return TestType_MANUAL
}

func (x *Metadata) GetOptions() *ProcessLogOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// XR based parameters to process log and generate report.
type ProcessLogOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The yang models specified are those the report is run against
	Models []string `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	// List of prefix xpaths to constrain the calculations and verbose reporting (to paths that match any 1 of the prefixes)
	PrefixPaths []string `protobuf:"bytes,2,rep,name=prefix_paths,json=prefixPaths,proto3" json:"prefix_paths,omitempty"`
	// Indicate whether to include the verbose output
	Verbose bool `protobuf:"varint,3,opt,name=verbose,proto3" json:"verbose,omitempty"`
}

func (x *ProcessLogOptions) Reset() {
	*x = ProcessLogOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metadata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessLogOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessLogOptions) ProtoMessage() {}

func (x *ProcessLogOptions) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessLogOptions.ProtoReflect.Descriptor instead.
func (*ProcessLogOptions) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessLogOptions) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ProcessLogOptions) GetPrefixPaths() []string {
	if x != nil {
		return x.PrefixPaths
	}
	return nil
}

func (x *ProcessLogOptions) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

var File_metadata_proto protoreflect.FileDescriptor

var file_metadata_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x79, 0x63, 0x6f, 0x76, 0x22, 0xd2, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x75, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x75, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61,
	0x6e, 0x69, 0x74, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x61, 0x6e, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x74,
	0x65, 0x73, 0x74, 0x5f, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x79, 0x63, 0x6f, 0x76, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x50, 0x68, 0x61, 0x73, 0x65,
	0x52, 0x09, 0x74, 0x65, 0x73, 0x74, 0x50, 0x68, 0x61, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x74,
	0x65, 0x73, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e,
	0x2e, 0x79, 0x63, 0x6f, 0x76, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08,
	0x74, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x79, 0x63, 0x6f, 0x76,
	0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x68, 0x0a, 0x11, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x50, 0x61, 0x74, 0x68, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x62, 0x6f, 0x73, 0x65, 0x2a, 0x57, 0x0a, 0x09, 0x54, 0x65, 0x73, 0x74, 0x50, 0x68, 0x61,
	0x73, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x54, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x54,
	0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x44, 0x54, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x56,
	0x54, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x49, 0x54, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03,
	0x4d, 0x54, 0x42, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x49, 0x54, 0x10, 0x06, 0x12, 0x0e,
	0x0a, 0x0a, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x07, 0x2a, 0x42,
	0x0a, 0x08, 0x54, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x41,
	0x4e, 0x55, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x52, 0x45, 0x43, 0x4f, 0x4d,
	0x4d, 0x49, 0x54, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x49, 0x47, 0x48, 0x54, 0x4c, 0x59,
	0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4f, 0x43, 0x43, 0x41, 0x53, 0x49, 0x4f, 0x4e, 0x41, 0x4c,
	0x10, 0x03, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x79, 0x63, 0x6f, 0x76, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_metadata_proto_rawDescOnce sync.Once
	file_metadata_proto_rawDescData = file_metadata_proto_rawDesc
)

func file_metadata_proto_rawDescGZIP() []byte {
	file_metadata_proto_rawDescOnce.Do(func() {
		file_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_metadata_proto_rawDescData)
	})
	return file_metadata_proto_rawDescData
}

var file_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metadata_proto_goTypes = []interface{}{
	(TestPhase)(0),            // 0: ycov.TestPhase
	(TestType)(0),             // 1: ycov.TestType
	(*Metadata)(nil),          // 2: ycov.Metadata
	(*ProcessLogOptions)(nil), // 3: ycov.ProcessLogOptions
}
var file_metadata_proto_depIdxs = []int32{
	0, // 0: ycov.Metadata.test_phase:type_name -> ycov.TestPhase
	1, // 1: ycov.Metadata.test_type:type_name -> ycov.TestType
	3, // 2: ycov.Metadata.options:type_name -> ycov.ProcessLogOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_metadata_proto_init() }
func file_metadata_proto_init() {
	if File_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metadata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessLogOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_metadata_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_proto_depIdxs,
		EnumInfos:         file_metadata_proto_enumTypes,
		MessageInfos:      file_metadata_proto_msgTypes,
	}.Build()
	File_metadata_proto = out.File
	file_metadata_proto_rawDesc = nil
	file_metadata_proto_goTypes = nil
	file_metadata_proto_depIdxs = nil
}
