// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: yang_coverage.proto

package ycov

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// YangCoverageClient is the client API for YangCoverage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type YangCoverageClient interface {
	// ClearLogs clears any existing YANG coverage test logs
	ClearLogs(ctx context.Context, in *ClearLogsRequest, opts ...grpc.CallOption) (*ClearLogsResponse, error)
	// GatherLogs gathers the current set of YANG coverage test logs
	GatherLogs(ctx context.Context, in *GatherLogsRequest, opts ...grpc.CallOption) (*GatherLogsResponse, error)
}

type yangCoverageClient struct {
	cc grpc.ClientConnInterface
}

func NewYangCoverageClient(cc grpc.ClientConnInterface) YangCoverageClient {
	return &yangCoverageClient{cc}
}

func (c *yangCoverageClient) ClearLogs(ctx context.Context, in *ClearLogsRequest, opts ...grpc.CallOption) (*ClearLogsResponse, error) {
	out := new(ClearLogsResponse)
	err := c.cc.Invoke(ctx, "/ycov.YangCoverage/ClearLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yangCoverageClient) GatherLogs(ctx context.Context, in *GatherLogsRequest, opts ...grpc.CallOption) (*GatherLogsResponse, error) {
	out := new(GatherLogsResponse)
	err := c.cc.Invoke(ctx, "/ycov.YangCoverage/GatherLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YangCoverageServer is the server API for YangCoverage service.
// All implementations must embed UnimplementedYangCoverageServer
// for forward compatibility
type YangCoverageServer interface {
	// ClearLogs clears any existing YANG coverage test logs
	ClearLogs(context.Context, *ClearLogsRequest) (*ClearLogsResponse, error)
	// GatherLogs gathers the current set of YANG coverage test logs
	GatherLogs(context.Context, *GatherLogsRequest) (*GatherLogsResponse, error)
	mustEmbedUnimplementedYangCoverageServer()
}

// UnimplementedYangCoverageServer must be embedded to have forward compatible implementations.
type UnimplementedYangCoverageServer struct {
}

func (UnimplementedYangCoverageServer) ClearLogs(context.Context, *ClearLogsRequest) (*ClearLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearLogs not implemented")
}
func (UnimplementedYangCoverageServer) GatherLogs(context.Context, *GatherLogsRequest) (*GatherLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GatherLogs not implemented")
}
func (UnimplementedYangCoverageServer) mustEmbedUnimplementedYangCoverageServer() {}

// UnsafeYangCoverageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to YangCoverageServer will
// result in compilation errors.
type UnsafeYangCoverageServer interface {
	mustEmbedUnimplementedYangCoverageServer()
}

func RegisterYangCoverageServer(s grpc.ServiceRegistrar, srv YangCoverageServer) {
	s.RegisterService(&YangCoverage_ServiceDesc, srv)
}

func _YangCoverage_ClearLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YangCoverageServer).ClearLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ycov.YangCoverage/ClearLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YangCoverageServer).ClearLogs(ctx, req.(*ClearLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _YangCoverage_GatherLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatherLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YangCoverageServer).GatherLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ycov.YangCoverage/GatherLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YangCoverageServer).GatherLogs(ctx, req.(*GatherLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// YangCoverage_ServiceDesc is the grpc.ServiceDesc for YangCoverage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var YangCoverage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ycov.YangCoverage",
	HandlerType: (*YangCoverageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClearLogs",
			Handler:    _YangCoverage_ClearLogs_Handler,
		},
		{
			MethodName: "GatherLogs",
			Handler:    _YangCoverage_GatherLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "yang_coverage.proto",
}
