# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "2c4021f7-3e24-4772-8bb5-8b2b67f2b7ce"
plan_id: "RT-5.16"
description: "LAG Member Removal (NIS) and ECMP Hashing Stability"
testbed: TESTBED_DUT_ATE_8LINKS
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_interface_in_default_vrf: true
    aggregate_atomic_update: true
    interface_enabled: true
    static_protocol_name: "static"
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    aggregate_atomic_update: true
    interface_enabled: true
    default_network_instance: "default"
    static_protocol_name: "STATIC"
    omit_l2_mtu: true
  }
}

