// Code generated by go run tools/addrundata; DO NOT EDIT.
package weighted_balancing_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "TE-3.2"
	rundata.TestDescription = "Traffic Balancing According to Weights"
	rundata.TestUUID = "a5e734a1-486c-4da7-b37a-85eeb5971c60"
}
