// Code generated by go run tools/addrundata; DO NOT EDIT.
package lldp_packetout_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "P4RT-7.2"
	rundata.TestDescription = "LLDP: PacketOut"
	rundata.TestUUID = "65aab5ff-2e76-4437-a77b-7ed10f663c5e"
}
