// Code generated by go run tools/addrundata; DO NOT EDIT.
package google_discovery_protocol_packetout_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "P4RT-3.2"
	rundata.TestDescription = "Google Discovery Protocol: PacketOut"
	rundata.TestUUID = "35e47706-04ec-44b2-a184-d1f274fb3182"
}
