platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
    pf_require_match_default_rule: true
    ttl_copy_unsupported: true
    gribi_mac_override_with_static_arp: true
    interface_ref_interface_id_format: true
  }
}
tags: TAGS_DATACENTER_EDGE
