# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "d90174d4-5764-4fdb-9610-031e7f8d2cfa"
plan_id: "TE-15.1"
description: "gRIBI Compliance"
testbed: TESTBED_DUT_ATE_4LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
    hardware_model: "CISCO-8808"
    hardware_model: "CISCO-8202-32FH-M"
    hardware_model: "8201"
    hardware_model: "xrd"
  }
  deviations: {
    ipv4_missing_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
    hardware_model: "7250-ixr10e"
    hardware_model: "ixr10"
  }
  deviations: {
    explicit_gribi_under_network_instance: true
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
    hardware_model: "DCS-7280CR3K-32D4"
    hardware_model: "DCS-7808"
    hardware_model: "DCS-7804-CH"
    hardware_model: "ceos"
  }
  deviations: {
    omit_l2_mtu: true
  }
}
