# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid:  "32cbec7e-c59a-41c1-a41b-7979d6a4430d"
plan_id:  "PF-1.27"
description:  "MPLSoGRE/MPLSoGUE MACsec and Line Rate Performance"
testbed:  TESTBED_DUT_ATE_2LINKS
