# proto-file: third_party/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

# uuid: ""
plan_id: "TR-6.2"
description: "Configuration of logging consumers - console, vty, local files"
testbed: TESTBED_DUT
