# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid:  "78f324b0-d069-45a7-ba7d-a76817783a27"
plan_id:  "DP-1.16"
description:  "Ingress traffic classification and rewrite"
testbed:  TESTBED_DUT_ATE_2LINKS
