# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "a5b892e1-192d-45ff-89b5-a84a2865fdb2"
plan_id: "DP-1.16"
description: "Ingress traffic classification and rewrite"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    interface_enabled: true
    default_network_instance: "default"
    qos_remark_oc_unsupported : true
    static_mpls_lsp_oc_unsupported: true
    skip_verify_classifier_matchedpackets: true
  }
}