# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "043dc110-04d9-4327-be04-91cd261a4d9a"
plan_id: "RT-5.11"
description: "Suppress IPv6 ND Router Advertisement [Depreciated]"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_interface_in_default_vrf: true
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
  }
}
