# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "50a59a15-f856-48a9-b270-c194120b1789"
plan_id: "TE-13.2"
description: "gRIBI route DELETE during Failover"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    no_mix_of_tagged_and_untagged_subinterfaces: true
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    no_mix_of_tagged_and_untagged_subinterfaces: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    gnoi_subcomponent_path: true
    interface_enabled: true
    default_network_instance: "default"
  }
}
