# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "43591332-f2c8-4ba6-8957-f010bc0f3cd1"
plan_id: "RT-5.2"
description: "Aggregate Interfaces"
testbed: TESTBED_DUT_ATE_9LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
    hardware_model: "CISCO-8808"
    hardware_model: "CISCO-8202-32FH-M"
    hardware_model: "8201"
    hardware_model: "xrd"
  }
  deviations: {
    ipv4_missing_enabled: true
  }
}
