// Code generated by go run tools/addrundata; DO NOT EDIT.
package rt_5_2_aggregate_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "RT-5.2"
	rundata.TestDescription = "Aggregate Interfaces"
	rundata.TestUUID = "43591332-f2c8-4ba6-8957-f010bc0f3cd1"
}
