# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "93695155-2898-47d4-9bbb-ac40611d3882"
plan_id: "TE-3.3"
description: "Hierarchical weight resolution"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    hierarchical_weight_resolution_tolerance: 1.5
    ipv4_missing_enabled: true
    interface_ref_interface_id_format: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    hierarchical_weight_resolution_tolerance: 0.4
    explicit_interface_ref_definition: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    omit_l2_mtu: true
    deprecated_vlan_id: true
    interface_enabled: true
    default_network_instance: "default"
  }
}
tags: TAGS_TRANSIT
