// Code generated by go run tools/addrundata; DO NOT EDIT.
package hierarchical_weight_resolution_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "TE-3.3"
	rundata.TestDescription = "Hierarchical weight resolution"
	rundata.TestUUID = "93695155-2898-47d4-9bbb-ac40611d3882"
}
