# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# proto-file: github.com/openconfig/featureprofiles/proto/feature.proto
# proto-message: FeatureProfile

id {
  name: "sflow"
  version: 1
}

# Global
config_path {
  path: "/sampling/sflow/config/agent-id-ipv4"
}
config_path {
  path: "/sampling/sflow/config/agent-id-ipv6"
}
config_path {
  path: "/sampling/sflow/config/enabled"
}
config_path {
  path: "/sampling/sflow/config/egress-sampling-rate"
}
config_path {
  path: "/sampling/sflow/config/ingress-sampling-rate"
}
config_path {
  path: "/sampling/sflow/config/sample-size"
}
telemetry_path {
  path: "/sampling/sflow/state/agent-id-ipv4"
}
telemetry_path {
  path: "/sampling/sflow/state/agent-id-ipv6"
}
telemetry_path {
  path: "/sampling/sflow/state/enabled"
}
telemetry_path {
  path: "/sampling/sflow/state/egress-sampling-rate"
}
telemetry_path {
  path: "/sampling/sflow/state/ingress-sampling-rate"
}
telemetry_path {
  path: "/sampling/sflow/state/sample-size"
}

# Interfaces
config_path {
  path: "/sampling/sflow/interfaces/interface/config/enabled"
}
config_path {
  path: "/sampling/sflow/interfaces/interface/config/name"
}
telemetry_path {
  path: "/sampling/sflow/interfaces/interface/state/enabled"
}
telemetry_path {
  path: "/sampling/sflow/interfaces/interface/state/name"
}

# Collectors
config_path {
  path: "/sampling/sflow/collectors/collector/config/address"
}
config_path {
  path: "/sampling/sflow/collectors/collector/config/network-instance"
}
config_path {
  path: "/sampling/sflow/collectors/collector/config/port"
}
config_path {
  path: "/sampling/sflow/collectors/collector/config/source-address"
}
telemetry_path {
  path: "/sampling/sflow/collectors/collector/state/address"
}
telemetry_path {
  path: "/sampling/sflow/collectors/collector/state/network-instance"
}
telemetry_path {
  path: "/sampling/sflow/collectors/collector/state/port"
}
telemetry_path {
  path: "/sampling/sflow/collectors/collector/state/source-address"
}
