# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid:  "31dbda6b-5034-4a95-880c-25e4ce0676c4"
plan_id:  "ACCTZ-2.1"
description:  "Record Subscribe Partial"
testbed:  TESTBED_DUT