# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "4261a986-00c4-43f2-8943-47f5e88b15ca"
plan_id: "RT-5.1"
description: "Singleton Interface"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
    hardware_model: "CISCO-8808"
    hardware_model: "CISCO-8202-32FH-M"
    hardware_model: "8201"
    hardware_model: "xrd"
  }
  deviations: {
    ip_neighbor_missing: true
    ipv4_missing_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
    hardware_model: "7250-ixr10e"
    hardware_model: "ixr10"
  }
  deviations: {
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
    hardware_model: "DCS-7280CR3K-32D4"
    hardware_model: "DCS-7808"
    hardware_model: "DCS-7804-CH"
    hardware_model: "ceos"
  }
  deviations: {
    omit_l2_mtu: true
  }
}
