# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "3a55a01a-2a2d-404e-b397-a840192d8d67"
plan_id: "RT-1.33"
description: "BGP Policy with prefix-set matching"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    interface_enabled: true
    skip_set_rp_match_set_options: true
    skip_prefix_set_mode: true
  }
}
platform_exceptions:  {
  platform:  {
    vendor:  ARISTA
  }
  deviations:  {
    omit_l2_mtu: true
    interface_enabled: true
    default_network_instance: "default"
    missing_value_for_defaults: true
    skip_set_rp_match_set_options: true
    default_import_export_policy: true

  }
}
platform_exceptions:  {
  platform:  {
    vendor:  CISCO
  }
  deviations:  {
    prepolicy_received_routes: true
  }
}
tags: TAGS_TRANSIT
tags: TAGS_DATACENTER_EDGE
