# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "dd744f00-c8a7-4604-8c46-241ff934d6e2"
plan_id: "TE-8.2"
description: "Supervisor Failure"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    gnoi_subcomponent_path: true
  }
}
