// Code generated by go run tools/addrundata; DO NOT EDIT.
package supervisor_failure_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "TE-8.2"
	rundata.TestDescription = "Supervisor Failure"
	rundata.TestUUID = "dd744f00-c8a7-4604-8c46-241ff934d6e2"
}
