# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "e98e61ec-03cd-4bff-8094-2fc69491962a"
plan_id: "gNOI-2.1"
description: "Packet-based Link Qualification"
testbed: TESTBED_DUT_DUT_4LINKS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    omit_l2_mtu: true
    interface_enabled: true
    link_qual_wait_after_delete_required: true
    skip_plq_interface_oper_status_check: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    interface_enabled: true
    explicit_port_speed: true
  }
}
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    skip_plq_interface_oper_status_check: true
    plq_reflector_stats_unsupported: true
    plq_generator_capabilities_max_mtu: 512
    plq_generator_capabilities_max_pps: 40000000
  }
}
