# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "e98e61ec-03cd-4bff-8094-2fc69491962a"
plan_id: "gNOI-2.1"
description: "Packet-based Link Qualification"
testbed: TESTBED_DUT_DUT_4LINKS
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    skip_plq_packets_count_check: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    omit_l2_mtu: true
    interface_enabled: true
    link_qual_wait_after_delete_required: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    interface_enabled: true
    explicit_port_speed: true
  }
}
