# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Feature Profile for Local Authentication
id {
  name: "security_aaa_local"
  version: 1
}

#
# system
#

# authentication-method leaf-list must include LOCAL
config_path { path: "/system/aaa/authentication/config/authentication-method" }

telemetry_path { path: "/system/aaa/authentication/state/authentication-method" }

#
# per-user
#

# configuration
#
config_path { path: "/system/aaa/authentication/users/user/config/username" }

config_path { path: "/system/aaa/authentication/users/user/config/ssh-key" }

config_path { path: "/system/aaa/authentication/users/user/config/password-hashed" }

# e.g. SYSTEM_ROLE_ADMIN
config_path { path: "/system/aaa/authentication/users/user/config/role" }

# state
#
telemetry_path { path: "/system/aaa/authentication/users/user/state/username" }

telemetry_path { path: "/system/aaa/authentication/users/user/state/ssh-key" }

telemetry_path { path: "/system/aaa/authentication/users/user/config/password-hashed" }

telemetry_path { path: "/system/aaa/authentication/users/user/state/role" }

