# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "9babfe1f-86c0-450f-a1c3-17fb9a673c1c"
plan_id: "TE-6.1"
description: "Route Removal via Flush"
testbed: TESTBED_DUT_ATE_2LINKS
