// Code generated by go run tools/addrundata; DO NOT EDIT.
package route_removal_via_flush_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "TE-6.1"
	rundata.TestDescription = "Route Removal via Flush"
	rundata.TestUUID = "9babfe1f-86c0-450f-a1c3-17fb9a673c1c"
}
