# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid:  "bf9109a0-9117-40a4-8417-aecfe36820ea"
plan_id:  "RT-8"
description:  "Singleton with breakouts"
testbed:  TESTBED_DUT_ATE_2LINKS
