# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid:  "fce08e5f-1fba-49cb-beee-f72478ffb5f3"
plan_id:  "TE-18.3"
description:  "MPLS in UDP Encapsulation Scale Test"
testbed:  TESTBED_DUT_ATE_2LINKS
platform_exceptions:  {
  platform:  {
    vendor:  ARISTA
  }
  deviations:  {
    static_protocol_name:  "STATIC"
    gribi_mac_override_static_arp_static_route:  true
    interface_enabled:  true
    default_network_instance:  "default"
    gribi_encap_header_unsupported:  true
  }
}
platform_exceptions:  {
  platform:  {
    vendor:  CISCO
  }
  deviations:  {
    static_protocol_name:  "STATIC"
    gribi_mac_override_static_arp_static_route:  true
    interface_enabled:  true
    default_network_instance:  "default"
    gribi_encap_header_unsupported:  true
  }
}
