
id {
  name: "isis_auth"
  version: 1
}

# Global

# Global Authentication
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/global/config/authentication-check"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/global/state/authentication-check"
}

# Levels

# Level csnp authentication
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/config/csnp-authentication"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/state/csnp-authentication"
}

# Level psnp authentication
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/config/psnp-authentication"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/state/psnp-authentication"
}

# Level lsp authentication
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/config/lsp-authentication"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/state/lsp-authentication"
}

# Level authentication key
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/key/config/auth-password"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/levels/level/authentication/key/state/auth-password"
}

# Interfaces authentication hello authentication
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/authentication/config/hello-authentication"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/authentication/state/hello-authentication"
}

# Interfaces authentication key authentication password
config_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/authentication/key/config/auth-password"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/authentication/key/state/auth-password"
}
