# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "20184b9e-0cb6-42ec-a280-ec157acaa832"
plan_id: "TE-11.21"
description: "Backup NHG: Multiple NH with PBF"
testbed: TESTBED_DUT_ATE_4LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    omit_l2_mtu: true
    interface_enabled: true
    default_network_instance: "default"
    interface_config_vrf_before_address: true
    backup_nhg_requires_vrf_with_decap: true
  }
}
tags: TAGS_DATACENTER_EDGE
