// Code generated by go run tools/addrundata; DO NOT EDIT.
package telemetry_basic_check_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "gNMI-1.10"
	rundata.TestDescription = "Telemetry: Basic Check"
	rundata.TestUUID = "58c13a5a-d3b3-4a2c-98a7-0404596ee8ea"
}
