// Code generated by go run tools/addrundata; DO NOT EDIT.
package system_base_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "OC-1.1"
	rundata.TestDescription = "System Configuration"
	rundata.TestUUID = "ec59d852-0828-4607-bea5-fbe2340c5414"
}
