// Code generated by go run tools/addrundata; DO NOT EDIT.
package traceroute_packetin_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "P4RT-5.1"
	rundata.TestDescription = "Traceroute: PacketIn"
	rundata.TestUUID = "5a5491b5-9900-4a05-b289-43feb1ceb814"
}
