// Code generated by go run tools/addrundata; DO NOT EDIT.
package qos_policy_config_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "DP-1.2"
	rundata.TestDescription = "QoS policy feature config"
	rundata.TestUUID = "b1da9742-66f5-460d-860b-58ab3f5c34f3"
}
