# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

id {
  name: "bgp_policybase"
  version: 1
}

#Configuration

# Defined-sets leaves

#community

##community-member
config_path {
  path: "/routing-policy/defined-sets/bgp-defined-sets/community-sets/community-set/config/community-member"
}
telemetry_path {
  path: "/routing-policy/defined-sets/bgp-defined-sets/community-sets/community-set/state/community-member"
}
##community-set-name
config_path {
  path: "/routing-policy/defined-sets/bgp-defined-sets/community-sets/community-set/config/community-set-name"
}
telemetry_path {
  path: "/routing-policy/defined-sets/bgp-defined-sets/community-sets/community-set/state/community-set-name"
}
##options:all,any,invert. default=any
config_path {
  path: "/routing-policy/defined-sets/bgp-defined-sets/community-sets/community-set/config/match-set-options"
}
telemetry_path {
  path: "/routing-policy/defined-sets/bgp-defined-sets/community-sets/community-set/state/match-set-options"
}

#as-path
##as-path-member
config_path {
  path: "/routing-policy/defined-sets/bgp-defined-sets/as-path-sets/as-path-set/config/as-path-set-member"
}
telemetry_path {
  path: "/routing-policy/defined-sets/bgp-defined-sets/as-path-sets/as-path-set/state/as-path-set-member"
}
##as-path-set-name
config_path {
  path: "/routing-policy/defined-sets/bgp-defined-sets/as-path-sets/as-path-set/config/as-path-set-name"
}
telemetry_path {
  path: "/routing-policy/defined-sets/bgp-defined-sets/as-path-sets/as-path-set/state/as-path-set-name"
}

config_path {
  path: "/routing-policy/defined-sets/prefix-sets/prefix-set/name"
}
config_path {
  path: "/routing-policy/defined-sets/prefix-sets/prefix-set/config/name"
}
telemetry_path {
  path: "/routing-policy/defined-sets/prefix-sets/prefix-set/state/name"
}
##prefix-set-mode:ipv4,ipv6,mixed
config_path {
  path: "/routing-policy/defined-sets/prefix-sets/prefix-set/config/mode"
}
telemetry_path {
  path: "/routing-policy/defined-sets/prefix-sets/prefix-set/state/mode"
}
##prefixes
config_path {
  path: "/routing-policy/defined-sets/prefix-sets/prefix-set/prefixes/prefix/ip-prefix"
}
config_path {
  path: "/routing-policy/defined-sets/prefix-sets/prefix-set/prefixes/prefix/config/ip-prefix"
}

config_path {
  path: "/routing-policy/defined-sets/prefix-sets/prefix-set/prefixes/prefix/masklength-range"
}
config_path {
  path: "/routing-policy/defined-sets/prefix-sets/prefix-set/prefixes/prefix/config/masklength-range"
}
telemetry_path {
  path: "/routing-policy/defined-sets/prefix-sets/prefix-set/prefixes/prefix/state/ip-prefix"
}
telemetry_path {
  path: "/routing-policy/defined-sets/prefix-sets/prefix-set/prefixes/prefix/state/masklength-range"
}

config_path {
  path: "/routing-policy/policy-definitions/policy-definition/name"
}
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/config/name"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/state/name"
}

config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/name"
}
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/config/name"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/state/name"
}

# Policy set/action leaves
##set-route-origin
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/config/set-route-origin"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/state/set-route-origin"
}
##set-local-pref
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/config/set-local-pref"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/state/set-local-pref"
}
##set-med
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/config/set-med"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/state/set-med"
}
##set-as-path-prepend(16|32bit)
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-as-path-prepend/config/repeat-n"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-as-path-prepend/state/repeat-n"
}
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-as-path-prepend/config/asn"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-as-path-prepend/state/asn"
}
##set-nexthop-self
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/config/set-next-hop"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/state/set-next-hop"
}
##set-community
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/config/method"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/state/method"
}
###options:add,remove,replace
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/config/options"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/state/options"
}
###method:inline
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/inline/config/communities"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/inline/state/communities"
}
###method:reference
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/reference/config/community-set-ref"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/reference/state/community-set-ref"
}

# Policy condition/match leaves

##match-next-hop
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/config/next-hop-in"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/state/next-hop-in"
}
##match-origin
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/config/origin-eq"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/state/origin-eq"
}
##match-med
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/config/med-eq"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/state/med-eq"
}
##match-local-pref
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/config/local-pref-eq"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/state/local-pref-eq"
}
##match-community-set
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/config/community-set"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/state/community-set"
}
##match-prefix-set
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/match-prefix-set/config/prefix-set"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/match-prefix-set/state/prefix-set"
}
###type:any,all,invert. default=any
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/match-prefix-set/config/match-set-options"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/match-prefix-set/state/match-set-options"
}

##match-as-path-set
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/match-as-path-set/config/as-path-set"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/match-as-path-set/state/as-path-set"
}
###type:any,all,invert. default=any
config_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/match-as-path-set/config/match-set-options"
}
telemetry_path {
  path: "/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/match-as-path-set/state/match-set-options"
}
#policy-result
config_path {
    path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/config/policy-result"
}
telemetry_path {
    path: "/routing-policy/policy-definitions/policy-definition/statements/statement/actions/state/policy-result"
}

# Per neighbor policy telemetry paths
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/afi-safi-name"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/apply-policy/state/export-policy"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/apply-policy/state/import-policy"
}


# Per  prefix-list policy telemetry paths
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/installed"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/received"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/received-pre-policy"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/state/prefixes/sent"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/afi-safis/afi-safi/apply-policy/state/export-policy"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/afi-safis/afi-safi/apply-policy/state/import-policy"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/apply-policy/config/default-import-policy"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/apply-policy/config/default-export-policy"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/apply-policy/config/default-export-policy"
}
config_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/apply-policy/config/default-import-policy"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/apply-policy/state/default-import-policy"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/apply-policy/state/default-export-policy"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/apply-policy/state/default-export-policy"
}
telemetry_path {
  path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/apply-policy/state/default-import-policy"
}

# Apply policy telemetry paths
config_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/apply-policy/config/export-policy"
}
config_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/apply-policy/config/import-policy"
}
config_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/apply-policy/config/export-policy"
}
config_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/apply-policy/config/import-policy"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/apply-policy/state/export-policy"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/apply-policy/state/import-policy"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/apply-policy/state/export-policy"
}
telemetry_path {
    path: "/network-instances/network-instance/protocols/protocol/bgp/peer-groups/peer-group/apply-policy/state/import-policy"
}
feature_profile_dependency {
  name: "bgp"
  version: 1
}



