# proto-file: github.com/openconfig/kne/proto/topo.proto
# proto-message: Topology
name: "nokia-srlinux-dutate"
nodes: {
    name: "dut"
    vendor: NOKIA
    model: "ixr10e"
    config: {
        image: "srlinux:latest"
        file: "config.cfg"
        cert: {
            self_signed: {
                cert_name: "kne-profile"
                key_name: "N/A"
                key_size: 4096
            }
        }
    }
    services: {
        key: 9339
        value: {
            name: "gnmi"
            inside: 9339
        }
    }
    services: {
        key: 9340
        value: {
            name: "gribi"
            inside: 9340
        }
    }
    services: {
        key: 22
        value: {
            name: "ssh"
            inside: 22
        }
    }
    services: {
        key: 9559
        value: {
            name: "p4rt"
            inside: 9559
        }
    }
    interfaces: {
        key: "e1-1"
        value: {
            name: "ethernet-1/1"
        }
    }
    interfaces: {
        key: "e1-2"
        value: {
            name: "ethernet-1/2"
        }
    }
    interfaces: {
        key: "e1-3"
        value: {
            name: "ethernet-1/3"
        }
    }
    interfaces: {
        key: "e1-4"
        value: {
            name: "ethernet-1/4"
        }
    }
    interfaces: {
        key: "e1-5"
        value: {
            name: "ethernet-1/5"
        }
    }
    interfaces: {
        key: "e1-6"
        value: {
            name: "ethernet-1/6"
        }
    }
    interfaces: {
        key: "e1-7"
        value: {
            name: "ethernet-1/7"
        }
    }
    interfaces: {
        key: "e1-8"
        value: {
            name: "ethernet-1/8"
        }
    }
    interfaces: {
        key: "e1-9"
        value: {
            name: "ethernet-1/9"
        }
    }
}
nodes: {
    name: "otg"
    vendor: KEYSIGHT
    version: "0.0.1-9999" # Please update this with the local version from ixiatg-configmap.yaml
}
links: {
    a_node: "otg"
    a_int: "eth1"
    z_node: "dut"
    z_int: "e1-1"
}
links: {
    a_node: "dut"
    a_int: "e1-2"
    z_node: "otg"
    z_int: "eth2"
}
links: {
    a_node: "dut"
    a_int: "e1-3"
    z_node: "otg"
    z_int: "eth3"
}
links: {
    a_node: "dut"
    a_int: "e1-4"
    z_node: "otg"
    z_int: "eth4"
}
links: {
    a_node: "dut"
    a_int: "e1-5"
    z_node: "otg"
    z_int: "eth5"
}
links: {
    a_node: "dut"
    a_int: "e1-6"
    z_node: "otg"
    z_int: "eth6"
}
links: {
    a_node: "dut"
    a_int: "e1-7"
    z_node: "otg"
    z_int: "eth7"
}
links: {
    a_node: "dut"
    a_int: "e1-8"
    z_node: "otg"
    z_int: "eth8"
}
links: {
    a_node: "dut"
    a_int: "e1-9"
    z_node: "otg"
    z_int: "eth9"
}
