// Code generated by go run tools/addrundata; DO NOT EDIT.
package telemetry_port_speed_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "gNMI-1.5"
	rundata.TestDescription = "Telemetry: Port Speed Test"
	rundata.TestUUID = "352d6fc8-5245-419a-9ae9-7da432a46cdf"
}
