// Code generated by go run tools/addrundata; DO NOT EDIT.
package base_bgp_session_parameters_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "RT-1.1"
	rundata.TestDescription = "Base BGP Session Parameters"
	rundata.TestUUID = "31ab1acc-3a50-4ce6-be63-d9e56ddc5813"
}
