// Code generated by go run tools/addrundata; DO NOT EDIT.
package traceroute_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "gNOI-5.2"
	rundata.TestDescription = "Traceroute Test"
	rundata.TestUUID = "5384dcdb-c427-4b35-94d3-d5f571960634"
}
