# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "e1888c8a-eaed-4496-88a2-9af7ffc32c49"
plan_id: "TE-14.3"
description: "gRIBI Scaling - full scale setup, target T1"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    omit_l2_mtu: true
    interface_enabled: true
    default_network_instance: "default"
  }
}

platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    no_mix_of_tagged_and_untagged_subinterfaces: true
    explicit_interface_in_default_vrf: true
    interface_enabled: true
  }
}

platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    no_mix_of_tagged_and_untagged_subinterfaces: true
    interface_ref_interface_id_format: true
  }
}
