# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid:  "f5d5c225-8900-42fd-8771-8614895ae036"
plan_id:  "TRANSCEIVER-6"
description:  "Telemetry: 400ZR Optics performance metrics (pm) streaming."
testbed:  TESTBED_DUT_400ZR
platform_exceptions:  {
  platform:  {
    vendor:  ARISTA
  }
  deviations:  {
    default_network_instance:  "default"
  }
}
