# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid:  "0af851dd-7b11-43b7-a3d0-5c988b7de124"
plan_id:  "TE-14.2"
description:  "encap and decap scale"
testbed:  TESTBED_DUT_ATE_2LINKS
platform_exceptions:  {
  platform:  {
    vendor:  CISCO
  }
  deviations:  {
    ipv4_missing_enabled:  true
    interface_ref_interface_id_format: true
    pf_require_match_default_rule: true
    pf_require_sequential_order_pbr_rules: true
    override_default_nh_scale: true
  }
}
platform_exceptions:  {
  platform:  {
    vendor:  NOKIA
  }
  deviations:  {
    no_mix_of_tagged_and_untagged_subinterfaces:  true
    explicit_gribi_under_network_instance:  true
    explicit_port_speed:  true
    explicit_interface_in_default_vrf:  true
    interface_enabled:  true
  }
}
platform_exceptions:  {
  platform:  {
    vendor:  JUNIPER
  }
  deviations:  {
    no_mix_of_tagged_and_untagged_subinterfaces:  true
    explicit_interface_ref_definition:  true
    gribi_decap_mixed_plen_unsupported:  true
  }
}
platform_exceptions:  {
  platform:  {
    vendor:  ARISTA
  }
  deviations:  {
    interface_enabled:  true
    default_network_instance:  "default"
    omit_l2_mtu: true
  }
}
