// Code generated by go run tools/addrundata; DO NOT EDIT.
package qos_output_queue_counters_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "DP-1.4"
	rundata.TestDescription = "QoS Interface Output Queue Counters"
	rundata.TestUUID = "279bd41d-dbe7-4b6c-8ec1-08fb12b7f7b0"
}
