# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "8e6a4bdd-7e4e-4c2a-90d8-55f3543f9e67"
plan_id: "DP-1.10"
description: "Mixed strict priority and WRR traffic test"
testbed: TESTBED_DUT_ATE_4LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    ipv4_missing_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    explicit_interface_ref_definition: true
    qos_dropped_octets: true
    scheduler_input_weight_limit: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    dequeue_delete_not_counted_as_drops: true
    qos_octets: true
    interface_enabled: true
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    qos_queue_requires_id: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    dequeue_delete_not_counted_as_drops: true
    interface_enabled: true
  }
}
