# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "4330effe-a20c-42fb-8372-80fb0901a325"
plan_id: "RT-7.2"
description: "BGP Policy Community Set"
testbed: TESTBED_DUT_ATE_2LINKS
tags: [TAGS_TRANSIT, TAGS_DATACENTER_EDGE]
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    route_policy_under_afi_unsupported: true
    omit_l2_mtu: true
    missing_value_for_defaults: true
    interface_enabled: true
    default_network_instance: "default"
    skip_set_rp_match_set_options: true
    skip_setting_disable_metric_propagation: true
    bgp_conditions_match_community_set_unsupported: true
  }
}
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    bgp_conditions_match_community_set_unsupported: true
    community_member_regex_unsupported: true
  }
}
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_interface_in_default_vrf:  true
    interface_enabled: true
    bgp_conditions_match_community_set_unsupported: true
  }
}

