name: "arista-ceos-dutdut"
nodes: {
    name: "dut1"
    vendor: ARISTA
    model: "ceos"
    os: "eos"
    config: {
        image: "ceos:latest"
        file: "arista_ceos.config"
        config_path: "/mnt/flash"
        config_file: "startup-config"
        cert: {
            self_signed: {
                cert_name: "gnmiCert.pem"
                key_name: "gnmiCertKey.pem"
                key_size: 4096
            }
        }
    }
    services: {
        key: 22
        value: {
            name: "ssh"
            inside: 22
        }
    }
    services: {
        key: 6030
        value: {
            name: "gnmi"
            inside: 6030
        }
    }
    services: {
        key: 9340
        value: {
            name: "gribi"
            inside: 9340
        }
    }
}
nodes: {
    name: "dut2"
    vendor: ARISTA
    model: "ceos"
    os: "eos"
    config: {
        image: "ceos:latest"
        file: "arista_ceos.config"
        config_path: "/mnt/flash"
        config_file: "startup-config"
        cert: {
            self_signed: {
                cert_name: "gnmiCert.pem"
                key_name: "gnmiCertKey.pem"
                key_size: 4096
            }
        }
    }
    services: {
        key: 22
        value: {
            name: "ssh"
            inside: 22
        }
    }
    services: {
        key: 6030
        value: {
            name: "gnmi"
            inside: 6030
        }
    }
    services: {
        key: 6040
        value: {
            name: "gribi"
            inside: 6040
        }
    }
}
links: {
  a_node: "dut1"
  a_int: "eth1"
  z_node: "dut2"
  z_int: "eth1"
}
