name: "arista-ceos-dutdut"
nodes: {
  name: "dut1"
  vendor: ARISTA
  model: "ceos"
  os: "eos"
  config: {
    config_path: "/mnt/flash"
    config_file: "startup-config"
    file: "arista_ceos.config"
    cert: {
      self_signed: {
        cert_name: "gnmiCert.pem"
        key_name: "gnmiCertKey.pem"
        key_size: 4096
      }
    }
  }
  services: {
    key: 22
    value: {
      name: "ssh"
      inside: 22
      outside: 22
    }
  }
  services: {
    key: 6030
    value: {
      name: "gnmi"
      inside: 6030
      outside: 6030
    }
  }
  services: {
    key: 6040
    value: {
      name: "gribi"
      inside: 6040
      outside: 6040
    }
  }
}
nodes: {
  name: "dut2"
  vendor: ARISTA
  model: "ceos"
  os: "eos"
  config: {
    config_path: "/mnt/flash"
    config_file: "startup-config"
    file: "arista_ceos.config"
    cert: {
      self_signed: {
        cert_name: "gnmiCert.pem"
        key_name: "gnmiCertKey.pem"
        key_size: 4096
      }
    }
  }
  services: {
    key: 22
    value: {
      name: "ssh"
      inside: 22
      outside: 22
    }
  }
  services: {
    key: 6030
    value: {
      name: "gnmi"
      inside: 6030
      outside: 6030
    }
  }
  services: {
    key: 6040
    value: {
      name: "gribi"
      inside: 6040
      outside: 6040
    }
  }
}
links: {
  a_node: "dut1"
  a_int: "eth1"
  z_node: "dut2"
  z_int: "eth1"
}
links: {
  a_node: "dut1"
  a_int: "eth2"
  z_node: "dut2"
  z_int: "eth2"
}
links: {
  a_node: "dut1"
  a_int: "eth3"
  z_node: "dut2"
  z_int: "eth3"
}
links: {
  a_node: "dut1"
  a_int: "eth4"
  z_node: "dut2"
  z_int: "eth4"
}
