name: "arista-ixia-lag"
nodes: {
    name: "otg"
    vendor: KEYSIGHT
    version: "0.0.1-3423"
    services: {
        key: 443
        value: {
            name: "https"
            inside: 443
        }
    }
    services: {
        key: 40051
        value: {
            name: "grpc"
            inside: 40051
        }
    }
    services: {
        key: 50051
        value: {
            name: "gnmi"
            inside: 50051
        }
    }
    interfaces: {
        key: "eth2"
        value: {
            group: "lag"
        }
    }
    interfaces: {
        key: "eth3"
        value: {
            group: "lag"
        }
    }
    interfaces: {
        key: "eth4"
        value: {
            group: "lag"
        }
    }
    interfaces: {
        key: "eth5"
        value: {
            group: "lag"
        }
    }
    interfaces: {
        key: "eth6"
        value: {
            group: "lag"
        }
    }
    interfaces: {
        key: "eth7"
        value: {
            group: "lag"
        }
    }
    interfaces: {
        key: "eth8"
        value: {
            group: "lag"
        }
    }
    interfaces: {
        key: "eth9"
        value: {
            group: "lag"
        }
    }
}
nodes: {
    name: "arista"
    vendor: ARISTA
    model: "ceos"
    os: "eos"
    config: {
        cert: {
            self_signed: {
                cert_name: "gnmiCert.pem",
                key_name: "gnmiCertKey.pem",
                key_size: 4096,
            }
        }
        config_path: "/mnt/flash"
        config_file: "startup-config"
        file: "arista_ceos.config"
        image: "ceos:latest"
    }
    services:{
        key: 22
        value: {
            name: "ssh"
            inside: 22
        }
    }
    services:{
        key: 6030
        value: {
            name: "gnmi"
            inside: 6030
        }
    }
    services:{
        key: 6040
        value: {
            name: "gribi"
            inside: 6040
        }
    }
}
links: {
    a_node: "otg"
    a_int: "eth1"
    z_node: "arista"
    z_int: "eth1"
}
links: {
    a_node: "arista"
    a_int: "eth2"
    z_node: "otg"
    z_int: "eth2"
}
links: {
    a_node: "arista"
    a_int: "eth3"
    z_node: "otg"
    z_int: "eth3"
}
links: {
    a_node: "arista"
    a_int: "eth4"
    z_node: "otg"
    z_int: "eth4"
}
links: {
    a_node: "arista"
    a_int: "eth5"
    z_node: "otg"
    z_int: "eth5"
}
links: {
    a_node: "arista"
    a_int: "eth6"
    z_node: "otg"
    z_int: "eth6"
}
links: {
    a_node: "arista"
    a_int: "eth7"
    z_node: "otg"
    z_int: "eth7"
}
links: {
    a_node: "arista"
    a_int: "eth8"
    z_node: "otg"
    z_int: "eth8"
}
links: {
    a_node: "arista"
    a_int: "eth9"
    z_node: "otg"
    z_int: "eth9"
}
