name: "ixia-c"
nodes: {
    name: "ate"
    vendor: KEYSIGHT
    version: "0.0.1-9999"
    services: {
        key: 40051
        value: {
            name: "grpc"
            inside: 40051
        }
    }
    services: {
        key: 50051
        value: {
            name: "gnmi"
            inside: 50051
        }
    }
}
nodes: {
    name: "dut"
    vendor: ARISTA
    model: "ceos"
    os: "eos"
    config: {
        image: "ceos:latest"
        init_image: "us-west1-docker.pkg.dev/gep-kne/kne/networkop/init-wait:ga"
        config_path: "/mnt/flash"
        config_file: "startup-config"
        file: "arista_ceos.config"
        cert: {
            self_signed: {
                cert_name: "gnmiCert.pem",
                key_name: "gnmiCertKey.pem",
                key_size: 4096,
            }
        }
    }
  services: {
    key: 22
    value: {
      name: "ssh"
      inside: 22
      outside: 22
    }
  }
  services: {
    key: 6030
    value: {
      name: "gnmi"
      inside: 6030
      outside: 6030
    }
  }
  services: {
    key: 6040
    value: {
      name: "gribi"
      inside: 6040
      outside: 6040
    }
  }
}
links: {
    a_node: "ate"
    a_int: "eth1"
    z_node: "dut"
    z_int: "eth1"
}
links: {
    a_node: "dut"
    a_int: "eth2"
    z_node: "ate"
    z_int: "eth2"
}
