name: "arista-ceos"
nodes: {
    name: "dut"
    vendor: ARISTA
    model: "ceos"
    os: "eos"
    config: {
        image: "ceos:latest"
        file: "arista_ceos.config"
        config_path: "/mnt/flash"
        config_file: "startup-config"
        cert: {
            self_signed: {
                cert_name: "gnmiCert.pem",
                key_name: "gnmiCertKey.pem",
                key_size: 4096,
            }
        }
    }
    services: {
        key: 22
        value: {
            name: "ssh"
            inside: 22
        }
    }
    services: {
        key: 6030
        value: {
            name: "gnmi"
            inside: 6030
        }
    }
    services: {
        key: 9340
        value: {
            name: "gribi"
            inside: 9340
        }
    }
}
nodes: {
    name: "otg"
    vendor: KEYSIGHT
    version: "0.0.1-9999" # Please update this with the local version from ixiatg-configmap.yaml
    services: {
        key: 8443
        value: {
            name: "https"
            inside: 8443
        }
    }
    services: {
        key: 40051
        value: {
            name: "grpc"
            inside: 40051
        }
    }
    services: {
        key: 50051
        value: {
            name: "gnmi"
            inside: 50051
        }
    }
}
links: {
    a_node: "otg"
    a_int: "eth1"
    z_node: "dut"
    z_int: "eth1"
}
links: {
    a_node: "dut"
    a_int: "eth2"
    z_node: "otg"
    z_int: "eth2"
}
