name: "cisco-xrd-dutdut"
nodes: {
    name: "dut1"
    vendor: CISCO
    model: "xrd"
    os: "ios-xr"
    config: {
        image: "xrd:latest"
        file: "cisco.config"
    }
    services: {
        key: 22
        value: {
            name: "ssh"
            inside: 22
        }
    }
    services: {
        key: 9339
        value: {
            name: "gnmi"
            inside: 57400
        }
    }
    services: {
        key: 9340
        value: {
            name: "gribi"
            inside: 57400
        }
    }
    services: {
        key: 9337
        value: {
            name: "gnoi"
            inside: 57400
        }
    }
    services: {
        key: 9559
        value: {
            name: "p4rt"
            inside: 57400
        }
    }
    interfaces: {
        key: "eth1"
        value: {
            name: "GigabitEthernet0/0/0/0"
        }
    }
}
nodes: {
    name: "dut2"
    vendor: CISCO
    model: "xrd"
    os: "ios-xr"
    config: {
        image: "xrd:latest"
        file: "cisco.config"
    }
    services: {
        key: 22
        value: {
            name: "ssh"
            inside: 22
        }
    }
    services: {
        key: 9339
        value: {
            name: "gnmi"
            inside: 57400
        }
    }
    services: {
        key: 9340
        value: {
            name: "gribi"
            inside: 57400
        }
    }
    services: {
        key: 9337
        value: {
            name: "gnoi"
            inside: 57400
        }
    }
    services: {
        key: 9559
        value: {
            name: "p4rt"
            inside: 57400
        }
    }
    interfaces: {
        key: "eth1"
        value: {
            name: "GigabitEthernet0/0/0/0"
        }
    }
}
links: {
    a_node: "dut1"
    a_int: "eth1"
    z_node: "dut2"
    z_int: "eth1"
}
