# proto-file: google3/third_party/openconfig/kne/proto/topo.proto
# proto-message: Topology

# This topology models a traffic source container, a DUT, and a traffic sink
# container that can be used to run traffic generation experiments that cannot
# be supported by ixiai-c.
#
#    -----                 -----                -----
#   | src | eth1 --- eth1 | dut | eth1 -- eth1 | dst |
#    -----                 -----                -----
#
# The 'src' host runs 'mpls_src:latest" and the 'dst' host runs
# 'mpls_dst:latest'.

name: "1dut-srcsink"
nodes: {
  name: "src"
  type: HOST
  config: {
    image: "mpls_src:latest"
    command: "/app/sendmpls"
    args: "-alsologtostderr"
    args: "-v=2"
    args: "-interface=eth1"
    args: "-dst_mac=00:02:02:02:02:02"
    args: "-labels=42,43,44"
  }
  services:{
    key: 22
    value: {
        name: "ssh"
        inside: 22
    }
  }
}
nodes: {
  name: "dst"
  type: HOST
  config: {
    image: "mpls_dst:latest"
    command: "/app/recvmpls"
    args: "-alsologtostderr"
    args: "-v=2"
    args: "-interface=eth1"
  }
  services:{
    key: 22
    value: {
        name: "ssh"
        inside: 22
    }
  }
}

nodes: {
  name: "dut"
  type: ARISTA_CEOS
  config: {
    image: "ceos:latest"
    init_image: "us-west1-docker.pkg.dev/gep-kne/kne/networkop/init-wait:ga"
    config_path: "/mnt/flash"
    config_file: "startup-config"
    file: "mplsdut.config"
    cert: {
      self_signed: {
        cert_name: "gnmiCert.pem"
        key_name: "gnmiCertKey.pem"
        key_size: 4096
      }
    }
  }
}

links: {
  a_node: "src"
  a_int: "eth1"
  z_node: "dut"
  z_int: "eth1"
}
links: {
  a_node: "dut"
  a_int: "eth2"
  z_node: "dst"
  z_int: "eth1"
}
