name: "nokia-srl"
nodes: {
    name: "dut"
    vendor: NOKIA
    config: {
        file: "nokia_srl.json"
        image: "ghcr.io/nokia/srlinux:latest"
        cert: {
            self_signed: {
                cert_name: "kne-profile"
                key_name: "N/A"
                key_size: 4096
            }
        }
    }
    services:{
        key: 22
        value: {
            name: "ssh"
            inside: 22
            outside: 22
        }
    }
    services:{
        key: 57400
        value: {
            name: "gnmi"
            inside: 57400
            outside: 57400
        }
    }
    services:{
      key: 57401
      value: {
        name: "gribi"
        inside: 57401
        outside: 57401
      }
    }
}
