name: "nokia-srl"
nodes: {
    name: "dut"
    vendor: NOKIA
    model: "ixr10"
    config: {
        file: "nokia_srl.json"
        image: "ghcr.io/nokia/srlinux:latest"
        cert: {
            self_signed: {
                cert_name: "kne-profile"
                key_name: "N/A"
                key_size: 4096
            }
        }
    }
    services:{
        key: 22
        value: {
            name: "ssh"
            inside: 22
        }
    }
    services:{
        key: 9337
        value: {
            name: "gnoi"
            inside: 57400
        }
    }
    services:{
        key: 9339
        value: {
            name: "gnmi"
            inside: 57400
        }
    }
    services:{
        key: 9340
        value: {
            name: "gribi"
            inside: 57401
        }
    }
    services:{
        key: 9559
        value: {
            name: "p4rt"
            inside: 9559
        }
    }
}
