name: "nokia-srl"
nodes: {
    name: "dut"
    type: NOKIA_SRL
    config: {
        file: "nokia_srl.json"
        cert: {
            self_signed: {
                cert_name: "kne-profile",
                key_name: "N/A",
                key_size: 4096,
            }
        }
    }
    services:{
        key: 22
        value: {
            name: "ssh"
            inside: 22
        }
    }
    services:{
        key: 57400
        value: {
            name: "gnmi"
            inside: 57400
        }
    }
}
