# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "9167593f-9a06-4e8c-8bf7-96b5e30bd996"
plan_id: "TE-3.7"
description: "Base Hierarchical NHG Update"
testbed: TESTBED_DUT_ATE_4LINKS
