tests_dir = "exec/tests/"
gh_logs_dir = "logs"
gh_data_dir = "data"
gh_reports_dir = "reports"
base_logs_dir = "/auto/firex-logs-ott/gob4/"
base_tracker_url = "https://firex-north.cisco.com/test_tracker/#/"
base_logs_url = "https://firex-north.cisco.com/auto/firex-logs-ott/gob4/"