# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid:  "a8344612-0db0-42a1-96cf-38846a7f1603"
plan_id:  "RT-7.5"
description:  "BGP Policy - Match and Set Link Bandwidth Community"
testbed:  TESTBED_DUT_ATE_2LINKS
platform_exceptions:  {
  platform:  {
    vendor:  ARISTA
  }
  deviations:  {
    route_policy_under_afi_unsupported:  true
    omit_l2_mtu:  true
    missing_value_for_defaults:  true
    interface_enabled:  true
    default_network_instance:  "default"
    skip_set_rp_match_set_options:  true
    skip_setting_disable_metric_propagation:  true
    bgp_conditions_match_community_set_unsupported:  true
    bgp_extended_community_index_unsupported:  true
    skip_bgp_send_community_type: true
  }
}
platform_exceptions:  {
  platform:  {
    vendor:  CISCO
  }
  deviations:  {
    bgp_extended_community_set_unsupported:  true
    community_member_regex_unsupported: true
    skip_setting_statement_for_policy: true
    bgp_set_ext_community_set_refs_unsupported: true
    bgp_delete_link_bandwidth_unsupported: true
    skip_bgp_send_community_type: true
    bgp_extended_community_index_unsupported: true
    bgp_conditions_match_community_set_unsupported: true
    bgp_explicit_extended_community_enable: true
  }
}
tags:  TAGS_AGGREGATION
tags:  TAGS_DATACENTER_EDGE
