# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# proto-file: github.com/openconfig/featureprofiles/proto/feature.proto
# proto-message: FeatureProfile

id {
  name: "experimental_route_redistribution"
  version: 1
}

# https://github.com/openconfig/public/blob/e9e3a82693d1f26c61d7fbf85b3b2d0418d4af9e/doc/network_instance_redistribution.md
# Protocol tables
config_path {
  path: "/network-instances/network-instance/tables/table/config/protocol"
}
config_path {
  path: "/network-instances/network-instance/tables/table/config/address-family"
}
telemetry_path {
  path: "/network-instances/network-instance/tables/table/state/protocol"
}
telemetry_path {
  path: "/network-instances/network-instance/tables/table/state/address-family"
}


# Table-connections
config_path {
  path: "/network-instances/network-instance/table-connections/table-connection/config/src-protocol"
}
config_path {
  path: "/network-instances/network-instance/table-connections/table-connection/config/dst-protocol"
}
config_path {
  path: "/network-instances/network-instance/table-connections/table-connection/config/address-family"
}
config_path {
  path: "/network-instances/network-instance/table-connections/table-connection/config/import-policy"
}
config_path {
  path: "/network-instances/network-instance/table-connections/table-connection/config/default-import-policy"
}
telemetry_path {
  path: "/network-instances/network-instance/table-connections/table-connection/state/src-protocol"
}
telemetry_path {
  path: "/network-instances/network-instance/table-connections/table-connection/state/dst-protocol"
}
telemetry_path {
  path: "/network-instances/network-instance/table-connections/table-connection/state/address-family"
}
telemetry_path {
  path: "/network-instances/network-instance/table-connections/table-connection/state/import-policy"
}
telemetry_path {
  path: "/network-instances/network-instance/table-connections/table-connection/state/default-import-policy"
}



feature_profile_dependency {
  name: "bgp"
  version: 1
}

feature_profile_dependency {
  name: "localaggregates"
  version: 1
}

feature_profile_dependency {
  name: "bgp_policybase"
  version: 1
}
