# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "7c282986-8100-416a-9364-1893ae9df055"
plan_id: "gNOI-3.2"
description: "Per-Component Reboot"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    gnoi_fabric_component_reboot_unsupported: true
    gnoi_subcomponent_path: true
  }
}
