// Code generated by go run tools/addrundata; DO NOT EDIT.
package per_component_reboot_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "gNOI-3.2"
	rundata.TestDescription = "Per-Component Reboot"
	rundata.TestUUID = "7c282986-8100-416a-9364-1893ae9df055"
}
