// Code generated by go run tools/addrundata; DO NOT EDIT.
package backup_nhg_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "TE-11.1"
	rundata.TestDescription = "Backup NHG: Single NH"
	rundata.TestUUID = "ac89b122-9979-432f-aa82-363308c56a67"
}
