# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "261d317f-9bcc-43f9-a412-295ae6c008cf"
plan_id: "gNMI-1.16"
description: "fabric redundancy test"
testbed: TESTBED_DUT_ATE_2LINKS
