// Code generated by go run tools/addrundata; DO NOT EDIT.
package aggregate_forwarding_viable_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "RT-5.4"
	rundata.TestDescription = "Aggregate Forwarding Viable"
	rundata.TestUUID = "7a38f75a-0ff8-4a86-9398-e28c32de1862"
}
