// Code generated by go run tools/addrundata; DO NOT EDIT.
package route_installation_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "RT-1.2"
	rundata.TestDescription = "BGP Policy & Route Installation"
	rundata.TestUUID = "e386a26b-ca43-4510-9c21-9dbd8b36ae50"
}
