// Code generated by go run tools/addrundata; DO NOT EDIT.
package wrr_traffic_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "DP-1.9"
	rundata.TestDescription = "WRR traffic test"
	rundata.TestUUID = "50dd5501-d9c8-4888-9d9d-00f3c51e6088"
}
