name: "openconfig-lemming-dutate"
nodes: {
    name: "dut"
    vendor: OPENCONFIG
    model: "LEMMING"
}
nodes: {
    name: "otg"
    vendor: KEYSIGHT
    version: "0.0.1-9999" # Please update this with the local version from ixiatg-configmap.yaml
}
links: {
    a_node: "otg"
    a_int: "eth1"
    z_node: "dut"
    z_int: "eth1"
}
links: {
    a_node: "dut"
    a_int: "eth2"
    z_node: "otg"
    z_int: "eth2"
}
links: {
    a_node: "dut"
    a_int: "eth3"
    z_node: "otg"
    z_int: "eth3"
}
links: {
    a_node: "dut"
    a_int: "eth4"
    z_node: "otg"
    z_int: "eth4"
}
links: {
    a_node: "dut"
    a_int: "eth5"
    z_node: "otg"
    z_int: "eth5"
}
links: {
    a_node: "dut"
    a_int: "eth6"
    z_node: "otg"
    z_int: "eth6"
}
links: {
    a_node: "dut"
    a_int: "eth7"
    z_node: "otg"
    z_int: "eth7"
}
links: {
    a_node: "dut"
    a_int: "eth8"
    z_node: "otg"
    z_int: "eth8"
}
links: {
    a_node: "dut"
    a_int: "eth9"
    z_node: "otg"
    z_int: "eth9"
}
