# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# proto-file: github.com/openconfig/featureprofiles/proto/feature.proto
# proto-message: FeatureProfile

id {
  name: "experimental_telemetry_only"
  version: 1
}

# Fan
telemetry_path {
  path: "/components/component/fan/state/speed"
}

# Pipeline-counters lookup block
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/lookup-block/state/nexthop-memory"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/lookup-block/state/nexthop-memory-used"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/lookup-block/state/acl-memory-total-entries"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/lookup-block/state/acl-memory-used-entries"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/lookup-block/state/acl-memory-total-bytes"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/lookup-block/state/acl-memory-used-bytes"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/lookup-block/state/lookup-memory"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/lookup-block/state/lookup-memory-used"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/lookup-block/state/oversubscription"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/lookup-block/state/no-route"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/lookup-block/state/no-label"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/lookup-block/state/no-nexthop"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/lookup-block/state/invalid-packet"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/lookup-block/state/forwarding-policy"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/lookup-block/state/incorrect-software-state"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/lookup-block/state/rate-limit"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/lookup-block/state/fragment-total-drops"
}

# Pipeline counters queueing block
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/queueing-block/state/in-bytes"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/queueing-block/state/out-bytes"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/queueing-block/state/queue-memory"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/queueing-block/state/queue-memory-used"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/queueing-block/state/loopback-packets"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/queueing-block/state/loopback-bytes"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/queueing-block/state/oversubscription"
}

# Pipeline counters fabric block
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/fabric-block/state/in-bytes"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/fabric-block/state/out-bytes"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/fabric-block/state/in-packets"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/fabric-block/state/out-packets"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/fabric-block/state/in-low-priority-cells"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/fabric-block/state/out-low-priority-cells"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/fabric-block/state/in-high-priority-packets"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/fabric-block/state/out-high-priority-packets"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/fabric-block/state/in-low-priority-packets"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/fabric-block/state/out-low-priority-packets"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/fabric-block/state/oversubscription"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/fabric-block/state/lost-packets"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/fabric-block/state/out-high-priority"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/fabric-block/state/fabric-aggregate"
}

# Pipeline counters host interface block
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/host-interface-block/state/out-packets"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/host-interface-block/state/in-bytes"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/host-interface-block/state/out-bytes"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/host-interface-block/state/fragment-punt-pkts"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/host-interface-block/state/in-high-priority-packets"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/host-interface-block/state/out-high-priority-packets"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/host-interface-block/state/in-low-priority-packets"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/packet/host-interface-block/state/out-low-priority-packets"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/host-interface-block/state/oversubscription"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/host-interface-block/state/rate-limit"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/host-interface-block/state/in-high-priority"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/host-interface-block/state/out-high-priority"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/host-interface-block/state/in-low-priority"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/host-interface-block/state/out-low-priority"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/host-interface-block/state/fragment-punt"
}
telemetry_path {
    path: "/components/component/integrated-circuit/pipeline-counters/drop/host-interface-block/state/host-aggregate"
}


# Port
telemetry_path {
    path: "/components/component/port/breakout-mode/groups/group/state/breakout-speed"
}
telemetry_path {
    path: "/components/component/port/breakout-mode/groups/group/state/index"
}
telemetry_path {
    path: "/components/component/port/breakout-mode/groups/group/state/num-breakouts"
}
telemetry_path {
    path: "/components/component/port/breakout-mode/groups/group/state/num-physical-channels"
}
config_path {
    path: "/components/component/port/breakout-mode/groups/group/config/breakout-speed"
}
config_path {
    path: "/components/component/port/breakout-mode/groups/group/config/index"
}
config_path {
    path: "/components/component/port/breakout-mode/groups/group/config/num-breakouts"
}
config_path {
    path: "/components/component/port/breakout-mode/groups/group/config/num-physical-channels"
}

# Power supply
telemetry_path {
    path: "/components/component/power-supply/state/input-current"
}
telemetry_path {
    path: "/components/component/power-supply/state/output-current"
}
telemetry_path {
    path: "/components/component/power-supply/state/output-voltage"
}

# integrated circuit backplane
telemetry_path {
    path: "/components/component/integrated-circuit/backplane-facing-capacity/state/total"
}
telemetry_path {
    path: "/components/component/integrated-circuit/backplane-facing-capacity/state/consumed-capacity"
}
telemetry_path {
    path: "/components/component/integrated-circuit/backplane-facing-capacity/state/available-pct"
}

telemetry_path {
    path: "/components/component/properties/property/state/value"
}
telemetry_path {
    path: "/components/component/subcomponents/subcomponent/state/name"
}
telemetry_path {
    path: "/components/component/state/description"
}
telemetry_path {
    path: "/components/component/properties/property/state/value"
}
telemetry_path {
    path: "/components/component/state/parent"
}
telemetry_path {
    path: "/components/component/subcomponents/subcomponent/state/name"
}
telemetry_path {
  path: "/components/component/integrated-circuit/state/node-id"
}
telemetry_path {
  path: "/components/component/state/empty"
}
telemetry_path {
  path: "/components/component/state/firmware-version"
}
telemetry_path {
  path: "/components/component/state/hardware-version"
}
telemetry_path {
  path: "/components/component/state/mfg-date"
}
telemetry_path {
  path: "/components/component/state/mfg-name"
}
telemetry_path {
  path: "/components/component/state/name"
}
telemetry_path {
  path: "/components/component/state/oper-status"
}
telemetry_path {
  path: "/components/component/state/parent"
}
telemetry_path {
  path: "/components/component/state/part-no"
}
telemetry_path {
  path: "/components/component/state/serial-no"
}
telemetry_path {
  path: "/components/component/state/software-version"
}
telemetry_path {
  path: "/components/component/state/temperature/instant"
}
telemetry_path {
  path: "/components/component/state/type"
}
telemetry_path {
  path: "/components/component/transceiver/physical-channels/channel/state/input-power/instant"
}
telemetry_path {
  path: "/components/component/transceiver/physical-channels/channel/state/laser-bias-current/instant"
}
telemetry_path {
  path: "/components/component/transceiver/physical-channels/channel/state/output-power/instant"
}
telemetry_path {
  path: "/components/component/transceiver/state/form-factor"
}
telemetry_path {
  path: "/interfaces/interface/aggregation/state/member"
}
telemetry_path {
  path: "/interfaces/interface/ethernet/state/counters/in-maxsize-exceeded"
}
telemetry_path {
  path: "/interfaces/interface/hold-time/state/down"
}
telemetry_path {
  path: "/interfaces/interface/hold-time/state/up"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/carrier-transitions"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/in-discards"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/in-fcs-errors"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/in-pkts"
}
telemetry_path {
  path: "/interfaces/interface/state/cpu"
}
telemetry_path {
  path: "/interfaces/interface/state/hardware-port"
}
telemetry_path {
  path: "/interfaces/interface/state/last-change"
}
telemetry_path {
  path: "/interfaces/interface/state/management"
}
telemetry_path {
  path: "/interfaces/interface/state/physical-channel"
}
telemetry_path {
  path: "/interfaces/interface/state/transceiver"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv4/addresses/address/state/ip"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv4/addresses/address/state/prefix-length"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv6/addresses/address/state/ip"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv6/addresses/address/state/prefix-length"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/state/index"
}
telemetry_path {
  path: "/lacp/interfaces/interface/members/member/state/activity"
}
telemetry_path {
  path: "/lacp/interfaces/interface/members/member/state/collecting"
}
telemetry_path {
  path: "/lacp/interfaces/interface/members/member/state/distributing"
}
telemetry_path {
  path: "/lacp/interfaces/interface/state/system-id-mac"
}
telemetry_path {
  path: "/qos/interfaces/interface/output/queues/queue/state/dropped-pkts"
}
telemetry_path {
  path: "/qos/interfaces/interface/output/queues/queue/state/name"
}
telemetry_path {
  path: "/qos/interfaces/interface/output/queues/queue/state/transmit-octets"
}
telemetry_path {
  path: "/qos/interfaces/interface/output/queues/queue/state/transmit-pkts"
}
telemetry_path {
  path: "/qos/interfaces/interface/output/scheduler-policy/state/name"
}
telemetry_path {
  path: "/system/alarms/alarm/state/id"
}
telemetry_path {
  path: "/system/alarms/alarm/state/resource"
}
telemetry_path {
  path: "/system/alarms/alarm/state/severity"
}
telemetry_path {
  path: "/system/alarms/alarm/state/text"
}
telemetry_path {
  path: "/system/alarms/alarm/state/time-created"
}
telemetry_path {
  path: "/system/alarms/alarm/state/type-id"
}
telemetry_path {
  path: "/system/cpus/cpu/state/total/avg"
}
telemetry_path {
  path: "/system/memory/state/counters/correctable-ecc-errors"
}
telemetry_path {
  path: "/system/memory/state/counters/uncorrectable-ecc-errors"
}
telemetry_path {
  path: "/system/memory/state/free"
}
telemetry_path {
  path: "/system/memory/state/physical"
}
telemetry_path {
  path: "/system/memory/state/used"
}
telemetry_path {
  path: "/system/processes/process/state/cpu-utilization"
}
telemetry_path {
  path: "/system/processes/process/state/memory-usage"
}
telemetry_path {
  path: "/system/processes/process/state/name"
}
telemetry_path {
  path: "/system/processes/process/state/pid"
}
telemetry_path {
  path: "/system/state/hostname"
}
config_path {
    path: "/components/component/config/name"
}
config_path {
    path: "/components/component/integrated-circuit/config/node-id"
}
