# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "a5b892e1-192d-45ff-89b5-a84a2865fdb2"
plan_id: "RT-2.1"
description: "Base IS-IS Process and Adjacencies"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    isis_multi_topology_unsupported: true
    isis_explicit_level_authentication_config: true
    isis_interface_level1_disable_required: true
    missing_isis_interface_afi_safi_enable: true
    isis_restart_suppress_unsupported: true
    explicit_interface_in_default_vrf: true
    missing_value_for_defaults: true
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    isis_single_topology_required: true
    set_isis_auth_with_interface_authentication_container: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    omit_l2_mtu: true
    missing_value_for_defaults: true
    interface_enabled: true
    default_network_instance: "default"
    isis_instance_enabled_required: true
    isis_interface_afi_unsupported: true
    fr_breakout_fix: true
  }
}
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    isis_level_enabled: true
    interface_ref_interface_id_format: true
  }
}
