# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid:  "6af949d5-9a5f-4aed-88f2-076143857e9b"
plan_id:  "RT-7.10"
description:  "Routing policy statement insertion and removal"
testbed:  TESTBED_DUT_ATE_2LINKS
platform_exceptions:  {
  platform:  {
    vendor:  NOKIA
  }
  deviations:  {
    explicit_interface_in_default_vrf:  true
    interface_enabled:  true
    skip_bgp_send_community_type:  true
    bgp_actions_set_community_method_unsupported:  true
  }
}
platform_exceptions:  {
  platform:  {
    vendor:  ARISTA
  }
  deviations:  {
    omit_l2_mtu:  true
    interface_enabled:  true
    default_network_instance:  "default"
  }
}
platform_exceptions:  {
  platform:  {
    vendor:  CISCO
  }
  deviations:  {
    bgp_community_type_slice_input_unsupported: true
  }
}
tags:  TAGS_DATACENTER_EDGE
