// Code generated by go run tools/addrundata; DO NOT EDIT.
package qos_basic_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "DP-1.14"
	rundata.TestDescription = "QoS basic test"
	rundata.TestUUID = "8e6a4bdd-7e4e-4c2a-90d8-55f3543f9e18"
}
