# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "b1da9742-66f5-460d-860b-58ab3f5c34f3"
plan_id: "DP-1.2"
description: "QoS policy feature config"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: JUNIPER
  }
  deviations: {
    state_path_unsupported: true
    drop_weight_leaves_unsupported: true
    explicit_interface_ref_definition: true
  }
}
