# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "65aab5ff-2e76-4437-a77b-7ed10f663c5e"
plan_id: "P4RT-7.2"
description: "LLDP: PacketOut"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_p4rt_node_component: true
    explicit_port_speed: true
    explicit_interface_in_default_vrf: true
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    interface_enabled: true
  }
}
