# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "d54b1029-6f8e-4dc7-a50d-99d6e4f59474"
plan_id: "RT-3.2"
description: "Multiple <Protocol, DSCP> Rules for VRF Selection"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: CISCO
    hardware_model: "CISCO-8808"
    hardware_model: "CISCO-8202-32FH-M"
    hardware_model: "8201"
    hardware_model: "xrd"
  }
  deviations: {
    interface_ref_config_unsupported: true
  }
}
