// Code generated by go run tools/addrundata; DO NOT EDIT.
package policy_based_vrf_selection_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "RT-3.2"
	rundata.TestDescription = "Multiple <Protocol, DSCP> Rules for VRF Selection"
	rundata.TestUUID = "d54b1029-6f8e-4dc7-a50d-99d6e4f59474"
}
