# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

id {
  name: "interface_singleton"
  version: 1
}

# Interface basic config.
config_path {
  path: "/interfaces/interface/config/name"
}
telemetry_path {
  path: "/interfaces/interface/state/name"
}
config_path {
  path: "/interfaces/interface/config/id"
}
telemetry_path {
  path: "/interfaces/interface/state/id"
}
config_path {
  path: "/interfaces/interface/config/description"
}
telemetry_path {
  path: "/interfaces/interface/state/description"
}
config_path {
  path: "/interfaces/interface/config/type"
}
telemetry_path {
  path: "/interfaces/interface/state/type"
}
config_path {
  path: "/interfaces/interface/config/enabled"
}
telemetry_path {
  path: "/interfaces/interface/state/enabled"
}
config_path {
  path: "/interfaces/interface/config/forwarding-viable"
}
telemetry_path {
  path: "/interfaces/interface/state/forwarding-viable"
}
config_path {
  path: "/interfaces/interface/config/loopback-mode"
}
telemetry_path {
  path: "/interfaces/interface/state/loopback-mode"
}
telemetry_path {
  path: "/interfaces/interface/state/oper-status"
}
telemetry_path {
  path: "/interfaces/interface/state/admin-status"
}

# Interface hold timers
config_path {
  path: "/interfaces/interface/hold-time/config/down"
}
telemetry_path {
  path: "/interfaces/interface/hold-time/state/down"
}
config_path {
  path: "/interfaces/interface/hold-time/config/up"
}
telemetry_path {
  path: "/interfaces/interface/hold-time/state/up"
}

# Interface counters
telemetry_path {
  path: "/interfaces/interface/state/counters/out-octets"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/in-broadcast-pkts"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/in-discards"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/in-errors"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/in-multicast-pkts"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/in-octets"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/in-unicast-pkts"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/in-unknown-protos"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/out-broadcast-pkts"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/out-discards"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/out-errors"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/out-multicast-pkts"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/out-octets"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/out-pkts"
}
telemetry_path {
  path: "/interfaces/interface/state/counters/out-unicast-pkts"
}

# Ethernet config
config_path {
  path: "/interfaces/interface/ethernet/config/mac-address"
}
telemetry_path {
  path: "/interfaces/interface/ethernet/state/mac-address"
}
config_path {
  path: "/interfaces/interface/ethernet/config/port-speed"
}
telemetry_path {
  path: "/interfaces/interface/ethernet/state/port-speed"
}
config_path {
  path: "/interfaces/interface/ethernet/config/duplex-mode"
}
telemetry_path {
  path: "/interfaces/interface/ethernet/state/duplex-mode"
}
config_path {
  path: "/interfaces/interface/ethernet/config/enable-flow-control"
}
telemetry_path {
  path: "/interfaces/interface/ethernet/state/enable-flow-control"
}
config_path {
  path: "/interfaces/interface/ethernet/config/auto-negotiate"
}
telemetry_path {
  path: "/interfaces/interface/ethernet/state/auto-negotiate"
}
telemetry_path {
  path: "/interfaces/interface/ethernet/state/counters/in-mac-pause-frames"
}
telemetry_path {
  path: "/interfaces/interface/ethernet/state/counters/out-mac-pause-frames"
}
telemetry_path {
  path: "/interfaces/interface/ethernet/state/negotiated-port-speed"
}

# Sub-interface
config_path {
  path: "/interfaces/interface/subinterfaces/subinterface/config/description"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/state/description"
}
config_path {
  path: "/interfaces/interface/subinterfaces/subinterface/config/enabled"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/state/enabled"
}
config_path {
  path: "/interfaces/interface/subinterfaces/subinterface/config/index"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/state/index"
}

# Sub-interface ipv4
config_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv4/config/enabled"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv4/state/enabled"
}
config_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv4/config/mtu"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv4/state/mtu"
}

# Sub-interface ipv6
config_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv6/config/enabled"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv6/state/enabled"
}
config_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv6/config/mtu"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv6/state/mtu"
}

# Sub-interface counters
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv4/addresses/address/state/ip"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv4/state/counters/in-pkts"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv4/state/counters/out-pkts"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv6/addresses/address/state/ip"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv6/state/counters/in-discarded-pkts"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv4/state/counters/out-discarded-pkts"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv6/state/counters/in-pkts"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv6/state/counters/out-discarded-pkts"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv6/state/counters/out-pkts"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv6/state/counters/in-pkts"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv6/state/counters/out-forwarded-pkts"
}
telemetry_path {
  path: "/interfaces/interface/subinterfaces/subinterface/ipv6/state/counters/out-pkts"
}
