# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "d8f6569c-03c0-4f63-b311-f6bb1ed1ed48"
plan_id: "PF-1.4"
description: "GUEv1 Decapsulation rule using destination-address-prefix-set and TTL and DSCP behavior test"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    interface_enabled: true
    default_network_instance: "default"
    decapsulate_gue_oc_unsupported: true
    policy_rule_counters_oc_unsupported: true
  }
}
