# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid:  "1d21e3cf-25c0-4e44-8988-582188e37452"
plan_id:  "RT-7.1"
description:  "BGP default policies"
testbed:  TESTBED_DUT_ATE_2LINKS
platform_exceptions:  {
  platform:  {
    vendor:  JUNIPER
  }
  deviations:  {
    isis_level_enabled:  true
    skip_non_bgp_route_export_check:  true
    default_import_export_policy: true
  }
}
platform_exceptions:  {
  platform:  {
    vendor:  ARISTA
  }
  deviations:  {
    interface_enabled:  true
    default_network_instance:  "default"
    missing_isis_interface_afi_safi_enable: true
    isis_interface_afi_unsupported: true
    isis_instance_enabled_required: true
    default_import_export_policy: true
    bgp_default_policy_unsupported: true
  }
}
platform_exceptions:  {
  platform:  {
    vendor:  NOKIA
  }
  deviations:  {
    explicit_interface_in_default_vrf: true
    explicit_port_speed: true
    interface_enabled:  true
    static_protocol_name: "static"
    skip_non_bgp_route_export_check:  true
    missing_isis_interface_afi_safi_enable: true
    bgp_default_policy_unsupported: true
    skip_prefix_set_mode: true
  }
}
platform_exceptions:  {
  platform:  {
    vendor:  CISCO
  }
  deviations:  {
    missing_isis_interface_afi_safi_enable: true
    bgp_default_policy_unsupported: true
    prepolicy_received_routes: true
  }
}
