name: NOSImage validation script

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: "49 0 * * *"

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
      with:
        go-version: stable
        cache: false
    - name: Generate Examples and Check No Diff
      run: |
        cd tools/nosimage
        go generate ./example

        git diff --exit-code --ignore-all-space --ignore-blank-lines

    - name: Validate Good Example
      run: |
        cd tools/nosimage
        go run validate/validate.go -file example/valid_example_nosimageprofile.textproto; rm -rf tmp

    - name: Validate Bad Example
      run: |
        cd tools/nosimage
        for file in example/invalid-*.textproto; do
          if go run validate/validate.go -file "$file"; then
            echo "Validation passed for $file, but failure expected"
            exit 1
          fi
        done
        rm -rf tmp
