name: Rundata Check
on: [pull_request]

jobs:
  check_rundata:
    name: Check for Rundata
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@v3
    - name: Check that addrundata is up to date.
      run: go run ./tools/addrundata
