name: Rundata Check
on: [pull_request]

jobs:
  check_rundata:
    name: Check for Rundata
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - name: Check that addrundata is up to date.
      run: go run ./tools/addrundata
