name: Validate Deviations

on:
  push:
    branches: [ main ]

  pull_request:
    paths:
      - 'proto/metadata.proto'
      - 'internal/deviations/deviations.textproto'
      - 'tools/validate_deviations/**'

jobs:
  validate-deviations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version-file: 'go.mod'
          cache: false

      # - name: Run Go Unit Tests
      #   run: |
      #     # Run the unit tests for the validation tool.
      #     cd tools/validate_deviations
      #     go test .

      - name: Run Validation Script Integration Tests
        run: |
          # Build the validator binary and then run the shell-based integration tests.
          cd tools/validate_deviations
          go build .
          ./validate_deviations_test.sh

      # TODO: remove exempt_deviations_file from cmd once existed deviation are fixed to inlcude all necesaary fields
      - name: Run Main Deviation File Validation
        run: |
          # Run the validator on the main deviations file.
          go run tools/validate_deviations/validate_deviations.go \
            --deviations_file internal/deviations/deviations.textproto \
            --exempt_deviations_file tools/validate_deviations/exempt_deviations.txt \
            --skip_completeness_check