// Code generated by go run tools/addrundata; DO NOT EDIT.
package telemetry_inventory_test

import "github.com/openconfig/featureprofiles/internal/rundata"

func init() {
	rundata.TestPlanID = "gNMI-1.4"
	rundata.TestDescription = "Telemetry: Inventory"
	rundata.TestUUID = "44fed7d9-4c79-4952-8b83-fbd5f7138ae9"
}
