# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "78f99d29-c7db-4e6d-8284-614154efc0d1"
plan_id: "P4RT-1.2"
description: "P4RT Daemon Failure"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: NOKIA
    hardware_model: "7250-ixr10e"
    hardware_model: "ixr10"
  }
  deviations: {
    explicit_p4rt_node_component: true
  }
}
