# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

plan_id:  "Certz"
description:  "gNSI Client Certificate Baseline Tests"
testbed:  TESTBED_DUT_ATE_2LINKS
