# proto-file: third_party/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

plan_id: "RT-5.8"
description: "IPv6 Link Local"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    interface_enabled: true
    default_network_instance: "default"
  }
}
