# proto-file: github.com/openconfig/featureprofiles/proto/metadata.proto
# proto-message: Metadata

uuid: "26ee6729-368d-4583-ada4-6b3baf70c436"
plan_id: "RT-1.64"
description: "RT-1.64 BGP Import/Export Policy (Control plane only) Functional Test Case"
testbed: TESTBED_DUT_ATE_2LINKS
platform_exceptions: {
  platform: {
    vendor: NOKIA
  }
  deviations: {
    explicit_interface_in_default_vrf: true
    interface_enabled: true
  }
}
platform_exceptions: {
  platform: {
    vendor: ARISTA
  }
  deviations: {
    omit_l2_mtu: true
    interface_enabled: true
    default_network_instance: "default"
  }
}
platform_exceptions: {
  platform: {
    vendor: CISCO
  }
  deviations: {
    interface_enabled: true
  }
}
